import {notFound} from 'next/navigation';
import {findArticle,listPublishedArticles} from '../../../lib/article-storage.js';
import {readPublicListArticles} from '../../../lib/public-data.js';
import {articleSchemaType} from '../../../lib/article-types.js';
import '../artikel.css';
export const dynamic='force-dynamic';
export async function generateMetadata({params}){const a=await findArticle((await params).slug);if(!a||a.status!=='PUBLISHED')return{};const canonical=a.seo?.canonical||`https://berita-auto.vercel.app/artikel/${a.slug}`;return{title:a.metaTitle||a.title,description:a.metaDescription||a.excerpt,alternates:{canonical},robots:{index:true,follow:true},openGraph:{type:'article',url:canonical,title:a.metaTitle||a.title,description:a.metaDescription||a.excerpt,siteName:'Berita Auto',images:a.imageUrl?[{url:a.imageUrl,width:1200,height:675,alt:a.imageAlt||a.title}]:[]}}}
export default async function ArticleDetail({params}){const a=await findArticle((await params).slug);if(!a||a.status!=='PUBLISHED')notFound();const [allArticles,news]=await Promise.all([listPublishedArticles(),readPublicListArticles()]);const relatedArticles=allArticles.filter(x=>x.id!==a.id&&(x.category===a.category||x.topicCluster===a.topicCluster)).slice(0,3);const relatedNews=news.filter(x=>x.contentType!=='article'&&x.category===a.category).slice(0,3);const headings=String(a.content||'').match(/^#{2,3} .+$/gm)||[];const schema={"@context":"https://schema.org","@type":articleSchemaType(a),headline:a.title,description:a.excerpt,datePublished:a.createdAt,dateModified:a.updatedAt,mainEntityOfPage:a.seo?.canonical||`https://berita-auto.vercel.app/artikel/${a.slug}`,image:a.imageUrl?[a.imageUrl]:undefined};return <main className="article-detail-public">{a.imageUrl&&<figure className="article-hero-image"><img src={a.imageUrl} alt={a.imageAlt||a.title} width="1200" height="675" fetchPriority="high"/><figcaption>{a.imageCaption||'Ilustrasi Berita Auto'}</figcaption></figure>}<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><span className="eyebrow">ARTIKEL · {a.articleType}</span><h1>{a.title}</h1><p className="article-standfirst">{a.excerpt}</p><p className="article-byline">Berita Auto · Diperbarui {new Date(a.updatedAt).toLocaleDateString('id-ID')} · {a.readingTime||Math.max(3,Math.ceil(String(a.content||'').split(/\s+/).length/200))} menit baca</p>{headings.length>2&&<nav className="article-toc"><strong>Daftar Isi</strong>{headings.map((h,i)=>{const text=h.replace(/^###?\s/,'');return <a key={i} href={`#${text.toLowerCase().replace(/[^a-z0-9\s-]/g,'').replace(/\s+/g,'-')}`}>{text}</a>})}</nav>}<article className="article-body"><MarkdownLike content={a.content||''}/></article><section className="article-source-box"><h2>Sumber Referensi</h2>{(a.sources||[]).map((s,i)=><a key={i} href={s.url} target="_blank" rel="noopener noreferrer">{s.name||s.url}</a>)}</section>{relatedArticles.length>0&&<section className="article-source-box"><h2>Artikel Terkait</h2>{relatedArticles.map(x=><a key={x.id} href={`/artikel/${x.slug}`}>{x.title}</a>)}</section>}{relatedNews.length>0&&<section className="article-source-box"><h2>Berita Terkait</h2>{relatedNews.map(x=><a key={x.id} href={`/berita/${x.slug||x.id}`}>{x.title}</a>)}</section>}</main>}
function MarkdownLike({content}){return <>{String(content).split(/\n\n+/).map((block,i)=>{const t=block.trim();if(!t)return null;if(t.startsWith('### ')){const x=t.slice(4);return <h3 key={i} id={x.toLowerCase().replace(/[^a-z0-9\s-]/g,'').replace(/\s+/g,'-')}>{x}</h3>}if(t.startsWith('## ')){const x=t.slice(3);return <h2 key={i} id={x.toLowerCase().replace(/[^a-z0-9\s-]/g,'').replace(/\s+/g,'-')}>{x}</h2>}if(/^\d+\. /m.test(t))return <ol key={i}>{t.split('\n').map((x,j)=><li key={j}>{x.replace(/^\d+\. /,'')}</li>)}</ol>;if(/^[-*] /m.test(t))return <ul key={i}>{t.split('\n').map((x,j)=><li key={j}>{x.replace(/^[-*] /,'')}</li>)}</ul>;return <p key={i}>{t}</p>})}</>}
