import {auth} from '../../../../auth.js';
import {runArticlePipeline} from '../../../../lib/article-pipeline.js';
import {discoverArticleOpportunities} from '../../../../lib/article-ideas.js';
import {listArticleAutomationRuns} from '../../../../lib/article-automation-telemetry.js';
import {findArticle,listAllArticles,upsertArticle,normalizeArticle} from '../../../../lib/article-storage.js';
import {generateAndPersistArticleImage} from '../../../../lib/article-image.js';

export const runtime='nodejs';export const dynamic='force-dynamic';
async function allowed(){const session=await auth().catch(()=>null);const list=(process.env.ADMIN_EMAILS||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);const email=session?.user?.email?.trim().toLowerCase();return Boolean(email&&list.includes(email))}
export async function GET(){if(!await allowed())return Response.json({error:'forbidden'},{status:403});const [runs,articles]=await Promise.all([listArticleAutomationRuns(20),listAllArticles()]);const today=new Date().toISOString().slice(0,10);return Response.json({runs,articlesToday:articles.filter(x=>String(x.createdAt||'').startsWith(today)).length,published:articles.filter(x=>x.status==='PUBLISHED').length,needsReview:articles.filter(x=>x.status==='NEEDS_REVIEW').length,imageFailed:articles.filter(x=>x.imageStatus==='failed').length},{headers:{'cache-control':'no-store'}})}
export async function POST(request){if(!await allowed())return Response.json({error:'forbidden'},{status:403});const body=await request.json().catch(()=>({}));const action=String(body?.action||'run').toLowerCase();if(action==='opportunity'){const candidates=await discoverArticleOpportunities({limit:20});return Response.json({status:'dry_run',candidateCount:candidates.length,candidates:candidates.slice(0,10).map(x=>({topic:x.topic,primaryQuery:x.primaryQuery,category:x.category,articleType:x.articleType,searchScore:x.searchScore||null,source:x.opportunityReason,reason:x.aiReason||null}))})}
if(action==='repair_failed_images'){const rows=await listAllArticles();const targets=rows.filter(x=>x.content&&x.sourceCount>=2&&!x.imageUrl&&x.imageStatus==='failed').slice(0,3);const results=[];for(const article of targets){try{const image=await generateAndPersistArticleImage(article);const saved=await upsertArticle(normalizeArticle({...article,...image,imageStatus:'ready'}));results.push({articleId:saved.id,status:'ready',imageSourceType:saved.imageSourceType})}catch(error){const code=String(error?.imageErrorCode||error?.message||'image_generation_failed').replace(/[^a-z0-9_:-]/gi,'_').slice(0,100);results.push({articleId:article.id,status:'failed',imageErrorCode:code})}}return Response.json({status:'completed',processed:targets.length,results})}
if(action==='repair_image'){const id=String(body?.articleId||'').trim();if(!id)return Response.json({error:'article_id_required'},{status:400});const article=await findArticle(id);if(!article)return Response.json({error:'article_not_found'},{status:404});try{const image=await generateAndPersistArticleImage(article);const saved=await upsertArticle(normalizeArticle({...article,...image,imageStatus:'ready'}));return Response.json({status:'ready',article:saved})}catch(error){return Response.json({status:'failed',articleId:id,imageErrorCode:String(error?.imageErrorCode||error?.message||'image_generation_failed').replace(/[^a-z0-9_:-]/gi,'_').slice(0,100)},{status:502})}}
const result=await runArticlePipeline({mode:'auto'},{dryRun:false,scheduled:false,trigger:'admin'});return Response.json({status:String(result.status||'failed').toLowerCase(),reason:result.reason||null,article:result.article||null,idea:result.idea||null,quality:result.quality||null,research:result.research||null,candidatesEvaluated:result.candidateCount||0,imageStatus:result.article?.imageStatus||null})}
