import {auth} from '../../../../auth.js';
import {runArticlePipeline} from '../../../../lib/article-pipeline.js';
import {discoverArticleOpportunities} from '../../../../lib/article-ideas.js';
import {listArticleAutomationRuns} from '../../../../lib/article-automation-telemetry.js';
import {findArticle,listAllArticles,upsertArticle,normalizeArticle} from '../../../../lib/article-storage.js';
import {generateAndPersistArticleImageWithRecovery} from '../../../../lib/article-image-recovery.js';
import {checkArticleImageStorageHealth} from '../../../../lib/article-image.js';

export const runtime='nodejs';
export const dynamic='force-dynamic';
async function allowed(){const session=await auth().catch(()=>null);const list=(process.env.ADMIN_EMAILS||'').split(',').map(v=>v.trim().toLowerCase()).filter(Boolean);const email=session?.user?.email?.trim().toLowerCase();return Boolean(email&&list.includes(email))}
const isFallbackImage=a=>String(a?.imageSourceType||'').toLowerCase()==='branded_fallback'||String(a?.imageDeliveryMode||'').toLowerCase()==='dynamic'||String(a?.imageUrl||'').includes('/api/article-image-fallback/');
export async function GET(){if(!await allowed())return Response.json({error:'forbidden'},{status:403});const [runs,storageHealth]=await Promise.all([listArticleAutomationRuns(20),checkArticleImageStorageHealth().catch(()=>({configured:Boolean(process.env.BLOB_READ_WRITE_TOKEN),healthy:false,status:'unavailable',code:'storage_health_error'}))]);return Response.json({runs,storageHealth},{headers:{'cache-control':'no-store'}})}
export async function POST(request){if(!await allowed())return Response.json({error:'forbidden'},{status:403});const body=await request.json().catch(()=>({}));const action=String(body?.action||'run').toLowerCase();if(action==='opportunity'){const candidates=await discoverArticleOpportunities({limit:20});return Response.json({status:'dry_run',candidateCount:candidates.length,candidates:candidates.slice(0,10).map(x=>({topic:x.topic,primaryQuery:x.primaryQuery,category:x.category,articleType:x.articleType,searchScore:x.searchScore||null,source:x.opportunityReason,reason:x.aiReason||null}))})}
if(action==='repair_failed_images'){const storage=await checkArticleImageStorageHealth().catch(()=>({configured:false,healthy:false,status:'unavailable',code:'storage_health_error'}));if(!storage.healthy)return Response.json({status:'skipped',reason:'image_storage_unhealthy',storageHealth:storage,processed:0,results:[]});const rows=await listAllArticles();const targets=rows.filter(x=>x.content&&x.sourceCount>=2&&(x.imageStatus==='failed'||x.lastImageAttemptStatus==='failed'||!x.imageUrl||isFallbackImage(x))).slice(0,3);const results=[];for(const article of targets){try{const image=await generateAndPersistArticleImageWithRecovery(article,{maxAttempts:3});const next={...article,...image,imageStatus:image.imageStatus||'ready',lastImageAttemptStatus:image.imageStatus==='fallback'?'failed':'success',lastImageErrorCode:image.imageStatus==='fallback'?(image.lastImageErrorCode||image.imageFailureCode||'IMAGE_RECOVERY_EXHAUSTED'):null};const saved=await upsertArticle(normalizeArticle(next));results.push({articleId:saved.id,status:saved.imageStatus==='fallback'?'fallback':'ready',imageSourceType:saved.imageSourceType,imageAttemptCount:saved.imageAttemptCount||3,imageRecoveredAutomatically:Boolean(saved.imageRecoveredAutomatically)})}catch(error){const code=String(error?.imageErrorCode||error?.message||'image_generation_failed').replace(/[^a-z0-9_:-]/gi,'_').slice(0,100);results.push({articleId:article.id,status:'failed',imageErrorCode:code,imageAttemptCount:error?.imageAttemptCount||3})}}return Response.json({status:'completed',processed:targets.length,results,storageHealth:storage})}
if(action==='repair_image'){const id=String(body?.articleId||'').trim();if(!id)return Response.json({error:'article_id_required'},{status:400});const article=await findArticle(id);if(!article)return Response.json({error:'article_not_found'},{status:404});const storage=await checkArticleImageStorageHealth().catch(()=>({configured:false,healthy:false,status:'unavailable',code:'storage_health_error'}));if(!storage.healthy)return Response.json({status:'skipped',reason:'image_storage_unhealthy',articleId:id,storageHealth:storage},{status:503});try{const image=await generateAndPersistArticleImageWithRecovery(article,{maxAttempts:3});const saved=await upsertArticle(normalizeArticle({...article,...image,imageStatus:image.imageStatus||'ready',lastImageAttemptStatus:image.imageStatus==='fallback'?'failed':'success'}));return Response.json({status:saved.imageStatus==='fallback'?'fallback':'ready',article:saved,storageHealth:storage})}catch(error){return Response.json({status:'failed',articleId:id,imageErrorCode:String(error?.imageErrorCode||error?.message||'image_generation_failed').replace(/[^a-z0-9_:-]/gi,'_').slice(0,100),imageAttemptCount:error?.imageAttemptCount||3,storageHealth:storage},{status:502})}}
const result=await runArticlePipeline({mode:'auto'},{dryRun:false,scheduled:false,trigger:'admin'});return Response.json({status:String(result.status||'failed').toLowerCase(),reason:result.reason||null,article:result.article||null,idea:result.idea||null,quality:result.quality||null,research:result.research||null,candidatesEvaluated:result.candidateCount||0,imageStatus:result.article?.imageStatus||null})}
