'use client';
import {useEffect,useMemo,useState} from 'react';

const TABS=[['automation','Automation / News Pipeline'],['berita','Berita'],['distribusi','Distribusi'],['penonton','Penonton'],['ai','AI & Processing'],['system','System'],['notes','Catatan & Perbaikan']];
const fmt=value=>{if(!value)return '-';const d=new Date(value);return Number.isNaN(d.getTime())?'-':new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Jakarta'}).format(d)+' WIB'};
const dayKey=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta'}).format(new Date());
const publicTime=a=>Date.parse(a?.publishedAt||a?.sitePublishedAt||a?.sourcePublishedAt||a?.createdAt||0)||0;
const warning=a=>Array.isArray(a?.publishWarnings)&&a.publishWarnings.length>0||a?.qualityStatus==='warning'||a?.qualityStatus==='degraded';
const status=a=>a?.publishStatus==='rejected'?'Tidak Dipublish':warning(a)?'Published Warning':'Published';
export default function AdminWorkspace({initialArticles=[],initialTab='automation',initialArticle=null}){
 const [tab,setTab]=useState(initialTab); const [articles,setArticles]=useState(initialArticles); const [selected,setSelected]=useState(initialArticle); const [detailCache,setDetailCache]=useState({}); const [sort,setSort]=useState('latest'); const [filter,setFilter]=useState(''); const [query,setQuery]=useState(''); const [dashboard,setDashboard]=useState(null); const [analytics,setAnalytics]=useState(null);
 useEffect(()=>{const onPop=()=>{const p=new URLSearchParams(location.search);setTab(p.get('tab')||'automation');setSelected(articles.find(a=>a.id===p.get('article'))||null)};window.addEventListener('popstate',onPop);return()=>window.removeEventListener('popstate',onPop)},[articles]);
 useEffect(()=>{fetch('/api/admin-berita/dashboard',{cache:'no-store'}).then(r=>r.ok?r.json():null).then(x=>{if(x){setDashboard(x);setAnalytics(x.analytics)}}).catch(()=>{})},[]);
 const navigate=(nextTab,articleId='')=>{setTab(nextTab);const p=new URLSearchParams(location.search);p.set('tab',nextTab);if(articleId)p.set('article',articleId);else p.delete('article');history.pushState({},'',`/admin-berita?${p}`)};
 const openArticle=async a=>{setSelected(a);navigate('berita',a.id);if(detailCache[a.id]){setSelected(detailCache[a.id]);return}try{const r=await fetch(`/api/admin-berita/article?id=${encodeURIComponent(a.id)}`,{cache:'no-store'});if(r.ok){const d=await r.json();setDetailCache(c=>({...c,[a.id]:d.article}));setSelected(d.article)}}catch{}};
 const visible=useMemo(()=>{let rows=[...articles];if(filter==='warning')rows=rows.filter(warning);if(filter==='rejected')rows=rows.filter(a=>a.publishStatus==='rejected');if(filter==='paraphrase')rows=rows.filter(a=>a.paraphraseStatus==='success');if(filter==='translated')rows=rows.filter(a=>a.translationStatus==='translated');if(query)rows=rows.filter(a=>[a.title,a.sourceName,a.category].some(v=>String(v||'').toLowerCase().includes(query.toLowerCase())));if(sort==='today')rows.sort((a,b)=>(b.todayViews||0)-(a.todayViews||0));else if(sort==='all')rows.sort((a,b)=>(b.totalViews||b.views||0)-(a.totalViews||a.views||0));else rows.sort((a,b)=>publicTime(b)-publicTime(a));return rows.slice(0,100)},[articles,filter,query,sort]);
 const metrics=dashboard?.metrics||{};
 return <main className="admin-shell"><header className="admin-topbar"><div><span className="admin-kicker">BERITA AUTO</span><strong>Berita Auto</strong><small className="admin-header-subtitle">Kelola berita, publikasi, AI, terjemahan, dan automation.</small></div><div className="admin-actions"><a href="/" className="admin-link">Buka Website</a><span className="admin-user">{dashboard?.email||'Administrator'}</span></div></header><section className="admin-content">
  <section className="admin-hero"><div><span className="admin-label">NEWS PIPELINE</span><h1>{tab==='automation'?'Automation / News Pipeline':TABS.find(x=>x[0]===tab)?.[1]||'Admin'}</h1><p>Monitoring publikasi, berita, distribusi, penonton, AI, dan perbaikan.</p></div><div className="pipeline-health"><span className="status-badge status-good">{dashboard?.automation?.status||'Healthy'}</span><small>Last cycle {fmt(dashboard?.automation?.lastCycle)}</small></div></section>
  <section className="admin-summary-grid compact"><button onClick={()=>{setFilter('');navigate('berita')}}><span>Published</span><strong>{metrics.published??0}</strong></button><button onClick={()=>navigate('berita')}><span>Artikel Hari Ini</span><strong>{metrics.todayPublished??0}</strong></button><button onClick={()=>{setFilter('paraphrase');navigate('berita')}}><span>Parafrase</span><strong>{metrics.paraphrase??0}</strong></button><button onClick={()=>{setFilter('translated');navigate('berita')}}><span>Terjemahan</span><strong>{metrics.translation??0}</strong></button><div><span>Total Penayangan</span><strong>{analytics?.totalViews??0}</strong></div><div><span>Penayangan Hari Ini</span><strong>{analytics?.todayViews??0}</strong></div><div><span>Jumlah Kategori</span><strong>{metrics.categoryCount??0}</strong></div><div><span>Jumlah Sumber</span><strong>{metrics.sourceCount??0}</strong></div></section>
  <nav className="admin-tabs" aria-label="Admin sections">{TABS.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>navigate(id)}>{label}</button>)}</nav>
  {tab==='automation'&&<Automation dashboard={dashboard}/>} {tab==='berita'&&<section className="admin-master-detail"><section className="admin-panel article-workspace"><div className="panel-head"><div><p className="admin-label">BERITA</p><h2>Berita Terbaru</h2></div><div className="admin-filters"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari artikel..."/><select value={sort} onChange={e=>setSort(e.target.value)}><option value="latest">Terbaru</option><option value="today">Terpopuler Hari Ini</option><option value="all">Terpopuler Sepanjang Waktu</option></select><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Semua</option><option value="warning">Published Warning</option><option value="rejected">Tidak Dipublish</option><option value="paraphrase">Parafrase</option><option value="translated">Terjemahan</option></select></div></div><div className="article-master-list">{visible.map(a=><button key={a.id} className={`article-master-row${selected?.id===a.id?' active':''}`} onClick={()=>openArticle(a)}><div className="thumb">{a.imageUrl?<img src={a.imageUrl} alt="" width="72" height="48"/>:<span>BA</span>}</div><div className="article-main"><h3>{a.title}</h3><p>{a.category||'Tanpa Kategori'} · {a.sourceName||'Sumber publik'} · {fmt(a.publishedAt||a.sitePublishedAt)}</p><div className="article-processing-badges"><span className={status(a)==='Published'?'status-badge status-good':status(a)==='Published Warning'?'status-badge status-warn':'status-badge status-bad'}>{status(a)}</span>{a.paraphraseStatus==='success'&&<span className="source-scope">Parafrase</span>}{a.translationStatus==='translated'&&<span className="source-scope">Terjemahan</span>}{a.generationProvider==='fallback'&&<span className="source-scope">Fallback</span>}{warning(a)&&<span className="source-scope">Warning</span>}</div></div><div className="article-meta">{a.todayViews??0} hari ini<br/>{a.totalViews??a.views??0} total</div></button>)}{!visible.length&&<div className="empty-state">Tidak ada artikel sesuai filter.</div>}</div></section><ArticleDetail article={selected}/></section>}
  {tab==='distribusi'&&<Distribution dashboard={dashboard} onCategory={v=>{setFilter('');navigate('berita');setQuery(v)}}/>} {tab==='penonton'&&<Audience analytics={analytics}/>} {tab==='ai'&&<AI dashboard={dashboard}/>} {tab==='system'&&<System dashboard={dashboard}/>} {tab==='notes'&&<Notes/>}
 </section></main>
}
function Automation({dashboard}){const a=dashboard?.automation||{};return <section className="admin-dashboard"><section className="pipeline-strip"><Metric label="Scheduler" value={a.scheduler||'Active'}/><Metric label="Worker" value={a.worker||'Healthy'}/><Metric label="Last Cycle" value={a.lastCycle?fmt(a.lastCycle):'-'}/><Metric label="Published" value={a.published??0}/><Metric label="Queue" value={a.queue??0}/><Metric label="Runtime" value={a.runtimeMs?`${(a.runtimeMs/1000).toFixed(1)} s`:'-'}/><Metric label="Image" value={a.image||'Source / Fallback'}/><Metric label="AI" value={a.provider||'Fallback'}/></section><section className="admin-panel"><div className="panel-head"><div><p className="admin-label">RECENT CYCLES</p><h2>Activity</h2></div><span className="source-scope">Raw technical detail collapsed</span></div><div className="cycle-list">{(dashboard?.cycles||[]).map((r,i)=><div key={r.cycleId||i}><span>{fmt(r.startedAt)}</span><strong>{r.status||'Completed'}</strong><span>{r.runtimeMs?`${(r.runtimeMs/1000).toFixed(1)}s`:'-'} · {r.processed||0} processed · {r.published||0} published · {r.warnings||0} warning · {r.rejected||0} rejected · {r.provider||'-'}</span><b>queue {r.queue??'-'}</b></div>)}{!(dashboard?.cycles||[]).length&&<div className="empty-state">Belum ada cycle telemetry.</div>}</div></section></section>}
function Metric({label,value}){return <div className="pipeline-metric"><span>{label}</span><strong>{value}</strong></div>}
function ArticleDetail({article}){if(!article)return <aside className="admin-panel article-detail-panel"><div className="empty-state">Pilih artikel untuk melihat detail.</div></aside>;const warnings=article.publishWarnings||[];return <aside className="admin-panel article-detail-panel"><div className="detail-status"><span className={status(article)==='Published'?'status-badge status-good':status(article)==='Published Warning'?'status-badge status-warn':'status-badge status-bad'}>{status(article)}</span><span>{fmt(article.publishedAt||article.sitePublishedAt)}</span><span>{article.category||'-'}</span></div><h2>{article.title}</h2><section className="detail-section"><h3>Catatan</h3>{warnings.length?<div className="warning-list">{warnings.map((w,i)=><p key={i}>⚠ {humanWarning(w)}</p>)}</div>:<p className="muted">Tidak ada warning.</p>}</section><section className="detail-section"><h3>Proses Artikel</h3><div className="detail-grid"><span>Parafrase</span><strong>{article.paraphraseStatus||'failed'}</strong><span>Terjemahan</span><strong>{article.translationStatus||'not_required'}</strong><span>Bahasa sumber</span><strong>{article.originalLanguage||article.language||'-'}</strong><span>Bahasa terbit</span><strong>{article.publishedLanguage||article.language||'-'}</strong><span>Provider final</span><strong>{article.generationProvider||'-'}</strong><span>Quality</span><strong>{article.qualityStatus||'good'}</strong><span>Indexability</span><strong>{article.indexabilityStatus|| (article.indexable===false?'Noindex':'Indexable')}</strong><span>Image</span><strong>{article.imageStatus||'unknown'}</strong></div></section><section className="detail-section"><h3>AI Flow</h3><div className="flow-list"><span>Gemini Primary</span><b>{article.geminiPrimaryResult||'-'}</b><span>Gemini Secondary</span><b>{article.geminiSecondaryResult||'-'}</b><span>Groq</span><b>{article.groqResult||'-'}</b><span>Fallback</span><b>{article.generationProvider==='fallback'?'Used':'Not used'}</b></div></section><details className="technical"><summary>Detail Teknis</summary><pre>{JSON.stringify({id:article.id,cycleId:article.cycleId,runtimeSha:article.runtimeSha,publishDecisionReason:article.publishDecisionReason,publishWarnings:article.publishWarnings,sourceUrl:article.url},null,2)}</pre></details></aside>}
function humanWarning(v){return ({missing_image:'Gambar sumber tidak tersedia.',invalid_image:'Gambar sumber tidak valid.',image_fallback_used:'Menggunakan gambar default.',gemini_primary_failed:'Gemini Primary gagal memproses artikel.',gemini_secondary_failed:'Gemini Secondary gagal memproses artikel.',groq_failed:'Groq gagal memproses artikel.',translation_failed:'Terjemahan otomatis tidak berhasil.',published_original_language:'Artikel diterbitkan dalam bahasa sumber.',fallback_used:'Artikel diterbitkan menggunakan fallback.'}[v]||v)}
function Distribution({dashboard}){return <section className="admin-grid"><section className="admin-panel"><p className="admin-label">KATEGORI</p><h2>Distribusi Kategori</h2><div className="bar-list">{(dashboard?.categories||[]).map(x=><div key={x.name}><div><span>{x.name}</span><b>{x.count} · {x.percent}%</b></div><div className="source-bar"><i style={{width:`${Math.min(100,x.percent)}%`}}/></div><small>{x.today} hari ini · terakhir {fmt(x.lastPublished)}</small></div>)}</div></section><section className="admin-panel"><p className="admin-label">SUMBER</p><h2>Kesehatan Publisher</h2><div className="source-list">{(dashboard?.sources||[]).map(x=><div className="source-row" key={x.publisher}><div className="source-row-head"><span>{x.publisher}</span><strong>{x.status}</strong><b>{x.count}</b></div><div className="source-bar"><i style={{width:`${Math.min(100,x.imageCoverage||0)}%`}}/></div><small>today {x.today} · image {x.imageCoverage}% · last {fmt(x.lastPublished)}</small></div>)}</div></section></section>}
function Audience({analytics}){return <section className="admin-grid"><section className="admin-panel"><p className="admin-label">PENONTON</p><h2>Audience Analytics</h2><div className="analytics-metrics"><Metric label="Total Penayangan" value={analytics?.totalViews??0}/><Metric label="Penayangan Hari Ini" value={analytics?.todayViews??0}/></div><h3>Terpopuler Hari Ini</h3><div className="popular-admin">{(analytics?.topToday||[]).map((a,i)=><div key={a.id}><b>{i+1}</b><span>{a.title}</span><strong>{a.views}</strong></div>)}{!(analytics?.topToday||[]).length&&<p className="muted">Belum ada data penayangan hari ini.</p>}</div></section><section className="admin-panel"><h3>Terpopuler Sepanjang Waktu</h3><div className="popular-admin">{(analytics?.topLifetime||[]).map((a,i)=><div key={a.id}><b>{i+1}</b><span>{a.title}</span><strong>{a.views}</strong></div>)}</div><h3>Distribusi Kategori</h3><div className="bar-list">{(analytics?.topCategories||[]).map(x=><div key={x.name}><div><span>{x.name}</span><b>{x.views}</b></div></div>)}</div></section></section>}
function AI({dashboard}){return <section className="admin-grid"><section className="admin-panel"><p className="admin-label">AI &amp; PROCESSING</p><h2>Provider Chain</h2><div className="provider-list">{(dashboard?.providers||[]).map(p=><div className="provider-card" key={p.name}><div><strong>{p.label}</strong><span>Configured: {p.configured?'YES':'NO'}</span></div><code>{p.model||'-'}</code></div>)}</div></section><section className="admin-panel"><h3>Last Processing</h3><div className="summary-list"><div><dt>AI Success</dt><dd>{dashboard?.ai?.success??0}</dd></div><div><dt>Fallback Used</dt><dd>{dashboard?.ai?.fallback??0}</dd></div><div><dt>Translation Failed</dt><dd>{dashboard?.ai?.translationFailed??0}</dd></div><div><dt>Paraphrase Failed</dt><dd>{dashboard?.ai?.paraphraseFailed??0}</dd></div></div></section></section>}
function System({dashboard}){return <section className="admin-grid"><section className="admin-panel"><p className="admin-label">SYSTEM</p><h2>Runtime</h2><div className="summary-list"><div><dt>Feature HEAD</dt><dd>{dashboard?.system?.featureHead||'-'}</dd></div><div><dt>Production SHA</dt><dd>{dashboard?.system?.productionSha||'-'}</dd></div><div><dt>Runtime SHA</dt><dd>{dashboard?.system?.runtimeSha||'-'}</dd></div><div><dt>Vercel</dt><dd>{dashboard?.system?.vercelState||'-'}</dd></div><div><dt>CI</dt><dd>{dashboard?.system?.ci||'-'}</dd></div></div></section><section className="admin-panel"><h2>Scheduler</h2><div className="summary-list"><div><dt>Primary</dt><dd>QStash / configured publication trigger</dd></div><div><dt>Fallback</dt><dd>GitHub Actions 7,22,37,52 UTC</dd></div><div><dt>Deferred Vercel</dt><dd>17 0,6,12,18 UTC</dd></div></div></section></section>}
function Notes(){return <section className="admin-panel"><p className="admin-label">CATATAN &amp; PERBAIKAN</p><h2>Open · Monitoring · Resolved</h2><p className="muted">Gunakan area Catatan &amp; Perbaikan untuk pekerjaan dan known issues. Raw worker log tidak ditampilkan di dashboard utama.</p></section>}
