import {auth,signIn,signOut} from '../../auth.js';
import {readArticles} from '../../lib/storage.js';
import AdminWorkspace from './AdminWorkspace.jsx';
import SearchIntentPanel from './SearchIntentPanel.jsx';
import AdminNotesPanel from '../../components/admin/AdminNotesPanel.jsx';
import './admin.css';
import './admin-overrides.css';
import './admin-actions.css';
import './notes-panel.css';
import './search-intent.css';
export const dynamic='force-dynamic';
export const metadata={title:'Admin Console | Berita Auto',robots:{index:false,follow:false,noarchive:true}};
export default async function AdminPage({searchParams}){let session=null;let authConfigured=true;try{session=await auth()}catch{authConfigured=false}const configured=Boolean(process.env.GOOGLE_CLIENT_ID&&process.env.GOOGLE_CLIENT_SECRET&&process.env.AUTH_SECRET&&(process.env.ADMIN_EMAILS||'').trim());if(!authConfigured||!configured)return <main className="admin-shell admin-login"><section className="login-card"><span className="admin-kicker">BERITA AUTO</span><p className="admin-label">ADMIN CONSOLE</p><h1>Admin authentication belum dikonfigurasi.</h1><p>Hubungi administrator project untuk melengkapi konfigurasi Google OAuth.</p></section></main>;if(!session?.user){const error=searchParams?.error==='AccessDenied';return <main className="admin-shell admin-login"><section className="login-card"><span className="admin-kicker">BERITA AUTO</span><p className="admin-label">ADMIN CONSOLE</p><h1>Masuk ke Admin</h1><p>Gunakan akun Google administrator untuk melanjutkan.</p>{error&&<div className="admin-error">Akun ini tidak memiliki akses administrator.</div>}<form action={async()=>{'use server';await signIn('google',{redirectTo:'/admin-berita'})}}><button className="google-button" type="submit">Masuk dengan Google</button></form></section></main>};const allowed=(process.env.ADMIN_EMAILS||'').split(',').map(v=>v.trim().toLowerCase()).filter(Boolean);const email=session.user.email?.trim().toLowerCase();if(!email||!allowed.includes(email))return <main className="admin-shell admin-login"><section className="login-card"><span className="admin-kicker">BERITA AUTO</span><p className="admin-label">ADMIN CONSOLE</p><h1>Akun ini tidak memiliki akses administrator.</h1><form action={async()=>{'use server';await signOut({redirectTo:'/admin-berita'})}}><button className="ghost-button" type="submit">Keluar</button></form></section></main>;const items=await readArticles();const initialArticles=items.map(a=>({...a,content:undefined,summary:undefined,excerpt:undefined}));const initialTab=String(searchParams?.tab||'automation').toLowerCase();const initialArticle=initialArticles.find(a=>String(a.id)===String(searchParams?.article||''))||null;const normalizedTab=['automation','berita','distribusi','penonton','ai','system','notes'].includes(initialTab)?initialTab:'automation';return <div className="admin-workspace-shell"><div className="admin-ads-shortcut"><a href="/admin-instagram" aria-label="Instagram Automation">◎ <span>Instagram</span></a><a href="/admin-berita/iklan" aria-label="Kelola Iklan">▣ <span>Kelola Iklan</span></a></div>{normalizedTab==='berita'&&<SearchIntentPanel articles={initialArticles}/>}<AdminWorkspace initialArticles={initialArticles} initialTab={normalizedTab} initialArticle={initialArticle} email={email}/><AdminNotesPanel/></div>}
