import {auth,signIn,signOut} from '../../auth.js';
import InstagramDashboard from './InstagramDashboard.jsx';
import {getAdminInstagramStatus} from '../../lib/admin-instagram.js';
import {getInstagramReviewSnapshot} from '../../lib/instagram-review.js';
import './admin-instagram.css';
export const dynamic='force-dynamic';
export const metadata={title:'Instagram Review | Berita Auto',robots:{index:false,follow:false,noarchive:true}};
export default async function AdminInstagramPage(){let session=null;let authConfigured=true;try{session=await auth()}catch{authConfigured=false}const configured=Boolean(process.env.GOOGLE_CLIENT_ID&&process.env.GOOGLE_CLIENT_SECRET&&process.env.AUTH_SECRET&&(process.env.ADMIN_EMAILS||'').trim());if(!authConfigured||!configured)return <main className="ig-shell"><section className="ig-panel"><span className="ig-kicker">BERITA AUTO</span><h1>Admin authentication belum dikonfigurasi.</h1><p>Hubungi administrator project untuk melengkapi konfigurasi Google OAuth.</p></section></main>;if(!session?.user)return <main className="ig-shell"><section className="ig-panel"><span className="ig-kicker">BERITA AUTO</span><h1>Masuk ke Instagram Review</h1><p>Gunakan akun Google administrator untuk melanjutkan.</p><form action={async()=>{'use server';await signIn('google',{redirectTo:'/admin-instagram'})}}><div className="ig-actions"><button type="submit">Masuk dengan Google</button><a href="/admin-berita">Kembali</a></div></form></section></main>;const allowed=(process.env.ADMIN_EMAILS||'').split(',').map(v=>v.trim().toLowerCase()).filter(Boolean);const email=session.user.email?.trim().toLowerCase();if(!email||!allowed.includes(email))return <main className="ig-shell"><section className="ig-panel"><span className="ig-kicker">BERITA AUTO</span><h1>Akun ini tidak memiliki akses administrator.</h1><form action={async()=>{'use server';await signOut({redirectTo:'/admin-berita'})}}><button type="submit">Keluar</button></form></section></main>;
let status={};let review={mode:'review',prepareIntervalMinutes:1,readyQueueTarget:null,preparationBatchSize:3,items:[],ready:[],counts:{ready:0,preparing:0,failed:0,posted:0,removed:0},lastPreparation:null,refreshedAt:new Date().toISOString()};let reviewError=null;try{[status,review]=await Promise.all([getAdminInstagramStatus(),getInstagramReviewSnapshot()]);}catch(error){reviewError=String(error?.message||error).slice(0,240);try{status=await getAdminInstagramStatus();}catch(statusError){status={overview:{status:'ERROR',message:'Status Instagram sementara tidak dapat dimuat.'},posts:[],news:{},metaPublishing:{effectiveState:'UNKNOWN'}};}}
return <><InstagramDashboard initial={{...status,review}}/>{reviewError?<div className="ig-panel" style={{maxWidth:'1180px',margin:'0 auto 24px'}}><strong>⚠️ Data antrean Instagram sementara gagal dimuat.</strong><p>Silakan tekan Refresh. Detail teknis: <code>{reviewError}</code></p><a href="/admin-instagram?view=ready">Refresh</a></div>:null}</>}
