import {fetchSourceMaterial} from '../worker/source-material.js';
import {cleanExcerpt} from './text.js';
import {getProviderRegistry,DEFAULT_GEMINI_MODEL,DEFAULT_OPENAI_MODEL,AI_TIMEOUT_MS} from './ai-providers.js';

function cleanText(value=''){return String(value).replace(/```(?:json)?/gi,'').replace(/```/g,'').replace(/\.{3,}/g,'').replace(/^[\s]*(?:berikut(?: adalah)?|ini(?: adalah)?)[\s,:-]*/i,'').replace(/[ \t]+\n/g,'\n').trim()}
function parseJsonText(value=''){const cleaned=cleanText(value);if(!cleaned)return null;try{return JSON.parse(cleaned)}catch{}const start=cleaned.indexOf('{');const end=cleaned.lastIndexOf('}');if(start>=0&&end>start){try{return JSON.parse(cleaned.slice(start,end+1))}catch{}}return null}
function paragraphList(value=''){return String(value).split(/\n{2,}/).map(x=>cleanText(x)).filter(x=>x.length>=40)}
function normalized(value=''){return cleanText(value).toLowerCase().replace(/\s+/g,' ')}
function validateOutput(output,material=''){const title=cleanText(output?.title||''),excerpt=cleanText(output?.excerpt||''),content=cleanText(output?.content||''),sourceText=String(material||'').trim(),paragraphs=paragraphList(content);const minParagraphs=sourceText.length>=1600?5:sourceText.length>=700?3:2;const minLength=Math.max(320,Math.min(1800,sourceText.length*.25));if(!title||!excerpt||!content)throw new Error('invalid_response');if(content.length<minLength)throw new Error('content_too_short');if(paragraphs.length<minParagraphs)throw new Error('insufficient_paragraphs');if(/\.{3,}|\bplaceholder\b|\[insert\]|<PLACEHOLDER>/i.test(`${title}\n${excerpt}\n${content}`))throw new Error('invalid_response');if(normalized(sourceText)&&normalized(content)===normalized(sourceText))throw new Error('copied_source_material');return{title,excerpt,content}}
function fallback(item,material=''){const body=[];const summary=cleanText(item.summary||item.title||'');const sourceParagraphs=paragraphList(material).slice(0,8);if(summary&&summary.length>=40)body.push(summary);for(const p of sourceParagraphs)if(!body.some(x=>normalized(x)===normalized(p)))body.push(p);if(!body.length)body.push(cleanText(item.title||'Berita terbaru'));body.push(`Sumber: ${item.sourceName||'sumber publik'}${item.url?` — ${item.url}`:''}`);return{title:cleanText(item.title||'Berita terbaru'),excerpt:cleanExcerpt(item.summary||item.title||''),content:body.join('\n\n'),generationProvider:'fallback',generationModel:null,generationAt:new Date().toISOString()}}
function providerError(error){const message=String(error?.message||error||'unknown');if(message==='429'||/rate[_ -]?limited|quota/i.test(message))return'rate_limited';if(error?.name==='AbortError'||/timeout|aborted/i.test(message))return'timeout';if(/5\d\d/.test(message)||/server_error/i.test(message))return'server_error';if(/invalid_response|content_too_short|insufficient_paragraphs|copied_source_material/i.test(message))return'invalid_response';if(/401|403|auth/i.test(message))return'auth';return'unknown'}
function buildPrompt(item,material=''){return`Anda adalah editor newsroom Berita Auto. Tulis ulang bahan berita berikut menjadi artikel Bahasa Indonesia yang orisinal, natural, profesional, dan faktual. Bahan hanya boleh dipakai sebagai sumber fakta. Ubah lead, struktur kalimat, pilihan kata, dan alur paragraf; jangan sekadar mengganti sinonim. Target 5-8 paragraf bila bahan mencukupi.\n\nJangan menambah fakta yang tidak tersedia. Jangan membuat kutipan langsung, narasumber, reporter, wawancara, saksi mata, lokasi liputan, statistik, angka keuangan, penelitian, jurnal, pernyataan pemerintah, atau kronologi baru. Jangan menulis seolah reporter Berita Auto berada di lokasi atau mewawancarai siapa pun. Kutipan langsung hanya boleh dipakai bila benar-benar ada di bahan sumber; jika ragu, parafrase. Jangan gunakan ellipsis tiga titik. Jangan clickbait. Pertahankan atribusi sumber.\n\nKembalikan JSON terstruktur dengan field title, excerpt, content. Field content berisi paragraf lengkap dipisahkan oleh dua newline. Jangan mengembalikan markdown fence, pengantar, komentar, atau field tambahan.\n\nJudul sumber: ${item.title||''}\nRingkasan RSS: ${item.summary||''}\nNama sumber: ${item.sourceName||''}\nURL sumber: ${item.url||''}\nBahan faktual:\n${material||item.summary||item.title||''}`}
async function requestWithTimeout(url,options){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),AI_TIMEOUT_MS);try{return await fetch(url,{...options,signal:controller.signal})}finally{clearTimeout(timer)}}
export function getAIProviderConfig(){return{primary:'gemini',providers:getProviderRegistry({buildPrompt,parseJsonText,validateOutput,requestWithTimeout}).map(p=>({name:p.name,configured:p.isConfigured(),model:p.modelName,timeoutMs:p.timeoutMs})),fallback:'factual'}}
export async function generateArticle(item,materialArg=''){const material=materialArg||await fetchSourceMaterial(item);const providers=getProviderRegistry({buildPrompt,parseJsonText,validateOutput,requestWithTimeout});for(const provider of providers){if(!provider.isConfigured()){console.log(`[ai] provider=${provider.name} status=not_configured`);continue}try{const started=Date.now();const result=await provider.generate(item,material);console.log(`[ai] provider=${provider.name} status=success model=${result.generationModel} durationMs=${Date.now()-started}`);return result}catch(error){console.warn(`[ai] provider=${provider.name} status=${providerError(error)}`)}}console.warn('[ai] provider=fallback status=used');return fallback(item,material)}
