import {put} from '@vercel/blob';
import {ARTICLE_CONFIG} from './article-config.js';

const SITE='https://berita-auto.vercel.app';
const TIMEOUT_MS=30000;
const IMAGE_TEMPLATE_VERSION=ARTICLE_CONFIG.image.templateVersion||2;

function imageConfig(){return ARTICLE_CONFIG.image}
function clean(v){return String(v||'').replace(/\s+/g,' ').trim()}
function escapeXml(v){return String(v||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;')}
function safeCode(value,fallback='image_generation_failed'){return String(value||fallback).toLowerCase().replace(/[^a-z0-9_:-]/g,'_').slice(0,100)}
function hostOf(url=''){try{return new URL(url).hostname.toLowerCase()}catch{return ''}}

function wordWidth(word,fontSize){let width=0;for(const ch of String(word||'')){if(/\s/.test(ch))width+=.30;else if(/[MW@%&]/.test(ch))width+=.86;else if(/[ilIjtfr]/.test(ch))width+=.30;else if(/[.,:;!|'`]/.test(ch))width+=.28;else if(/[A-Z]/.test(ch))width+=.68;else width+=.56}return width*fontSize}
function lineWidth(line,fontSize){return String(line||'').split(/\s+/).filter(Boolean).reduce((sum,word,index)=>sum+wordWidth(word,fontSize)+(index?fontSize*.30:0),0)}
function wrapLayout(text,{maxWidth=920,maxLines=3,fontSize=46,ellipsis=true}={}){const words=clean(text).split(/\s+/).filter(Boolean);if(!words.length)return{lines:[],overflowed:false,truncated:false};const lines=[];let current='';for(const word of words){const candidate=current?`${current} ${word}`:word;if(current&&lineWidth(candidate,fontSize)>maxWidth){lines.push(current);current=word}else current=candidate}if(current)lines.push(current);if(lines.length<=maxLines&&lines.every(line=>lineWidth(line,fontSize)<=maxWidth))return{lines,overflowed:false,truncated:false};const kept=lines.slice(0,maxLines);const omitted=lines.slice(maxLines).flatMap(line=>line.split(/\s+/).filter(Boolean));let last=kept[maxLines-1]||'';if(omitted.length){for(const word of omitted){const candidate=last?`${last} ${word}`:word;if(lineWidth(`${candidate}…`,fontSize)<=maxWidth)last=candidate;else break}if(ellipsis){const candidate=`${last}…`;if(lineWidth(candidate,fontSize)<=maxWidth)last=candidate;else{const parts=last.split(/\s+/).filter(Boolean);while(parts.length&&lineWidth(`${parts.join(' ')}…`,fontSize)>maxWidth)parts.pop();last=parts.length?`${parts.join(' ')}…`:''}}kept[maxLines-1]=last}return{lines:kept.filter(Boolean),overflowed:true,truncated:true}}
export function wrapTextByWords(text,options={}){return wrapLayout(text,options).lines}
export function titleLines(title,baseSize=46){const maxWidth=920,maxLines=3;for(const fontSize of [baseSize,42,38,35,32]){const result=wrapLayout(title,{maxWidth,maxLines,fontSize,ellipsis:false});if(!result.overflowed&&result.lines.length<=maxLines)return{fontSize,lines:result.lines,overflowed:false,truncated:false}}const final=wrapLayout(title,{maxWidth,maxLines,fontSize:32,ellipsis:true});return{fontSize:32,lines:final.lines,overflowed:final.overflowed,truncated:final.truncated}}

export function buildArticleImagePrompt(article={}){return `Create a professional editorial illustration for an Indonesian evergreen article published by Berita Auto. Subject: ${clean(article.title||article.topic)}. Search intent: ${clean(article.primaryQuery)}. Category: ${clean(article.category||'General')}. Entities: ${clean((article.entities||article.entityNames||[]).join(', '))}. Use a realistic, informative visual scene without logos, copyrighted characters, readable text, watermarks, or fabricated product specifications. Make the subject immediately understandable, visually clean, trustworthy, modern newsroom style, natural lighting, wide composition, 16:9.`}

function visualQuery(article={}){const title=clean(article.title||article.topic);const query=clean(article.primaryQuery);const category=clean(article.category);const entities=clean((article.entities||article.entityNames||[]).join(' '));const text=`${title} ${query} ${category} ${entities}`;let subject=text;if(/listrik|energi|hemat/i.test(text))subject='home electricity energy saving energy efficient home appliances';else if(/mesin|motor|karburator|aki|oli|rem|speedometer|banjir/i.test(text))subject=/panas|overheat/i.test(text)?'motorcycle engine cooling motorcycle engine maintenance':`motorcycle ${title.replace(/[^a-zA-Z0-9 ]/g,' ')} motorcycle maintenance`;else if(/baterai|ponsel|smartphone/i.test(text))subject='smartphone battery technology battery care';return clean(`${subject} ${query} ${category} ${entities}`).slice(0,240)}

async function request(url,options={}){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),TIMEOUT_MS);try{return await fetch(url,{...options,signal:controller.signal,cache:'no-store',headers:{'user-agent':'BeritaAuto/1.0 image-pipeline',...(options.headers||{})}})}catch(error){if(error?.name==='AbortError')throw new Error('image_request_timeout');throw error}finally{clearTimeout(timer)}}

async function generateGemini(prompt,config){const key=String(process.env.GEMINI_API_KEY||'').trim();if(!key)throw new Error('gemini_api_key_missing');const response=await request('https://generativelanguage.googleapis.com/v1beta/interactions',{method:'POST',headers:{'x-goog-api-key':key,'content-type':'application/json',accept:'application/json'},body:JSON.stringify({model:config.model,input:prompt,response_format:{type:'image',mime_type:'image/jpeg',aspect_ratio:config.aspectRatio,image_size:'1K'}})});const payload=await response.json().catch(()=>null);if(!response.ok)throw new Error(`gemini_image_http_${response.status}`);const data=payload?.output_image?.data||payload?.steps?.flatMap(step=>Array.isArray(step?.content)?step.content:[]).find(block=>block?.type==='image')?.data;if(!data)throw new Error(payload?.status==='failed'?'gemini_image_failed':'gemini_image_missing');return{buffer:Buffer.from(data,'base64'),mimeType:'image/jpeg'}}

const LICENSE_RE=/^(public domain|cc0|cc by(?:-sa)?(?:\s|$)|cc-by(?:-sa)?(?:\s|$))/i;
function normalizeLicense(value=''){return clean(String(value).replace(/<[^>]+>/g,' '))}
function licenseAllowed(value=''){const license=normalizeLicense(value);return Boolean(license&&LICENSE_RE.test(license))}
function tokenScore(query,haystack){const tokens=clean(query).toLowerCase().split(/[^a-z0-9]+/).filter(t=>t.length>=4);if(!tokens.length)return 0;const text=clean(haystack).toLowerCase();return tokens.reduce((score,t)=>score+(text.includes(t)?1:0),0)/tokens.length}
function candidateIsSafe(title,info,meta,license){const hay=`${title} ${meta.ObjectName?.value||''} ${meta.ImageDescription?.value||''} ${meta.Categories?.value||''}`;return Boolean(info?.url&&String(info.mime||'').startsWith('image/')&&Number(info.width||0)>=1000&&Number(info.height||0)>=500&&!/logo|avatar|icon|tracking|pixel|screenshot|advert|banner|watermark/i.test(hay)&&licenseAllowed(license))}

async function searchWikimedia(article={}){const query=visualQuery(article);if(!query)throw new Error('open_license_no_query');const url=`https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrsearch=${encodeURIComponent(query)}&gsrnamespace=6&gsrlimit=15&prop=imageinfo&iiprop=url|mime|size|extmetadata&iiurlwidth=1200&format=json&origin=*`;const response=await request(url,{headers:{accept:'application/json'}});if(!response.ok)throw new Error(`wikimedia_http_${response.status}`);const payload=await response.json().catch(()=>null);const pages=Object.values(payload?.query?.pages||{});const ranked=pages.map(page=>{const info=page?.imageinfo?.[0];const meta=info?.extmetadata||{};const license=normalizeLicense(meta.LicenseShortName?.value||meta.License?.value||'');return{page,info,meta,license,score:tokenScore(query,`${page?.title||''} ${meta.ObjectName?.value||''} ${meta.ImageDescription?.value||''}`)}}).filter(x=>candidateIsSafe(x.page?.title||'',x.info,x.meta,x.license)).sort((a,b)=>b.score-a.score);const best=ranked[0];if(!best)throw new Error('wikimedia_no_licensed_relevant_image');const author=normalizeLicense(best.meta.Artist?.value||best.meta.Credit?.value||'Wikimedia Commons contributor');return{url:best.info.thumburl||best.info.url,originalUrl:best.info.url,mimeType:best.info.mime,license:best.license,author,attributionUrl:`https://commons.wikimedia.org/wiki/${encodeURIComponent(String(best.page.title||'').replace(/ /g,'_'))}`,provider:'Wikimedia Commons',query,score:best.score}}

async function searchOpenverse(article={}){const query=visualQuery(article);if(!query)throw new Error('open_license_no_query');const url=`https://api.openverse.org/v1/images/?q=${encodeURIComponent(query)}&page_size=20&license_type=commercial`;const response=await request(url,{headers:{accept:'application/json'}});if(!response.ok)throw new Error(`openverse_http_${response.status}`);const payload=await response.json().catch(()=>null);const results=Array.isArray(payload?.results)?payload.results:[];const ranked=results.map(item=>{const license=normalizeLicense(item.license||item.license_name||'');const hay=`${item.title||''} ${item.creator||''} ${item.tags?.map?.(t=>typeof t==='string'?t:t?.name||'').join(' ')||''}`;return{item,license,score:tokenScore(query,hay)}}).filter(x=>licenseAllowed(x.license)&&x.item?.url&&String(x.item?.mime_type||'').startsWith('image/')&&Number(x.item?.width||0)>=1000&&Number(x.item?.height||0)>=500&&!/logo|avatar|icon|tracking|pixel|screenshot|advert|banner|watermark/i.test(`${x.item.title||''} ${x.item.description||''}`)).sort((a,b)=>b.score-a.score);const best=ranked[0];if(!best)throw new Error('openverse_no_licensed_relevant_image');const item=best.item;return{url:item.url,originalUrl:item.foreign_landing_url||item.url,mimeType:item.mime_type,license:best.license,author:normalizeLicense(item.creator||'Unknown creator'),attributionUrl:item.foreign_landing_url||item.url,provider:'Openverse',query,score:best.score}}

async function findOpenLicenseImage(article={}){let firstError=null;try{return await searchWikimedia(article)}catch(error){firstError=error}try{return await searchOpenverse(article)}catch(error){throw new Error(firstError?.message||error?.message||'open_license_unavailable')}}

async function downloadExternalImage(candidate){const response=await request(candidate.url,{headers:{accept:'image/avif,image/webp,image/jpeg,image/png;q=0.9,*/*;q=0.5'}});if(!response.ok)throw new Error(`open_license_image_http_${response.status}`);const type=String(response.headers.get('content-type')||candidate.mimeType||'').split(';')[0].toLowerCase();if(!type.startsWith('image/'))throw new Error('open_license_not_image');const length=Number(response.headers.get('content-length')||0);if(length>0&&length<20000)throw new Error('open_license_image_too_small');const array=await response.arrayBuffer();if(array.byteLength<20000)throw new Error('open_license_image_too_small');return{buffer:Buffer.from(array),mimeType:type}}

function researchLicenseAllowed(source={}){return licenseAllowed(source.license||source.licenseName||source.imageLicense||'')}
async function findResearchImage(article={}){for(const source of Array.isArray(article.sources)?article.sources:[]){const candidate=source?.imageUrl||source?.image?.url||source?.thumbnailUrl||'';if(!candidate||hostOf(candidate).includes('google')||!researchLicenseAllowed(source))continue;try{const downloaded=await downloadExternalImage({url:candidate,mimeType:source?.mimeType});return{...downloaded,sourceType:'research_source',provider:source.publisher||source.name||hostOf(candidate),originalUrl:candidate,license:normalizeLicense(source.license||source.licenseName||source.imageLicense),author:source.author||'',attributionUrl:source.attributionUrl||source.canonicalUrl||source.resolvedUrl||source.url||candidate}}catch{}}throw new Error('research_image_unavailable')}

export function fallbackSvg(article={},config){const title=clean(article.title||'Artikel Berita Auto');const topic=clean(article.category||'Panduan & Pengetahuan');const {fontSize,lines}=titleLines(title,46);const tspans=lines.map((line,i)=>`<tspan x="90" dy="${i===0?0:Math.round(fontSize*1.28)}">${escapeXml(line)}</tspan>`).join('');return Buffer.from(`<?xml version="1.0" encoding="UTF-8"?><svg xmlns="http://www.w3.org/2000/svg" width="${config.width}" height="${config.height}" viewBox="0 0 ${config.width} ${config.height}"><rect width="100%" height="100%" fill="#101827"/><circle cx="1030" cy="105" r="260" fill="#26354f"/><circle cx="1120" cy="590" r="175" fill="#172338"/><path d="M0 560 C250 500 420 650 720 555 S1050 500 1200 560 V675 H0Z" fill="#15233a"/><rect x="90" y="82" width="180" height="9" rx="5" fill="#ffffff" opacity=".7"/><text x="90" y="150" font-family="Arial,sans-serif" font-size="27" font-weight="700" fill="#ffffff">BERITA AUTO</text><text x="90" y="225" font-family="Arial,sans-serif" font-size="20" fill="#b8c7dc">${escapeXml(topic)}</text><text x="90" y="315" font-family="Arial,sans-serif" font-size="${fontSize}" font-weight="700" fill="#ffffff">${tspans}</text><text x="90" y="610" font-family="Arial,sans-serif" font-size="18" fill="#b8c7dc">Ilustrasi Berita Auto</text></svg>`,'utf8')}

async function persistImage(buffer,article,config,mimeType='image/jpeg'){if(config.storage!=='blob')throw new Error('unsupported_article_image_storage');if(!String(process.env.BLOB_READ_WRITE_TOKEN||'').trim())throw new Error('blob_token_missing');const slug=clean(article.slug||article.title).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80)||'artikel';const extension=mimeType==='image/svg+xml'?'svg':mimeType==='image/png'?'png':'jpg';const version=Date.now();let blob;try{blob=await put(`articles/${slug}-v${IMAGE_TEMPLATE_VERSION}-${version}.${extension}`,buffer,{access:'public',contentType:mimeType,addRandomSuffix:true})}catch(error){throw new Error('blob_upload_failed')}if(!blob?.url)throw new Error('blob_url_missing');try{const check=await request(blob.url,{method:'HEAD'});const type=String(check.headers.get('content-type')||'');if(!check.ok)throw new Error('blob_url_unreachable');if(!type.startsWith('image/'))throw new Error('blob_content_type_invalid')}catch(error){if(String(error?.message||'').startsWith('blob_'))throw error;throw new Error('blob_url_validation_failed')}return{url:blob.url,version}}

export async function generateAndPersistArticleImage(article={}){const config=imageConfig();if(!config.enabled)return{status:'disabled',imageStatus:'disabled',imageUrl:null,config};const generatedAt=new Date().toISOString();let generated=null,sourceType='',model='none',aiGenerationStatus='not_attempted',fallbackStatus='not_attempted',persistenceStatus='failed',imageErrorCode=null,sourceMeta={};
 try{const internet=await findOpenLicenseImage(article);generated=await downloadExternalImage(internet);sourceType='open_license';sourceMeta=internet;fallbackStatus='open_license_success'}catch(error){fallbackStatus='open_license_failed';imageErrorCode=safeCode(error?.message,'open_license_failed')}
 if(!generated&&config.provider==='gemini'){try{generated=await generateGemini(buildArticleImagePrompt(article),config);sourceType='ai_generated';model=config.model;aiGenerationStatus='success';fallbackStatus=fallbackStatus==='not_attempted'?'ai_success':`${fallbackStatus}|ai_success`}catch(error){aiGenerationStatus='failed';fallbackStatus=`${fallbackStatus}|ai_failed`;imageErrorCode=imageErrorCode||safeCode(error?.message,'gemini_image_failed')}}
 if(!generated){try{const research=await findResearchImage(article);generated=research;sourceType='research_source';sourceMeta=research;fallbackStatus=`${fallbackStatus}|research_success`}catch(error){fallbackStatus=`${fallbackStatus}|research_failed`;imageErrorCode=imageErrorCode||safeCode(error?.message,'research_image_unavailable')}}
 if(!generated){try{generated={buffer:fallbackSvg(article,config),mimeType:'image/svg+xml'};sourceType='branded_fallback';fallbackStatus=`${fallbackStatus}|branded_success`}catch(error){fallbackStatus=`${fallbackStatus}|branded_failed`;imageErrorCode=imageErrorCode||'branded_fallback_failed'}}
 if(!generated)throw Object.assign(new Error(imageErrorCode||'image_generation_failed'),{imageErrorCode:imageErrorCode||'image_generation_failed',aiGenerationStatus,fallbackStatus,persistenceStatus});
 let persisted;try{persisted=await persistImage(generated.buffer,article,config,generated.mimeType);persistenceStatus='success'}catch(error){persistenceStatus='failed';imageErrorCode=imageErrorCode||safeCode(error?.message,'blob_upload_failed');throw Object.assign(new Error(imageErrorCode),{imageErrorCode,aiGenerationStatus,fallbackStatus,persistenceStatus})}
 const caption=sourceType==='ai_generated'&&config.disclosure?'Ilustrasi AI — Berita Auto':sourceType==='open_license'?`Foto: ${sourceMeta.author||'Author'} / ${sourceMeta.provider||'Open License'}`:sourceType==='research_source'?`Foto/Ilustrasi: ${sourceMeta.author?`${sourceMeta.author} / `:''}${sourceMeta.provider||'sumber referensi'}`:'Ilustrasi Berita Auto';
 const alt=clean(article.title||article.primaryQuery||'Ilustrasi artikel Berita Auto');
 return{status:'ready',imageStatus:'ready',imageUrl:persisted.url,imageAlt:alt,imageCaption:caption,imageSourceType:sourceType,imageSourceProvider:sourceMeta.provider||null,imageOriginalUrl:sourceMeta.originalUrl||null,imageLicense:sourceMeta.license||null,imageAuthor:sourceMeta.author||null,imageAttributionUrl:sourceMeta.attributionUrl||null,imageModel:model,imageGeneratedAt:generatedAt,imageGenerationAttemptAt:generatedAt,imageVersion:persisted.version,imageTemplateVersion:IMAGE_TEMPLATE_VERSION,imageErrorCode:null,aiGenerationStatus,fallbackStatus,persistenceStatus,lastImageAttemptStatus:'success',lastImageErrorCode:null,site:SITE};
}

export {imageConfig,safeCode,visualQuery,licenseAllowed};
