import {evaluateSearchOpportunity} from './search-intent.js';
import {listAllArticles,findDuplicateArticle} from './article-storage.js';
import {readSearchAnalytics} from './search-data.js';
const TYPE_RULES=[['HOW_TO',/\b(cara|bagaimana|langkah|menyetel|memilih|mengecek|membaca|mengatur|menggunakan|menghemat)\b/i],['TROUBLESHOOTING',/\b(penyebab|kenapa|brebet|mati|rusak|soak|tidak stabil|overheat|bermasalah|kesalahan)\b/i],['COMPARISON',/\b(perbedaan|vs|dibandingkan|bagus mana|lebih baik)\b/i],['FAQ',/\b(apa itu|apakah|faq|pertanyaan)\b/i],['CHECKLIST',/\b(tanda-tanda|cek|daftar|checklist)\b/i],['MAINTENANCE',/\b(perawatan|merawat|servis|maintenance)\b/i],['EXPLAINER',/\b(mengapa|fungsi|penjelasan|arti)\b/i]];
const EVERGREEN_FALLBACK=[['Cara menyetel karburator motor agar langsam stabil','Automotive'],['Penyebab motor brebet saat digas dan cara mengeceknya','Automotive'],['Cara membaca warna busi motor','Automotive'],['Penyebab speedometer motor mati','Automotive'],['Cara mengecek aki motor mulai soak','Automotive'],['Cara memilih oli motor yang tepat','Automotive'],['Tanda-tanda kampas rem harus diganti','Automotive'],['Penyebab mesin motor cepat panas','Automotive'],['Cara merawat motor setelah terendam banjir','Automotive'],['Perbedaan motor injeksi dan karburator','Automotive'],['Cara merawat baterai ponsel agar lebih awet','Technology'],['Cara menghemat listrik rumah tanpa mengurangi kenyamanan','Public Utility']];
const CATEGORY_HINTS=['Automotive','Technology','Public Utility','Transport','Consumer Guide','Energy','Maintenance','Home','Digital Safety','Public Service'];
const INTENT_TEMPLATES=[['Cara mengecek {entity}','HOW_TO'],['Penyebab {entity} dan cara mengatasinya','TROUBLESHOOTING'],['Tanda-tanda {entity} perlu diperiksa','CHECKLIST'],['Cara merawat {entity} agar lebih awet','MAINTENANCE'],['Cara memilih {entity} yang tepat','HOW_TO'],['Perbedaan {entity} dan pilihan alternatifnya','COMPARISON'],['Kesalahan umum saat menggunakan {entity}','TROUBLESHOOTING']];
const ACTION_WORDS=['mengecek','merawat','memilih','mengatasi','memahami','membaca','menyetel','membandingkan','memeriksa','menggunakan','menghemat','penyebab','tanda','perbedaan','kesalahan','cara','bagaimana','panduan','tips','langkah'];
const STOP_WORDS=new Set(['cara','bagaimana','tips','panduan','langkah','untuk','yang','agar','dan','adalah','dengan','ini','itu','motor','mobil','rumah','ponsel','efektif','tepat','umum','pilihan','alternatif']);
const PROBLEM_SUFFIX=/\s+(?:yang\s+)?(?:mati|rusak|soak|bermasalah|tidak\s+stabil|tidak\s+berfungsi|cepat\s+panas|terlalu\s+panas|brebet|sulit\s+menyala|harus\s+diganti)$/i;
const TRAILING_CLAUSE=/\s+(?:dan|serta)\s+(?:cara|tips|langkah|solusi|upaya)\b.*$/i;
const TRAILING_PURPOSE=/\s+(?:agar|supaya|untuk|tanpa)\b.*$/i;
function repeatedAdjacent(value=''){return /\b([a-z0-9]+)(?:\s+\1){1,}\b/i.test(normalizeTopic(value).toLowerCase())}
function repeatedMeaningfulToken(value=''){const counts=new Map();for(const token of normalizeTopic(value).toLowerCase().split(/[^a-z0-9]+/).filter(Boolean)){if(STOP_WORDS.has(token))continue;counts.set(token,(counts.get(token)||0)+1)}return [...counts.entries()].some(([token,count])=>count>=3&&token.length>=3)}
export function sanitizeArticleQuery(value=''){let q=normalizeTopic(value).replace(/\|+/g,' ');q=q.replace(/\s+/g,' ').trim();if(!q||q.length>120||repeatedAdjacent(q)||repeatedMeaningfulToken(q))return{valid:false,query:q,reason:repeatedAdjacent(q)||repeatedMeaningfulToken(q)?'repeated_token':'query_too_long_or_empty'};if(/\b(?:tanda|cara|penyebab|mengatasi|menghemat|perlu diperiksa)\s+(?:tanda|cara|penyebab|mengatasi|menghemat|perlu diperiksa)\b/i.test(q))return{valid:false,query:q,reason:'repeated_intent_phrase'};if(/\b(perlu diperiksa\s+){2,}|\bpenyebab(?:\s+penyebab)+\b|\bcara(?:\s+cara)+\b/i.test(q))return{valid:false,query:q,reason:'malformed_grammar'};return{valid:true,query:q,reason:null}}
export function isMalformedArticleQuery(value=''){return !sanitizeArticleQuery(value).valid}
export function extractArticleSubject(value=''){let q=normalizeTopic(value);q=q.replace(/^(?:panduan|tips|cara|bagaimana|penyebab|tanda(?:-tanda)?|fungsi|perbedaan|kesalahan(?:\s+umum)?|mengapa|kenapa)\s+/i,'');q=q.replace(/^(?:mengecek|memeriksa|merawat|memilih|menggunakan|menghemat|membaca|menyetel|mengatur|memahami|mengatasi|membandingkan)\s+/i,'');q=q.replace(TRAILING_CLAUSE,'').replace(TRAILING_PURPOSE,'').replace(PROBLEM_SUFFIX,'').replace(/\s+/g,' ').trim();return q||normalizeTopic(value)}
export function inferArticleType(topic=''){for(const [type,re] of TYPE_RULES)if(re.test(topic))return type;return'EVERGREEN'}
export function normalizeTopic(topic=''){return String(topic||'').replace(/\s+/g,' ').replace(/\|+/g,' ').trim()}
export function primaryIntentForTopic(topic=''){return normalizeTopic(topic).toLowerCase()}
function actionClass(value=''){const t=normalizeTopic(value).toLowerCase();return ACTION_WORDS.find(x=>new RegExp(`\\b${x}\\b`).test(t))||inferArticleType(t).toLowerCase()}
function tokenSet(value=''){return new Set(normalizeTopic(value).toLowerCase().split(/[^a-z0-9]+/).filter(x=>x&&!STOP_WORDS.has(x)&&!ACTION_WORDS.includes(x)))}
export function intentSignature(value=''){const t=normalizeTopic(value).toLowerCase();return`${actionClass(t)}|${[...tokenSet(t)].sort().join(' ')}`}
function semanticDuplicate(a,b){const A=tokenSet(a),B=tokenSet(b);if(!A.size||!B.size)return false;let common=0;for(const token of A)if(B.has(token))common++;const score=common/(A.size+B.size-common);return score>=0.68||[...A].every(token=>B.has(token))||[...B].every(token=>A.has(token))}
export function buildArticleIdea(topic,{category='Automotive',articleType}={}){const clean=normalizeTopic(topic).replace(/^panduan\s+/i,'');const subject=extractArticleSubject(clean);const sanitized=sanitizeArticleQuery(clean);return{contentType:'article',title:clean,topic:clean,subject,topicCluster:intentSignature(subject),category,articleType:articleType||inferArticleType(clean),primaryQuery:primaryIntentForTopic(clean),searchIntent:inferArticleType(clean)==='TROUBLESHOOTING'?'problem_solution':'informational',queryValid:sanitized.valid,queryRejectReason:sanitized.reason,status:'IDEA'}}
export async function findArticleIdeas({topic='',limit=10}={}){if(topic)return[buildArticleIdea(topic)];return discoverArticleOpportunities({limit})}
function candidateFromQuery(query,category='Automotive'){const clean=normalizeTopic(query),check=sanitizeArticleQuery(clean);if(!check.valid)return null;if(clean.length<12||!/\b(cara|penyebab|kenapa|tanda|fungsi|perbedaan|bagaimana|memilih|mengecek|merawat|menghemat|tips|solusi|berapa|kapan|kesalahan)\b/i.test(clean))return null;return buildArticleIdea(clean,{category})}
function duplicateIntent(idea,rows=[]){const target=idea.primaryQuery||idea.title;return rows.some(x=>semanticDuplicate(target,x.primaryQuery||x.title)||intentSignature(target)===intentSignature(x.primaryQuery||x.title))}
async function addCandidate(candidates,seen,idea,sourceScore,reason,rows){if(!idea||isMalformedArticleQuery(idea.primaryQuery||idea.title))return false;const signature=intentSignature(idea.primaryQuery||idea.title);if(!signature||seen.has(signature)||duplicateIntent(idea,rows))return false;const duplicate=await findDuplicateArticle(idea);if(duplicate)return false;seen.add(signature);candidates.push({...idea,sourceScore:Number(sourceScore||0),opportunityReason:reason});return true}
function categoryForEntity(entity=''){const e=entity.toLowerCase();if(/motor|mobil|aki|oli|rem|busi|karbur|speedometer|mesin|ban/.test(e))return'Automotive';if(/ponsel|android|iphone|aplikasi|password|wifi/.test(e))return'Technology';if(/listrik|tagihan|hemat energi/.test(e))return'Public Utility';return'Consumer Guide'}
function deterministicGapExpansion(rows){const entities=[...new Set(rows.slice(0,80).map(x=>extractArticleSubject(x.topicCluster||x.title)).filter(x=>x.length>=8))];for(const [seed] of EVERGREEN_FALLBACK)entities.push(extractArticleSubject(seed));const out=[];for(const entity of [...new Set(entities)].slice(0,40))for(const [template,type] of INTENT_TEMPLATES)out.push(buildArticleIdea(template.replace('{entity}',entity),{category:categoryForEntity(entity),articleType:type}));return out.slice(0,80)}
async function aiExpandCandidates(signals,existing){const key=String(process.env.GEMINI_API_KEY||'').trim();if(!key)return[];const prompt=`Buat 15 ide artikel evergreen Bahasa Indonesia yang benar-benar berbeda search intent-nya. Gunakan sinyal nyata berikut. Hindari variasi sinonim dari query yang sama, query berulang, dan frasa rusak. Output JSON array fields topic, primaryQuery, category, articleType, reason. Kategori: ${CATEGORY_HINTS.join(', ')}. Sinyal: ${signals.slice(0,25).join(' | ')}. Existing: ${existing.slice(0,60).map(x=>x.primaryQuery||x.title).filter(Boolean).join(' | ')}`;try{const response=await fetch('https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite:generateContent',{method:'POST',headers:{'content-type':'application/json','x-goog-api-key':key},body:JSON.stringify({contents:[{role:'user',parts:[{text:prompt}]}],generationConfig:{responseMimeType:'application/json',responseSchema:{type:'ARRAY',items:{type:'OBJECT',properties:{topic:{type:'STRING'},primaryQuery:{type:'STRING'},category:{type:'STRING'},articleType:{type:'STRING'},reason:{type:'STRING'}},required:['topic','primaryQuery','category','articleType','reason']}}}})});if(!response.ok)return[];const data=await response.json();const parsed=JSON.parse(data?.candidates?.[0]?.content?.parts?.map(x=>x.text||'').join('')||'[]');return Array.isArray(parsed)?parsed.map(x=>{const raw=x.primaryQuery||x.topic;const check=sanitizeArticleQuery(raw);if(!check.valid)return null;const idea=buildArticleIdea(check.query,{category:x.category||'Consumer Guide',articleType:x.articleType||inferArticleType(check.query)});return{...idea,opportunityReason:'ai_expansion',aiReason:x.reason||''}}).filter(Boolean):[]}catch{return[]}}
export async function discoverArticleOpportunities({limit=10}={}){const rows=await listAllArticles(),analytics=await readSearchAnalytics().catch(()=>[]),candidates=[],seen=new Set();const queryRows=[...analytics].filter(x=>String(x.query||'').trim()).sort((a,b)=>(Number(b.impressions||0)*2+Number(b.clicks||0)*5)-(Number(a.impressions||0)*2+Number(a.clicks||0)*5));for(const row of queryRows){const idea=candidateFromQuery(row.query);if(idea)await addCandidate(candidates,seen,idea,Math.min(100,Number(row.impressions||0)+Number(row.clicks||0)*5),'search_console',rows);if(candidates.length>=limit)break}if(candidates.length<limit)for(const n of rows.slice(0,100)){const m=evaluateSearchOpportunity(n);if(Number(m.searchScore||0)<70)continue;const topic=normalizeTopic(n.topicCluster||n.title||'');const idea=candidateFromQuery(topic,n.category||'Automotive')||candidateFromQuery(`cara ${topic}`,n.category||'Automotive');if(idea)await addCandidate(candidates,seen,idea,Number(m.searchScore||0),'topic_cluster',rows);if(candidates.length>=limit)break}if(candidates.length<limit)for(const [topic,category] of EVERGREEN_FALLBACK){await addCandidate(candidates,seen,buildArticleIdea(topic,{category}),70,'evergreen_seed',rows);if(candidates.length>=limit)break}if(candidates.length<limit)for(const idea of deterministicGapExpansion(rows)){await addCandidate(candidates,seen,idea,62,'evergreen_gap',rows);if(candidates.length>=limit)break}if(candidates.length<limit){const signals=[...queryRows.slice(0,15).map(x=>x.query),...rows.slice(0,20).map(x=>x.title||x.topicCluster)].filter(Boolean);for(const idea of await aiExpandCandidates(signals,rows)){await addCandidate(candidates,seen,idea,65,'ai_expansion',rows);if(candidates.length>=limit)break}}return candidates.sort((a,b)=>(Number(b.sourceScore||0)+scoreArticleIdea(b))-(Number(a.sourceScore||0)+scoreArticleIdea(a))).slice(0,limit)}
export async function discoverArticleOpportunity(){return(await discoverArticleOpportunities({limit:10}))[0]||null}
export function scoreArticleIdea(idea={}){const q=String(idea.primaryQuery||'').trim();return Math.max(0,Math.min(100,40+(q.split(/\s+/).length>=3?20:0)+(idea.articleType!=='EVERGREEN'?15:5)+(idea.category?10:0)+(q.length>=20?15:0)+(idea.queryValid===false?-50:0)))}
