import {createHash,randomUUID} from 'node:crypto';
import {readFile,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {persistenceConfigured,getJson,setJson,acquireLock,releaseLock} from './persistence.js';
import {articleIsIndexable,normalizeArticleStatus,normalizeArticleType} from './article-types.js';
const KEY='ba:content:articles';const PATH=join(process.cwd(),'data','articles-content.json');
const slugify=v=>String(v||'artikel').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9\s-]/g,'').trim().replace(/\s+/g,'-').replace(/-+/g,'-').slice(0,100)||'artikel';
async function localRead(){try{return JSON.parse(await readFile(PATH,'utf8'))}catch{return[]}}
export async function readArticlesContent(){if(persistenceConfigured()){const value=await getJson(KEY);return Array.isArray(value)?value:[]}return localRead()}
export async function writeArticlesContent(items){const rows=Array.isArray(items)?items:[];if(persistenceConfigured())await setJson(KEY,rows);else await writeFile(PATH,JSON.stringify(rows,null,2)+'\n','utf8');return rows}
export function articleFingerprint(input={}){return createHash('sha256').update([input.title,input.primaryQuery,input.topicCluster,(input.entities||[]).join('|')].join('|').toLowerCase()).digest('hex').slice(0,20)}
export function normalizeArticle(input={}){const now=new Date().toISOString(),status=normalizeArticleStatus(input.status),id=String(input.id||randomUUID()),fingerprint=input.fingerprint||articleFingerprint(input);const baseSlug=slugify(input.slug||input.title);return {...input,id,fingerprint,contentType:'article',articleType:normalizeArticleType(input.articleType),status,slug:input.slug||`${baseSlug}-${fingerprint.slice(0,8)}`,robots:status==='PUBLISHED'?'index, follow':'noindex, nofollow',indexable:status==='PUBLISHED',createdAt:input.createdAt||now,updatedAt:now}}
export async function upsertArticle(input){const rows=await readArticlesContent();const normalized=normalizeArticle(input);const index=rows.findIndex(x=>x.id===normalized.id||x.fingerprint===normalized.fingerprint);if(index>=0)rows[index]={...rows[index],...normalized,createdAt:rows[index].createdAt,updatedAt:new Date().toISOString()};else rows.unshift(normalized);await writeArticlesContent(rows);return index>=0?rows[index]:normalized}
export async function findArticle(idOrSlug){const rows=await readArticlesContent();return rows.find(x=>String(x.id)===String(idOrSlug)||String(x.slug)===String(idOrSlug))||null}
export async function listPublishedArticles(){return (await readArticlesContent()).filter(articleIsIndexable).sort((a,b)=>Date.parse(b.updatedAt||0)-Date.parse(a.updatedAt||0))}
export async function listAllArticles(){return (await readArticlesContent()).sort((a,b)=>Date.parse(b.updatedAt||0)-Date.parse(a.updatedAt||0))}
export async function findDuplicateArticle(candidate){const rows=await readArticlesContent();const q=String(candidate.primaryQuery||'').toLowerCase().trim(),topic=String(candidate.topicCluster||'').toLowerCase().trim(),title=String(candidate.title||'').toLowerCase();for(const row of rows){if(row.id===candidate.id)continue;if(q&&String(row.primaryQuery||'').toLowerCase().trim()===q)return{type:'UPDATE_EXISTING',article:row,reason:'primary_query_match'};if(topic&&topic===String(row.topicCluster||'').toLowerCase().trim())return{type:'UPDATE_EXISTING',article:row,reason:'topic_cluster_match'};const words=title.split(/\s+/).filter(x=>x.length>3),hits=words.filter(w=>String(row.title||'').toLowerCase().includes(w)).length;if(words.length>=5&&hits/words.length>=0.8)return{type:'UPDATE_EXISTING',article:row,reason:'title_similarity'}}return null}
export async function withArticleLock(fn,ttl=600){const key='ba:article:publish:lock',token=randomUUID();if(persistenceConfigured()){if(!await acquireLock(key,token,ttl))return{status:'skipped',reason:'locked'};try{return await fn()}finally{await releaseLock(key,token)}}return fn()}
