const GOOGLE_NEWS_HOST='news.google.com';
const TRACKING_HOSTS=new Set(['news.google.com','google.com','www.google.com','gstatic.com','googleusercontent.com']);
// Source resolution never promotes tracking pixels or image assets to public article links.
export function humanSourceType(value=''){const key=String(value||'').toLowerCase();if(key==='search_discovered')return 'Media / Referensi';if(key==='official')return 'Sumber Resmi';if(key==='manufacturer')return 'Produsen / Dokumentasi Resmi';if(key==='manual')return 'Manual / Dokumentasi';if(key==='government')return 'Pemerintah';if(key==='technical')return 'Referensi Teknis';return value?'Referensi':'Media / Referensi'}
function domainOf(url=''){try{return new URL(url).hostname.replace(/^www\./,'')}catch{return ''}}
export function sourceDomain(source={}){return domainOf(source.canonicalUrl||source.resolvedUrl||source.url||'')}
export function isGoogleNewsUrl(url=''){return domainOf(url)===GOOGLE_NEWS_HOST}
function isTrackingHost(host=''){const h=String(host).toLowerCase();return TRACKING_HOSTS.has(h)||h.endsWith('.googleusercontent.com')||h.endsWith('.gstatic.com')}
function safeExternalUrl(value=''){try{const u=new URL(value);const host=u.hostname.toLowerCase();if(!/^https?:$/i.test(u.protocol)||isTrackingHost(host)||/\.(gif|png|jpe?g|webp|svg|ico)(\?|$)/i.test(u.pathname))return '';if(u.pathname.length<2)return '';return u.toString()}catch{return ''}}
async function resolveGoogleNewsUrl(url){if(!isGoogleNewsUrl(url))return url;const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),4500);try{const response=await fetch(url,{redirect:'follow',signal:controller.signal,headers:{'user-agent':'BeritaAuto/1.0 source-resolver','accept':'text/html,application/xhtml+xml'}});if(response.url&&!isGoogleNewsUrl(response.url)){const direct=safeExternalUrl(response.url);if(direct)return direct}const html=await response.text();const canonical=html.match(/<link[^>]+rel=["']canonical["'][^>]+href=["']([^"']+)["']/i)?.[1]||html.match(/<meta[^>]+property=["']og:url["'][^>]+content=["']([^"']+)["']/i)?.[1];const directCanonical=safeExternalUrl(canonical||'');if(directCanonical)return directCanonical;const urls=[...html.matchAll(/https?:\\?\/\\?\/[^\s"'<>\\]+/gi)].map(m=>m[0].replace(/\\\//g,'/')).map(safeExternalUrl).filter(Boolean);return urls[0]||url}catch{return url}finally{clearTimeout(timer)}}
export async function resolveArticleSources(sources=[]){const resolved=[];const seen=new Set();for(const source of Array.isArray(sources)?sources:[]){const discoveryUrl=source.discoveryUrl||source.url||'';const resolvedUrl=source.resolvedUrl||await resolveGoogleNewsUrl(discoveryUrl);const canonicalUrl=source.canonicalUrl||resolvedUrl;const key=`${domainOf(canonicalUrl)}|${canonicalUrl}`.toLowerCase();if(!canonicalUrl||seen.has(key))continue;seen.add(key);resolved.push({...source,discoveryUrl,resolvedUrl,canonicalUrl,url:canonicalUrl})}return resolved}
