import {evaluateSearchOpportunity} from './search-intent.js';
import {listAllArticles,findDuplicateArticle} from './article-storage.js';
const TYPE_RULES=[['HOW_TO',/\b(cara|bagaimana|langkah|menyetel|memilih|mengecek|membaca)\b/i],['TROUBLESHOOTING',/\b(penyebab|kenapa|brebet|mati|rusak|soak|tidak stabil|overheat)\b/i],['COMPARISON',/\b(perbedaan|vs|dibandingkan|bagus mana|lebih baik)\b/i],['FAQ',/\b(apa itu|apakah|faq|pertanyaan)\b/i],['CHECKLIST',/\b(tanda-tanda|cek|daftar)\b/i],['MAINTENANCE',/\b(perawatan|merawat|servis|maintenance)\b/i],['EXPLAINER',/\b(mengapa|fungsi|penjelasan|arti)\b/i]];
const STOP=new Set('yang dan untuk dari dengan pada dalam ini itu agar atau akan telah dapat adalah karena juga tidak lebih para sebuah motor mobil berita terbaru hari ini langsung cara tips panduan'.split(' '));
export function inferArticleType(topic=''){for(const [type,re] of TYPE_RULES)if(re.test(topic))return type;return 'EVERGREEN'}
export function normalizeTopic(topic=''){return String(topic||'').replace(/\s+/g,' ').trim()}
export function primaryIntentForTopic(topic=''){const t=normalizeTopic(topic).toLowerCase();if(/\b(cara|bagaimana|menyetel|mengecek|memilih|merawat)\b/.test(t))return t; if(/\b(penyebab|kenapa|tanda)\b/.test(t))return t; if(/\b(perbedaan|vs|bagus mana)\b/.test(t))return t;return t}
export function buildArticleIdea(topic,{category='Automotive',articleType}={}){const clean=normalizeTopic(topic);return{contentType:'article',title:clean,topic:clean,topicCluster:clean.toLowerCase().replace(/[^a-z0-9\s]/g,'').replace(/\s+/g,' ').trim(),category,articleType:articleType||inferArticleType(clean),primaryQuery:primaryIntentForTopic(clean),searchIntent:inferArticleType(clean)==='TROUBLESHOOTING'?'problem_solution':'informational',status:'IDEA'}}
export async function findArticleIdeas({topic='',limit=10}={}){if(topic)return[buildArticleIdea(topic)];const news=await listAllArticles();const candidates=[];for(const n of news.slice(0,80)){const m=evaluateSearchOpportunity(n);if(m.searchScore<70)continue;const sourceTopic=String(n.topicCluster||n.title||'').trim();if(!sourceTopic)continue;const idea=buildArticleIdea(`Panduan ${sourceTopic}`);const duplicate=await findDuplicateArticle(idea);if(!duplicate)candidates.push({...idea,derivedFromNewsId:n.id,sourceScore:m.searchScore});if(candidates.length>=limit)break}return candidates}
export function scoreArticleIdea(idea={}){const q=String(idea.primaryQuery||'').trim();const score=Math.min(100,40+(q.split(/\s+/).length>=3?20:0)+(idea.articleType!=='EVERGREEN'?15:5)+(idea.category?10:0)+(q.length>=20?15:0));return Math.max(0,score)}
