import {evaluateSearchOpportunity} from './search-intent.js';
import {listAllArticles,findDuplicateArticle} from './article-storage.js';
import {readSearchAnalytics} from './search-data.js';

const TYPE_RULES=[['HOW_TO',/\b(cara|bagaimana|langkah|menyetel|memilih|mengecek|membaca|mengatur|menggunakan)\b/i],['TROUBLESHOOTING',/\b(penyebab|kenapa|brebet|mati|rusak|soak|tidak stabil|overheat|bermasalah)\b/i],['COMPARISON',/\b(perbedaan|vs|dibandingkan|bagus mana|lebih baik)\b/i],['FAQ',/\b(apa itu|apakah|faq|pertanyaan)\b/i],['CHECKLIST',/\b(tanda-tanda|cek|daftar|checklist)\b/i],['MAINTENANCE',/\b(perawatan|merawat|servis|maintenance)\b/i],['EXPLAINER',/\b(mengapa|fungsi|penjelasan|arti)\b/i]];
const EVERGREEN_FALLBACK=[['Cara menyetel karburator motor agar langsam stabil','Automotive'],['Penyebab motor brebet saat digas dan cara mengeceknya','Automotive'],['Cara membaca warna busi motor','Automotive'],['Penyebab speedometer motor mati','Automotive'],['Cara mengecek aki motor mulai soak','Automotive'],['Cara memilih oli motor yang tepat','Automotive'],['Tanda-tanda kampas rem harus diganti','Automotive'],['Penyebab mesin motor cepat panas','Automotive'],['Cara merawat motor setelah terendam banjir','Automotive'],['Perbedaan motor injeksi dan karburator','Automotive'],['Cara merawat baterai ponsel agar lebih awet','Technology'],['Cara menghemat listrik rumah tanpa mengurangi kenyamanan','Public Utility']];
const CATEGORY_HINTS=['Automotive','Technology','Public Utility','Transport','Consumer Guide','Energy','Maintenance','Home','Digital Safety','Public Service'];
const INTENT_TEMPLATES=[['Cara mengecek {entity}','HOW_TO'],['Penyebab {entity} dan cara mengatasinya','TROUBLESHOOTING'],['Tanda-tanda {entity} perlu diperiksa','CHECKLIST'],['Cara merawat {entity} agar lebih awet','MAINTENANCE'],['Cara memilih {entity} yang tepat','HOW_TO'],['Perbedaan {entity} dan pilihan alternatifnya','COMPARISON'],['Kesalahan umum saat menggunakan {entity}','TROUBLESHOOTING']];

export function inferArticleType(topic=''){for(const [type,re] of TYPE_RULES)if(re.test(topic))return type;return 'EVERGREEN'}
export function normalizeTopic(topic=''){return String(topic||'').replace(/\s+/g,' ').trim()}
export function primaryIntentForTopic(topic=''){return normalizeTopic(topic).toLowerCase()}
function intentSignature(value=''){return normalizeTopic(value).toLowerCase().replace(/\b(cara|bagaimana|tips|panduan|langkah|untuk|yang|agar|dan|motor|mobil|rumah|ponsel)\b/g,' ').replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim()}
export function buildArticleIdea(topic,{category='Automotive',articleType}={}){const clean=normalizeTopic(topic).replace(/^panduan\s+/i,'');return{contentType:'article',title:clean,topic:clean,topicCluster:intentSignature(clean),category,articleType:articleType||inferArticleType(clean),primaryQuery:primaryIntentForTopic(clean),searchIntent:inferArticleType(clean)==='TROUBLESHOOTING'?'problem_solution':'informational',status:'IDEA'}}
export async function findArticleIdeas({topic='',limit=10}={}){if(topic)return[buildArticleIdea(topic)];return discoverArticleOpportunities({limit});}
function candidateFromQuery(query,category='Automotive'){const clean=normalizeTopic(query).replace(/^panduan\s+/i,'');if(clean.length<12||!/\b(cara|penyebab|kenapa|tanda|fungsi|perbedaan|bagaimana|memilih|mengecek|merawat|tips|solusi|berapa|kapan|kesalahan)\b/i.test(clean))return null;return buildArticleIdea(clean,{category})}
function duplicateIntent(row,existing=[]){const sig=intentSignature(row.primaryQuery||row.title);if(!sig)return false;return existing.some(x=>intentSignature(x.primaryQuery||x.title)===sig)}
async function addCandidate(candidates,seen,idea,sourceScore=0,reason='unknown',rows=[]){if(!idea)return false;const signature=intentSignature(idea.primaryQuery||idea.title);if(!signature||seen.has(signature)||duplicateIntent(idea,rows))return false;const duplicate=await findDuplicateArticle(idea);if(duplicate)return false;seen.add(signature);candidates.push({...idea,sourceScore:Number(sourceScore||0),opportunityReason:reason});return true}

function deterministicGapExpansion(rows){const out=[];const entities=[];for(const row of rows.slice(0,80)){const cluster=normalizeTopic(row.topicCluster||'');if(cluster&&cluster.length>=4)entities.push(cluster)}for(const [seed,category] of EVERGREEN_FALLBACK){const words=seed.replace(/^cara|^penyebab|^tanda-tanda|^perbedaan/ig,'').replace(/\s+/g,' ').trim();if(words.length>=8)entities.push(words)}const unique=[...new Set(entities)].slice(0,30);for(const entity of unique){for(const [template,type] of INTENT_TEMPLATES){const topic=template.replace('{entity}',entity);out.push(buildArticleIdea(topic,{category:categoryForEntity(entity),articleType:type}))}}return out.slice(0,60)}
function categoryForEntity(entity=''){const e=entity.toLowerCase();if(/motor|mobil|aki|oli|rem|busi|karbur|speedometer|mesin|ban/.test(e))return'Automotive';if(/ponsel|android|iphone|aplikasi|password|wifi/.test(e))return'Technology';if(/listrik|tagihan|hemat energi/.test(e))return'Public Utility';return'Consumer Guide'}

async function aiExpandCandidates(signals,existing){const key=String(process.env.GEMINI_API_KEY||'').trim();if(!key)return[];const prompt=`Buat 15 ide artikel evergreen Bahasa Indonesia yang benar-benar berbeda search intent-nya. Gunakan sinyal nyata berikut dan jangan mengulang intent yang sudah ada. Setiap ide harus berguna, dapat diriset dari minimal dua sumber publik, dan tidak memerlukan berita terbaru. Hindari variasi sinonim dari query yang sama. Output JSON array saja dengan fields topic, primaryQuery, category, articleType, reason.\nKategori yang tersedia: ${CATEGORY_HINTS.join(', ')}\nSinyal pencarian: ${signals.slice(0,25).join(' | ')}\nArtikel/query yang sudah ada: ${existing.slice(0,60).map(x=>x.primaryQuery||x.title).filter(Boolean).join(' | ')}`;
try{const response=await fetch('https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite:generateContent',{method:'POST',headers:{'content-type':'application/json','x-goog-api-key':key},body:JSON.stringify({contents:[{role:'user',parts:[{text:prompt}]}],generationConfig:{responseMimeType:'application/json',responseSchema:{type:'ARRAY',items:{type:'OBJECT',properties:{topic:{type:'STRING'},primaryQuery:{type:'STRING'},category:{type:'STRING'},articleType:{type:'STRING'},reason:{type:'STRING'}},required:['topic','primaryQuery','category','articleType','reason']}}}})});if(!response.ok)return[];const data=await response.json();const text=data?.candidates?.[0]?.content?.parts?.map(x=>x.text||'').join('')||'[]';const parsed=JSON.parse(text);return Array.isArray(parsed)?parsed.map(x=>buildArticleIdea(x.primaryQuery||x.topic,{category:x.category||'Consumer Guide',articleType:x.articleType||inferArticleType(x.primaryQuery||x.topic)})).map((idea,i)=>({...idea,opportunityReason:'ai_expansion',aiReason:parsed[i]?.reason||''})):[]}catch{return[]}}

export async function discoverArticleOpportunities({limit=10}={}){const rows=await listAllArticles();const analytics=await readSearchAnalytics().catch(()=>[]);const candidates=[];const seen=new Set();
  const queryRows=[...analytics].filter(x=>String(x.query||'').trim()).sort((a,b)=>(Number(b.impressions||0)*2+Number(b.clicks||0))-(Number(a.impressions||0)*2+Number(a.clicks||0)));
  for(const row of queryRows){const idea=candidateFromQuery(row.query);if(idea)await addCandidate(candidates,seen,idea,Math.min(100,Number(row.impressions||0)+Number(row.clicks||0)*5),'search_console',rows);if(candidates.length>=limit)break}
  if(candidates.length<limit){for(const n of rows.slice(0,100)){const m=evaluateSearchOpportunity(n);if(Number(m.searchScore||0)<70)continue;const sourceTopic=String(n.topicCluster||'').trim();const idea=candidateFromQuery(sourceTopic,n.category||'Automotive')||candidateFromQuery(`cara ${sourceTopic}`,n.category||'Automotive');if(idea)await addCandidate(candidates,seen,idea,Number(m.searchScore||0),'topic_cluster',rows);if(candidates.length>=limit)break}}
  if(candidates.length<limit){for(const [topic,category] of EVERGREEN_FALLBACK){const idea=buildArticleIdea(topic,{category});await addCandidate(candidates,seen,idea,70,'evergreen_seed',rows);if(candidates.length>=limit)break}}
  if(candidates.length<limit){for(const idea of deterministicGapExpansion(rows)){await addCandidate(candidates,seen,idea,62,'evergreen_gap',rows);if(candidates.length>=limit)break}}
  if(candidates.length<limit){const signals=[...queryRows.slice(0,15).map(x=>x.query),...rows.slice(0,20).map(x=>x.title||x.topicCluster)].filter(Boolean);const aiIdeas=await aiExpandCandidates(signals,rows);for(const idea of aiIdeas){await addCandidate(candidates,seen,idea,65,'ai_expansion',rows);if(candidates.length>=limit)break}}
  return candidates.sort((a,b)=>(Number(b.sourceScore||0)+scoreArticleIdea(b))-(Number(a.sourceScore||0)+scoreArticleIdea(a))).slice(0,limit)
}
export async function discoverArticleOpportunity(){const rows=await discoverArticleOpportunities({limit:10});return rows[0]||null}
export function scoreArticleIdea(idea={}){const q=String(idea.primaryQuery||'').trim();return Math.max(0,Math.min(100,40+(q.split(/\s+/).length>=3?20:0)+(idea.articleType!=='EVERGREEN'?15:5)+(idea.category?10:0)+(q.length>=20?15:0)))}
export {intentSignature};
