import {fingerprint} from './hash.js';

export const MAX_CAPTION_LENGTH=2100;
export const IDEAL_CAPTION_MIN=1300;
export const IDEAL_CAPTION_MAX=1900;
const MIN_CAPTION_LENGTH=700;
const SOURCE_FIELDS=['content','body','articleText','cleanedContent','fullText','text'];
const CAPTION_CACHE=new Map();
const GENERIC=new Set('yang dan untuk dari dengan pada dalam adalah akan telah dapat ini itu oleh sebagai karena juga tidak lebih para sebuah menjadi terhadap setelah sebelum tentang serta mereka kami kita agar jika ketika melalui menurut sebagai antara hanya sangat masih sudah bahwa'.split(/\s+/));
const BOILERPLATE=/^(?:baca juga|selengkapnya|subscribe|berlangganan|newsletter|ikuti kami|share|bagikan|advertisement|iklan|copyright|all rights reserved|berita terkait|artikel terkait|rekomendasi|login|sign in)\b/i;
const CATEGORY_TERMS={Otomotif:['otomotif','mobil','motor','kendaraan','toyota','honda','yamaha','suzuki','avanza','vario','fortuner','pajero','hybrid','listrik','ev'],Nasional:['nasional','pemerintah','kementerian','presiden','dpr','polisi','jakarta','provinsi','kabupaten','kota'],Teknologi:['teknologi','ai','artificial intelligence','smartphone','aplikasi','software','internet','digital','chip','startup'],Olahraga:['olahraga','sepak bola','bola','liga','klub','tim nasional','pemain','atlet','pertandingan'],Hiburan:['hiburan','artis','film','musik','penyanyi','aktor','aktris','konser','serial'],Ekonomi:['ekonomi','bisnis','saham','rupiah','bank','inflasi','pajak','ekspor','impor','perusahaan'],Internasional:['internasional','amerika','china','tiongkok','jepang','rusia','ukraina','palestina','israel']};
function normalize(value=''){return String(value||'').replace(/\u00a0/g,' ').replace(/<[^>]+>/g,' ').replace(/&(?:nbsp|amp|quot|apos|lt|gt);/gi,' ').replace(/[ \t]+/g,' ').replace(/\s*\n\s*/g,'\n').trim()}
function plain(value=''){return normalize(value).replace(/\s+/g,' ').trim()}
function sourceText(article={}){for(const field of SOURCE_FIELDS){const value=normalize(article?.[field]);if(value.length>=80)return value}return normalize(article?.summary||article?.excerpt||'')}
function sentences(text=''){return String(text).replace(/\n+/g,' ').match(/[^.!?]+[.!?]+|[^.!?]+$/g)?.map(plain).filter(x=>x.length>=45&&!BOILERPLATE.test(x))||[]}
function tokenSet(value=''){return new Set(plain(value).toLowerCase().replace(/[^\p{L}\p{N}\s-]/gu,' ').split(/\s+/).filter(x=>x.length>2&&!GENERIC.has(x)))}
function overlap(a,b){const aa=tokenSet(a),bb=tokenSet(b);if(!aa.size||!bb.size)return 0;let hit=0;for(const x of aa)if(bb.has(x))hit++;return hit/Math.max(aa.size,bb.size)}
function hasNumber(value){return /\b\d[\d.,:%-]*(?:\s*(?:juta|miliar|persen|%|km|kg|orang|tahun|bulan|hari))?\b/i.test(value)}
function hasDate(value){return /\b(?:senin|selasa|rabu|kamis|jumat|sabtu|minggu|januari|februari|maret|april|mei|juni|juli|agustus|september|oktober|november|desember)\b|\b20\d{2}\b|\b\d{1,2}[/-]\d{1,2}[/-]20\d{2}\b/i.test(value)}
function hasReason(value){return /\b(?:karena|sebab|akibat|agar|untuk|sehingga|menurut|setelah|sebelum|disebabkan|bertujuan)\b/i.test(value)}
function hasLocation(value){return /\b(?:di|dari|ke)\s+[A-Z][\p{L}\d.'’-]*(?:\s+[A-Z][\p{L}\d.'’-]*){0,3}/u.test(value)}
function rankSentences(article,text,title){const titleTokens=tokenSet(title);const category=String(article?.category||'').trim();const terms=(CATEGORY_TERMS[category]||[]).map(x=>x.toLowerCase());return sentences(text).map((sentence,index)=>{const tokens=tokenSet(sentence);let titleHit=0;for(const token of titleTokens)if(tokens.has(token))titleHit++;const categoryHit=terms.filter(term=>sentence.toLowerCase().includes(term)).length;const entityHit=(sentence.match(/\b[A-ZÀ-ÖØ-Þ][\p{L}\d&.'’-]{2,}(?:\s+[A-ZÀ-ÖØ-Þ][\p{L}\d&.'’-]{2,}){0,3}/gu)||[]).length;const score=titleHit*5+(hasNumber(sentence)?6:0)+(hasDate(sentence)?4:0)+(hasReason(sentence)?3:0)+(hasLocation(sentence)?3:0)+Math.min(6,categoryHit*2)+Math.min(6,entityHit)+(index<5?4-index*.5:0)+(sentence.length>=70&&sentence.length<=320?2:0);return{sentence,index,score}}).sort((a,b)=>b.score-a.score||a.index-b.index)}
function dedupeSentences(items){const out=[];for(const item of items){if(out.some(existing=>overlap(existing.sentence,item.sentence)>=.72))continue;out.push(item)}return out}
function fitParagraph(text,max){if(text.length<=max)return text;const cut=text.slice(0,max+1);const match=cut.match(/^([\s\S]*?[.!?])(?:\s|$)/);return (match?.[1]||cut.replace(/\s+\S*$/,'')).trim()}
function statusFor(length,sourceLength){if(sourceLength<250&&length<700)return'TOO_SHORT_SOURCE_LIMITED';if(length<MIN_CAPTION_LENGTH)return'TOO_SHORT';if(length>MAX_CAPTION_LENGTH)return'TOO_LONG';return'GOOD'}
function coverageFor(article,body,title){const joined=plain(`${title} ${body}`);const lower=joined.toLowerCase();const titleLower=plain(title).toLowerCase();const who=Boolean((title.match(/\b[A-ZÀ-ÖØ-Þ][\p{L}\d&.'’-]{2,}/gu)||[]).length||article?.entities?.length||/\b(?:pemerintah|presiden|kementerian|polisi|tim|klub|perusahaan|bank)\b/i.test(lower));const what=Boolean(titleLower&&lower.includes(titleLower.split(/\s+/).slice(0,3).join(' ')));const when=hasDate(joined);const where=hasLocation(joined);const why=hasReason(joined);const numbers=(joined.match(/\b\d[\d.,:%-]*/g)||[]).length;const keyFacts=Math.min(8,(joined.match(/\b(?:menurut|hasil|putusan|mencapai|sebesar|sebanyak|tercatat|naik|turun|menang|kalah|menetapkan|memutuskan)\b/gi)||[]).length);return{who,what,when,where,why,how:Boolean(/\b(?:dengan|melalui|setelah|sebelum|menggunakan|dilakukan|berlangsung|terjadi)\b/i.test(lower)),keyFacts,importantNumbers:numbers,impactContext:Boolean(body.split(/\n\n/).length>=3||/\b(?:dampak|berdampak|penting|membuat|memberi|menjadi|diperkirakan|konteks)\b/i.test(lower))}}
function hashtags(article,title,body){const values=[];const add=value=>{const normalized=plain(value).normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^\p{L}\p{N}]+/gu,'');if(!normalized)return;const h=`#${normalized}`;if(['#Berita','#News','#Indonesia','#Viral','#Fyp'].some(x=>x.toLowerCase()===h.toLowerCase()))return;if(!values.some(x=>x.toLowerCase()===h.toLowerCase()))values.push(h)};add('BeritaAuto');add(article?.category);const entities=Array.isArray(article?.entities)?article.entities:[];entities.slice(0,3).forEach(add);for(const term of Object.values(CATEGORY_TERMS).flat()){if(values.length>=6)break;if(body.toLowerCase().includes(term.toLowerCase())&&title.toLowerCase().includes(term.toLowerCase()))add(term)}return values.slice(0,8)}
function chooseSentences(article,text,title,target){const ranked=dedupeSentences(rankSentences(article,text,title));const selected=[];for(const item of ranked.slice(0,Math.min(7,ranked.length))){if(selected.some(x=>overlap(x.sentence,item.sentence)>=.72))continue;selected.push(item);if(plain(selected.map(x=>x.sentence).join(' ')).length>=target)break}return selected.sort((a,b)=>a.index-b.index)}
export function buildInstagramCaption(article={},siteUrl='https://berita-auto.vercel.app'){const title=plain(article?.title||'Berita terbaru');const source=sourceText(article);const sourceHash=fingerprint(source||title);const cacheKey=`${article?.id||'no-id'}:${sourceHash}`;const cached=CAPTION_CACHE.get(cacheKey);if(cached){return{...cached,captionGeneratedAt:cached.captionGeneratedAt}}const started=Date.now();const sourceLength=source.length;const publisher=plain(article?.publisher||article?.sourceName||article?.source||'');console.log(`[CAPTION_GENERATION_START] articleId=${article?.id||'unknown'}`);console.log(`[CAPTION_SOURCE_LOADED] articleId=${article?.id||'unknown'} sourceChars=${sourceLength}`);const summary=plain(article?.excerpt||article?.summary||'');const sourceForSelection=source||summary||title;const targetBody=Math.min(1550,Math.max(700,Math.floor((sourceForSelection.length||summary.length||title.length)*.55)));const selected=chooseSentences(article,sourceForSelection,title,targetBody);const intro=selected.slice(0,Math.min(3,selected.length)).map(x=>x.sentence);const detail=selected.slice(Math.min(3,selected.length),Math.min(7,selected.length)).map(x=>x.sentence);const context=selected.slice(7,9).map(x=>x.sentence);const paragraphsOut=[];paragraphsOut.push(title);if(intro.length)paragraphsOut.push(intro.join(' '));if(detail.length)paragraphsOut.push(detail.join(' '));if(context.length)paragraphsOut.push(context.join(' '));if(!detail.length&&summary&&plain(summary)!==plain(intro.join(' ')))paragraphsOut.push(summary);if(publisher)paragraphsOut.push(`Sumber: ${publisher}`);paragraphsOut.push('Ikuti Berita Auto untuk update berita terbaru.');const tags=hashtags(article,title,sourceForSelection);const body=paragraphsOut.map(x=>plain(x)).filter(Boolean).join('\n\n');let caption=`${body}\n\n${tags.join(' ')}`;if(caption.length>MAX_CAPTION_LENGTH){const reserved=tags.join(' ').length+2;const bodyLimit=MAX_CAPTION_LENGTH-reserved;const paragraphs=body.split(/\n\n/);let kept=[];let used=0;for(const paragraph of paragraphs){const next=used?(used+2+paragraph.length):paragraph.length;if(next>bodyLimit)break;kept.push(paragraph);used=next}if(kept.length<2)kept=paragraphs.slice(0,1);caption=`${fitParagraph(kept.join('\n\n'),bodyLimit)}\n\n${tags.join(' ')}`;caption=caption.slice(0,MAX_CAPTION_LENGTH);}
const length=caption.length;const coverage=coverageFor(article,body,title);const lengthStatus=statusFor(length,sourceLength);const qualityStatus=lengthStatus==='GOOD'&&coverage.who&&coverage.what&&coverage.keyFacts>=0?'GOOD':lengthStatus==='TOO_SHORT_SOURCE_LIMITED'?'SOURCE_LIMITED':'WARNING';const result={caption,captionBody:body,hashtags:tags,captionLength:length,captionLengthStatus:lengthStatus,captionQualityStatus:qualityStatus,captionGeneratedBy:'deterministic-rich',captionGeneratedAt:new Date().toISOString(),captionSourceLength:sourceLength,captionSourceHash:sourceHash,captionCoverage:coverage,oneAiCallMax:0,generationDurationMs:Date.now()-started,articleUrl:`${String(siteUrl).replace(/\/$/,'')}/berita/${article?.slug||article?.id||''}`};if(CAPTION_CACHE.size>=128)CAPTION_CACHE.delete(CAPTION_CACHE.keys().next().value);CAPTION_CACHE.set(cacheKey,result);console.log(`[CAPTION_VALIDATION] articleId=${article?.id||'unknown'} length=${length} status=${lengthStatus} quality=${qualityStatus}`);console.log(`[CAPTION_READY] articleId=${article?.id||'unknown'} length=${length}`);return result}
export function validateInstagramCaption(caption,article={}){const value=plain(caption);const source=sourceText(article);const coverage=coverageFor(article,value,plain(article?.title||''));const errors=[];const warnings=[];if(!value)errors.push('CAPTION_EMPTY');if(value.length>MAX_CAPTION_LENGTH)errors.push('CAPTION_TOO_LONG');if(value.length<MIN_CAPTION_LENGTH&&source.length>=250)warnings.push('CAPTION_TOO_SHORT');if(/\b(?:Entity|Keyword|SEO|internal id|metadata|system prompt)\s*:/i.test(value))errors.push('INTERNAL_METADATA');if(/<[^>]+>|\*\*|```/i.test(value))errors.push('UNSAFE_FORMAT');if((value.match(/#[\p{L}\p{N}_-]+/gu)||[]).length>8)errors.push('TOO_MANY_HASHTAGS');if(!value.includes('#BeritaAuto'))errors.push('MISSING_BRAND_HASHTAG');const paragraphs=value.split(/\n\n/).filter(Boolean);if(paragraphs.length<3&&source.length>=250)warnings.push('LOW_PARAGRAPH_COUNT');if(paragraphs.some(p=>p.length>650))warnings.push('LONG_PARAGRAPH');if(source.length>=250&&coverage.keyFacts===0)warnings.push('LOW_FACT_SIGNAL');return{valid:errors.length===0,warnings,errors,captionLength:value.length,captionLengthStatus:statusFor(value.length,source.length),captionCoverage:coverage}}
export function getInstagramCaptionSource(article={}){const source=sourceText(article);return{source,sourceLength:source.length,sourceField:SOURCE_FIELDS.find(field=>normalize(article?.[field]).length>=80)||((article?.summary||article?.excerpt)?'summary_or_excerpt':'title')}}
