const baseUrl=process.env.UPSTASH_REDIS_REST_URL||'';
const token=process.env.UPSTASH_REDIS_REST_TOKEN||'';
const MAX_RETRIES=2;
const CAPACITY_COOLDOWN_MS=15*60*1000;
const RETRY_BASE_MS=80;
export class PersistenceError extends Error{constructor(message,{code='PERSISTENCE_ERROR',operation='unknown',key=null,status=null,stage='command',durationMs=0,transient=false,cause=null}={}){super(message);this.name='PersistenceError';this.code=code;this.operation=operation;this.key=key;this.status=status;this.stage=stage;this.durationMs=durationMs;this.transient=transient;this.cause=cause;}}
export function persistenceConfigured(){return Boolean(baseUrl&&token)}
const safeKey=key=>String(key||'').slice(0,180);const retryableStatus=status=>status===408||status===429||status>=500;const transient400=message=>/temporar|try again|busy|rate.?limit|too many|timeout|unavailable|internal/i.test(String(message||''));const capacityMessage=message=>/max requests limit exceeded/i.test(String(message||''));
function capacityCircuitActive(){return Number(globalThis.__BA_UPSTASH_MAX_REQUESTS_UNTIL__||0)>Date.now()}
function markCapacityCircuit(){globalThis.__BA_UPSTASH_MAX_REQUESTS_UNTIL__=Date.now()+CAPACITY_COOLDOWN_MS}
function errorLog(error,{operation,key,status,durationMs,stage}){console.error('[instagram-persistence]',JSON.stringify({operation:operation||'unknown',stage:stage||'command',key:safeKey(key),status:status??null,errorCode:error?.code||'PERSISTENCE_ERROR',errorName:error?.name||'Error',message:String(error?.message||error).slice(0,240),durationMs:Number(durationMs||0)||0}));}
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function command(args,{operation='redis_command',key=null,retries=MAX_RETRIES}={}){if(!persistenceConfigured())return null;if(capacityCircuitActive())throw new PersistenceError('Upstash request quota exhausted',{code:'PERSISTENCE_MAX_REQUESTS_EXCEEDED',operation,key,stage:'capacity',status:400,transient:false});const started=Date.now(),body=JSON.stringify(args);let lastError=null;for(let attempt=0;attempt<=retries;attempt++){try{const response=await fetch(baseUrl,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json','Accept':'application/json'},body,cache:'no-store'});const raw=await response.text();let payload=null;try{payload=raw?JSON.parse(raw):null}catch{}const message=payload?.error?String(payload.error):raw.slice(0,240);if(!response.ok){if(response.status===400&&capacityMessage(message))markCapacityCircuit();const transient=retryableStatus(response.status)||(response.status===400&&transient400(message));const error=new PersistenceError(message||`persistence_http_${response.status}`,{code:capacityMessage(message)?'PERSISTENCE_MAX_REQUESTS_EXCEEDED':`PERSISTENCE_HTTP_${response.status}`,operation,key,status:response.status,stage:'http',durationMs:Date.now()-started,transient});lastError=error;if(transient&&attempt<retries){await sleep(RETRY_BASE_MS*Math.pow(2,attempt)+Math.floor(Math.random()*60));continue;}errorLog(error,{operation,key,status:response.status,durationMs:Date.now()-started,stage:'http'});throw error;}if(payload?.error){const error=new PersistenceError(String(payload.error),{code:'PERSISTENCE_COMMAND_FAILED',operation,key,status:200,stage:'redis',durationMs:Date.now()-started,transient:transient400(payload.error)});lastError=error;if(error.transient&&attempt<retries){await sleep(RETRY_BASE_MS*Math.pow(2,attempt)+Math.floor(Math.random()*60));continue;}errorLog(error,{operation,key,status:200,durationMs:Date.now()-started,stage:'redis'});throw error;}return payload?.result??null;}catch(error){if(error instanceof PersistenceError){lastError=error;if(error.transient&&attempt<retries){await sleep(RETRY_BASE_MS*Math.pow(2,attempt)+Math.floor(Math.random()*60));continue;}throw error;}const wrapped=new PersistenceError(String(error?.message||error),{code:'PERSISTENCE_NETWORK_ERROR',operation,key,stage:'network',durationMs:Date.now()-started,transient:true,cause:error});lastError=wrapped;if(attempt<retries){await sleep(RETRY_BASE_MS*Math.pow(2,attempt)+Math.floor(Math.random()*60));continue;}errorLog(wrapped,{operation,key,status:null,durationMs:Date.now()-started,stage:'network'});throw wrapped;}}throw lastError||new PersistenceError('persistence_command_failed',{operation,key});}
export async function getJson(key){const raw=await command(['GET',key],{operation:'get_json',key});if(raw==null)return null;if(typeof raw!=='string')return raw;try{return JSON.parse(raw)}catch(error){const wrapped=new PersistenceError('Stored JSON is malformed',{code:'PERSISTENCE_PARSE_FAILED',operation:'get_json',key,stage:'parse',cause:error});errorLog(wrapped,{operation:'get_json',key,status:200,durationMs:0,stage:'parse'});throw wrapped;}}
export async function mgetJson(keys){const normalized=(Array.isArray(keys)?keys:[]).map(String).filter(Boolean);if(!normalized.length)return[];const raw=await command(['MGET',...normalized],{operation:'mget_json',key:normalized[0]});const values=Array.isArray(raw)?raw:[];return values.map((value,index)=>{if(value==null)return null;if(typeof value!=='string')return value;try{return JSON.parse(value)}catch(error){const wrapped=new PersistenceError('Stored JSON is malformed',{code:'PERSISTENCE_PARSE_FAILED',operation:'mget_json',key:normalized[index],stage:'parse',cause:error});errorLog(wrapped,{operation:'mget_json',key:normalized[index],status:200,durationMs:0,stage:'parse'});return null;}});}
export async function setJson(key,value){let encoded;try{encoded=JSON.stringify(value);if(encoded===undefined)throw new Error('undefined_value')}catch(error){const wrapped=new PersistenceError(String(error?.message||error),{code:'PERSISTENCE_SERIALIZE_FAILED',operation:'set_json',key,stage:'serialize',cause:error});errorLog(wrapped,{operation:'set_json',key,status:null,durationMs:0,stage:'serialize'});throw wrapped;}await command(['SET',key,encoded],{operation:'set_json',key});return value;}
export async function delKey(key){await command(['DEL',key],{operation:'delete_key',key});}
export async function setAdd(index,id){await command(['SADD',index,id],{operation:'set_add',key:index});}
export async function setRemove(index,id){await command(['SREM',index,id],{operation:'set_remove',key:index});}
export async function setMembers(index){return(await command(['SMEMBERS',index],{operation:'set_members',key:index}))||[];}
export async function sortedAdd(index,score,id){const numeric=Number(score);if(!Number.isFinite(numeric))throw new PersistenceError('Invalid sorted-set score',{code:'PERSISTENCE_INVALID_SCORE',operation:'sorted_add',key:index,stage:'validate'});await command(['ZADD',index,numeric,id],{operation:'sorted_add',key:index});}
export async function sortedRange(index,start=0,stop=19){return(await command(['ZREVRANGE',index,start,stop],{operation:'sorted_range',key:index}))||[];}
export async function sortedRemove(index,id){await command(['ZREM',index,id],{operation:'sorted_remove',key:index});}
export async function listJson(index){const ids=await setMembers(index);if(!ids.length)return[];const values=await mgetJson(ids);const rows=[];for(let i=0;i<values.length;i++)if(values[i])rows.push(values[i]);return rows.sort((a,b)=>String(b.updatedAt||b.createdAt||'').localeCompare(String(a.updatedAt||a.createdAt||'')));}
export async function upsertIndexed(index,itemKey,item){await setJson(itemKey,item);try{await setAdd(index,itemKey)}catch(error){console.error('[instagram-persistence]',JSON.stringify({operation:'index_add',stage:'repair_needed',key:itemKey,status:error?.status??null,errorCode:error?.code||'PERSISTENCE_ERROR',message:String(error?.message||error).slice(0,240)}));throw new PersistenceError('QUEUE_INDEX_WRITE_FAILED',{code:'QUEUE_INDEX_WRITE_FAILED',operation:'upsert_indexed',key:itemKey,stage:'index',cause:error});}return item;}
export async function removeIndexed(index,itemKey){await setRemove(index,itemKey);await delKey(itemKey);}
export async function acquireLock(key,tokenValue,ttlSeconds=120){if(!persistenceConfigured())return false;if(capacityCircuitActive())throw new PersistenceError('Upstash request quota exhausted',{code:'PERSISTENCE_MAX_REQUESTS_EXCEEDED',operation:'lock_acquire',key,stage:'capacity',status:400});const result=await command(['SET',key,tokenValue,'NX','EX',ttlSeconds],{operation:'lock_acquire',key});if(result==='OK'&&key==='ba:social:instagram:prepare:lock'&&typeof globalThis!=='undefined')globalThis.__BA_INSTAGRAM_PREPARE_ACTIVE__=true;return result==='OK';}
export async function releaseLock(key,tokenValue){if(!persistenceConfigured())return false;const current=await command(['GET',key],{operation:'lock_read',key});if(current!==tokenValue)return false;await command(['DEL',key],{operation:'lock_release',key});if(key==='ba:social:instagram:prepare:lock'&&typeof globalThis!=='undefined')globalThis.__BA_INSTAGRAM_PREPARE_ACTIVE__=false;return true;}
