import {randomUUID} from 'node:crypto';
import {getJson,setJson,sortedAdd,sortedRange,persistenceConfigured} from './persistence.js';
const LATEST='ba:pipeline:latest';const RUNS='ba:pipeline:runs';const key=id=>`ba:pipeline:run:${id}`;
export async function startPipelineRun(meta={}){if(!persistenceConfigured())return{id:randomUUID(),persisted:false};const id=meta.id||randomUUID();const now=new Date().toISOString();const run={id,status:'RUNNING',stage:'STARTING',scheduledAt:meta.scheduledAt||now,startedAt:now,updatedAt:now,stages:{},lastError:null,published:0,...meta};await setJson(key(id),run);await setJson(LATEST,run);await sortedAdd(RUNS,Date.now(),id);return{...run,persisted:true}}
export async function updatePipelineRun(id,patch={}){if(!id||!persistenceConfigured())return null;const current=await getJson(key(id));if(!current)return null;const run={...current,...patch,updatedAt:new Date().toISOString()};await setJson(key(id),run);await setJson(LATEST,run);return run}
export async function setPipelineStage(id,stage,startedAt){if(!id||!persistenceConfigured())return;const current=await getJson(key(id));if(!current)return;await updatePipelineRun(id,{status:'RUNNING',stage,stageStartedAt:new Date(startedAt||Date.now()).toISOString()})}
export async function finishPipelineStage(id,stage,startedAt){if(!id||!persistenceConfigured())return;const current=await getJson(key(id));if(!current)return;const stages={...(current.stages||{}),[stage]:{startedAt:new Date(startedAt||Date.now()).toISOString(),durationMs:Date.now()-(startedAt||Date.now())}};await updatePipelineRun(id,{stages})}
export async function completePipelineRun(id,{status='COMPLETED',stage='COMPLETED',published=0,error=null,summary={}}={}){return updatePipelineRun(id,{status,stage,published,lastError:error,finishedAt:new Date().toISOString(),summary})}
export async function getPipelineSnapshot(){if(!persistenceConfigured())return{configured:false,latest:null,runs:[]};const latest=await getJson(LATEST);const ids=await sortedRange(RUNS,0,19);const rows=await Promise.all(ids.map(id=>getJson(key(id))));return{configured:true,latest,runs:rows.filter(Boolean)}}
