import {randomUUID} from 'node:crypto';
import {getJson,msetJson,sortedAdd,sortedRange,persistenceConfigured} from './persistence.js';
const LATEST='ba:pipeline:latest';const RUNS='ba:pipeline:runs';const key=id=>`ba:pipeline:run:${id}`;const runCache=new Map();
async function persistRun(run){await msetJson([[key(run.id),run],[LATEST,run]]);runCache.set(run.id,run);return run}
export async function startPipelineRun(meta={}){if(!persistenceConfigured())return{id:randomUUID(),persisted:false};const id=meta.id||randomUUID();const now=new Date().toISOString();const run={id,status:'RUNNING',stage:'STARTING',scheduledAt:meta.scheduledAt||now,startedAt:now,updatedAt:now,stages:{},lastError:null,published:0,...meta};await persistRun(run);await sortedAdd(RUNS,Date.now(),id);return{...run,persisted:true}}
export async function updatePipelineRun(id,patch={}){if(!id||!persistenceConfigured())return null;const cached=runCache.get(id);const current=cached||await getJson(key(id));if(!current)return null;const run={...current,...patch,updatedAt:new Date().toISOString()};return persistRun(run)}
export async function setPipelineStage(id,stage,startedAt){if(!id||!persistenceConfigured())return;const current=runCache.get(id)||await getJson(key(id));if(!current)return;await persistRun({...current,status:'RUNNING',stage,stageStartedAt:new Date(startedAt||Date.now()).toISOString(),updatedAt:new Date().toISOString()})}
export async function finishPipelineStage(id,stage,startedAt){if(!id)return;const current=runCache.get(id);if(!current)return;const started=Number(startedAt||Date.now());const stages={...(current.stages||{}),[stage]:{startedAt:new Date(started).toISOString(),durationMs:Date.now()-started}};runCache.set(id,{...current,stages,updatedAt:new Date().toISOString()})}
export async function completePipelineRun(id,{status='COMPLETED',stage='COMPLETED',published=0,error=null,summary={}}={}){return updatePipelineRun(id,{status,stage,published,lastError:error,finishedAt:new Date().toISOString(),summary})}
export async function getPipelineSnapshot(){if(!persistenceConfigured())return{configured:false,latest:null,runs:[]};const latest=await getJson(LATEST);const ids=await sortedRange(RUNS,0,19);const rows=await Promise.all(ids.map(id=>getJson(key(id))));return{configured:true,latest,runs:rows.filter(Boolean)}}
