import {sources} from './sources.js';

function clean(value=''){
  return value.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/<[^>]*>/g,' ').replace(/&nbsp;|&#160;/gi,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n))).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCharCode(parseInt(n,16))).replace(/\s+/g,' ').trim();
}
function tag(xml,name){const m=xml.match(new RegExp(`<${name}[^>]*>([\\s\\S]*?)</${name}>`,'i'));return m?clean(m[1]):'';}
function attr(tagText,name){const m=tagText.match(new RegExp(`${name}\\s*=\\s*[\"']([^\"']+)[\"']`,'i'));return m?m[1]:'';}
function resolveImage(value,base){if(!value)return null;try{const u=new URL(value,base);return /^https?:$/.test(u.protocol)?u.href:null;}catch{return null;}}
function rssImage(raw,description,base){const media=(raw.match(/<media:(?:content|thumbnail)\b[^>]*>/i)||raw.match(/<media:group\b[\s\S]*?<\/media:group>/i));if(media){const mediaUrl=attr(media[0],'url');const image=resolveImage(mediaUrl,base);if(image)return image;const nested=media[0].match(/<(?:media:content|media:thumbnail)\b[^>]*>/i);if(nested){const nestedImage=resolveImage(attr(nested[0],'url'),base);if(nestedImage)return nestedImage;}}const enclosure=raw.match(/<enclosure\b[^>]*>/i);if(enclosure&&(!attr(enclosure[0],'type')||/^image\//i.test(attr(enclosure[0],'type')))){const image=resolveImage(attr(enclosure[0],'url'),base);if(image)return image;}const img=description.match(/<img\b[^>]*?(?:src|data-src|data-original)\s*=\s*[\"']([^\"']+)[\"']/i);return img?resolveImage(img[1],base):null;}
function rssItems(xml){return xml.match(/<item\b[\s\S]*?<\/item>/gi)||[];}
function atomItems(xml){return xml.match(/<entry\b[\s\S]*?<\/entry>/gi)||[];}
function atomLink(item){const links=[...item.matchAll(/<link\b([^>]*)\/?>(?:<\/link>)?/gi)];const alternate=links.find(m=>!attr(m[1],'rel')||attr(m[1],'rel').toLowerCase()==='alternate');return alternate?attr(alternate[1],'href')||clean(alternate[0].replace(/<\/?link[^>]*>/gi,'')):'';}
function parseItem(item,source,isAtom=false){const rawDescription=(item.match(/<(?:description|summary|content)\b[^>]*>([\s\S]*?)<\/(?:description|summary|content)>/i)||[])[1]||'';const title=tag(item,'title');const link=isAtom?atomLink(item):tag(item,'link')||attr((item.match(/<link\b[^>]*>/i)||[])[0]||'','href');const publishedAt=tag(item,isAtom?'published':'pubDate')||tag(item,'updated')||tag(item,'dc:date');if(!title||!link)return null;return {title,summary:tag(item,isAtom?'summary':'description'),url:link,publishedAt,sourceId:source.id,publisher:source.publisher,sourceUrl:source.url,sourceName:source.name,category:source.category||'',sourceWeight:Number(source.weight)||1,imageUrl:rssImage(item,rawDescription,link),rawXml:item,rawDescription};}
export async function fetchSource(entry){const source=typeof entry==='string'?{id:entry,publisher:entry,name:entry,url:entry,category:'Nasional',weight:1,enabled:true}:entry;const started=Date.now();try{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),7000);let res;try{res=await fetch(source.url,{signal:controller.signal,headers:{'user-agent':'BeritaAuto/1.2 (+https://berita-auto.vercel.app)','accept':'application/rss+xml, application/atom+xml, application/xml, text/xml;q=0.9, */*;q=0.1'}});}finally{clearTimeout(timer);}if(!res.ok)throw new Error(`HTTP ${res.status}`);const xml=await res.text();const isAtom=/<feed\b/i.test(xml)&&!/<rss\b/i.test(xml);const rawItems=isAtom?atomItems(xml):rssItems(xml);const parsed=rawItems.map(item=>parseItem(item,source,isAtom)).filter(Boolean);return {source,items:parsed,durationMs:Date.now()-started,error:null};}catch(error){return {source,items:[],durationMs:Date.now()-started,error:String(error?.message||error)};}}
export async function fetchNews(){const results=await Promise.allSettled(sources.map(fetchSource));const out=[];let succeeded=0;let failed=0;for(const settled of results){const result=settled.status==='fulfilled'?settled.value:{source:{publisher:'unknown',name:'unknown'},items:[],durationMs:0,error:String(settled.reason||'unknown')};if(result.error){failed++;console.error(`[source] publisher=${result.source.publisher} fetched=0 failed=${result.error} duration=${result.durationMs}ms`);continue;}succeeded++;out.push(...result.items);const withImage=result.items.filter(item=>/^https?:\/\//.test(String(item.imageUrl||''))).length;console.log(`[source] publisher=${result.source.publisher} fetched=${result.items.length} withImage=${withImage} withoutImage=${Math.max(0,result.items.length-withImage)} coverage=${result.items.length?Math.round(withImage/result.items.length*100):0}% duration=${result.durationMs}ms`);}console.log(`[source-summary] checked=${sources.length} succeeded=${succeeded} failed=${failed} items=${out.length} withImage=${out.filter(item=>item.imageUrl).length} withoutImage=${out.filter(item=>!item.imageUrl).length}`);return {items:out,sourceStats:{checked:sources.length,succeeded,failed,itemsFetched:out.length,withImage:out.filter(item=>item.imageUrl).length,withoutImage:out.filter(item=>!item.imageUrl).length}};}
