import {getJson,setJson,sortedAdd,sortedRange,sortedRemove} from './persistence.js';

export const SOCIAL_QUEUE_KEY='ba:social:instagram:queue';
export const SOCIAL_PUBLISHED_INDEX='ba:social:instagram:published-index';
export const SOCIAL_LAST_PUBLISHED='ba:social:instagram:last-published-at';
export const SOCIAL_LOCK_KEY='ba:social:publish-lock';
export const SOCIAL_LOCK_TTL=600;

export function shouldSkipCooldown(lastPublishedAt,now,minIntervalMinutes){return Boolean(lastPublishedAt&&now-Date.parse(lastPublishedAt)<minIntervalMinutes*60000);}
export function shouldSkipDailyLimit(count,maxPostsPerDay){return Number(count)>=Number(maxPostsPerDay);}
export function shouldSkipMetaBuffer(usage,buffer){return Boolean(usage?.available&&Number(usage.remaining)<=Number(buffer));}
export function socialConfig(){const n=(name,fallback)=>{const v=Number(process.env[name]);return Number.isFinite(v)&&v>=0?v:fallback;};return{minIntervalMinutes:n('INSTAGRAM_MIN_INTERVAL_MINUTES',3),maxPostsPerDay:n('INSTAGRAM_MAX_POSTS_PER_DAY',50),limitBuffer:n('INSTAGRAM_PUBLISHING_LIMIT_BUFFER',10)};}
export function dailyKey(now=Date.now()){const date=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(now));return `ba:social:instagram:daily:${date}`;}
export function articlePath(article){return `/berita/${article?.slug||article?.id||''}`;}
function clean(value){return String(value||'').replace(/\s+/g,' ').trim();}
function words(value){return new Set(clean(value).toLowerCase().replace(/[^\p{L}\p{N}\s-]/gu,' ').split(/\s+/).filter(w=>w.length>2));}
export function titleSimilarity(a,b){const aa=words(a),bb=words(b);if(!aa.size||!bb.size)return 0;let shared=0;for(const word of aa)if(bb.has(word))shared++;return shared/Math.max(aa.size,bb.size);}
export function deterministicCaption(article,siteUrl=process.env.SITE_URL||'https://berita-auto.vercel.app'){const title=clean(article?.title)||'Berita terbaru';const summary=clean(article?.excerpt||article?.summary||'').slice(0,260);const publisher=clean(article?.publisher||article?.sourceName||'Sumber publik');const category=clean(article?.category||'Berita').replace(/[^\p{L}\p{N}]/gu,'');const slug=encodeURIComponent(article?.slug||article?.id||'');const lines=[`📰 ${title}`];if(summary)lines.push('',summary);lines.push('',`Baca selengkapnya: ${siteUrl.replace(/\/$/,'')}${articlePath({...article,slug})}`,'',`Sumber: ${publisher}`,'',`#BeritaAuto #BeritaTerkini #Indonesia #${category||'Berita'}`);return lines.join('\n').slice(0,2200);}
export function scoreSocialArticle(article,{now=Date.now(),recentPublished=[]}={}){const published=Date.parse(article?.sitePublishedAt||article?.createdAt||article?.publishedAt||'');const ageHours=Number.isFinite(published)?Math.max(0,(now-published)/3600000):72;const freshness=Math.max(0,40-Math.min(ageHours,48)*0.8);const sourceWeight=Math.min(15,Math.max(0,Number(article?.sourceWeight)||5));const text=`${article?.title||''} ${article?.excerpt||''}`.toLowerCase();const breaking=/breaking|terkini|gempa|banjir|kecelakaan|putusan|kebijakan|serangan|presiden|pemilu|peringatan|darurat/.test(text)?18:0;const categoryBoost=/nasional|politik|ekonomi|teknologi|olahraga|sains/.test(String(article?.category||'').toLowerCase())?8:3;const repeatedCategory=recentPublished.filter(x=>String(x?.category||'').toLowerCase()===String(article?.category||'').toLowerCase()).length;const similarity=Math.max(0,...recentPublished.map(x=>titleSimilarity(article?.title,x?.title)));return Number((freshness+sourceWeight+breaking+categoryBoost-(repeatedCategory*6)-(similarity*35)).toFixed(3));}
export function selectBestSocialArticle(items,{now=Date.now(),recentPublished=[]}={}){const candidates=(Array.isArray(items)?items:[]).filter(item=>item&&['queued','failed'].includes(item.state||'queued')&&(!item.nextRetryAt||Date.parse(item.nextRetryAt)<=now));if(!candidates.length)return null;const scored=candidates.map(item=>({...item,selectionScore:scoreSocialArticle(item.article||item,{now,recentPublished})})).sort((a,b)=>b.selectionScore-a.selectionScore);if(scored[0].selectionScore<10)return null;return scored[0];}
export function buildEligibleSocialQueue(queue){return(Array.isArray(queue)?queue:[]).filter(item=>item&&['queued','failed'].includes(item.state||'queued')&&item.article?.id&&item.article?.sitePublishedAt&&(!item.nextRetryAt||Date.parse(item.nextRetryAt)<=Date.now()));}
export async function queueSocialArticle(article){if(!article?.id)return{queued:false,reason:'missing_article_id'};const published=await getJson(`ba:social:instagram:published:${article.id}`);if(published)return{queued:false,reason:'already_published'};const key=`ba:social:instagram:item:${article.id}`;const existing=await getJson(key);if(existing?.state==='published')return{queued:false,reason:'already_published'};const now=new Date().toISOString();const item={...(existing||{}),id:article.id,articleId:article.id,platform:'instagram',article,state:'queued',attempts:Number(existing?.attempts)||0,lastError:existing?.lastError||null,createdAt:existing?.createdAt||now,updatedAt:now,nextRetryAt:null};await setJson(key,item);await sortedAdd(SOCIAL_QUEUE_KEY,-Date.parse(item.createdAt),key);return{queued:true,item};}
export async function readSocialQueue(limit=100){const keys=await sortedRange(SOCIAL_QUEUE_KEY,0,Math.max(0,limit-1));const rows=await Promise.all(keys.map(key=>getJson(key)));return rows.filter(Boolean);}
export async function readRecentPublished(limit=20){const keys=await sortedRange(SOCIAL_PUBLISHED_INDEX,0,Math.max(0,limit-1));const rows=await Promise.all(keys.map(key=>getJson(key)));return rows.filter(Boolean);}
export async function getDailyPublishedCount(now=Date.now()){return Number(await getJson(dailyKey(now)))||0;}
export async function incrementDailyPublishedCount(now=Date.now()){const key=dailyKey(now);const value=(Number(await getJson(key))||0)+1;await setJson(key,value);return value;}
export async function getLastPublishedAt(){return await getJson(SOCIAL_LAST_PUBLISHED);}
export async function markSocialProcessing(item,{triggerSource='unknown'}={}){const key=`ba:social:instagram:item:${item.articleId}`;const next={...item,state:'processing',currentStage:'TRIGGER_RECEIVED',triggerSource,attempts:Number(item.attempts||0)+1,updatedAt:new Date().toISOString(),lastError:null};await setJson(key,next);return next;}
export async function markSocialFailure(item,error,{permanent=false,retryAfterMs=0,ambiguous=false}={}){const key=`ba:social:instagram:item:${item.articleId}`;const metaLimit=Number(error?.metaCode)===9&&Number(error?.metaSubcode)===2207042;const effectiveRetryAfterMs=metaLimit?30*60*1000:retryAfterMs;const reason=metaLimit?'meta_publishing_limit':String(error?.reason||error?.message||'instagram_publish_failed').slice(0,300);const next={...item,state:ambiguous?'publish_ambiguous':permanent?'skipped':'failed',currentStage:metaLimit?'META_PUBLISHING_LIMIT':item.currentStage||'FAILED',failureStage:error?.instagramOperation||item.failureStage||null,lastError:reason,retryReason:reason,metaCode:Number(error?.metaCode||0)||null,metaSubcode:Number(error?.metaSubcode||0)||null,updatedAt:new Date().toISOString(),nextRetryAt:ambiguous||permanent?null:new Date(Date.now()+effectiveRetryAfterMs).toISOString()};await setJson(key,next);if(permanent)await sortedRemove(SOCIAL_QUEUE_KEY,key);return next;}
export async function markSocialPublished(item,{mediaId,mediaUrl=null,publishedAt=new Date().toISOString(),publishMode=null}={}){if(!mediaId)throw new Error('instagram_media_id_missing');const key=`ba:social:instagram:item:${item.articleId}`;const previewUrl=item.previewUrl||(Array.isArray(item.cardUrls)?item.cardUrls[0]:null)||null;const article=item.article||{};const record={...item,state:'published',currentStage:'SUCCESS',mediaId:String(mediaId),externalPostId:String(mediaId),externalPostUrl:mediaUrl||item.externalPostUrl||null,publishedAt,updatedAt:publishedAt,nextRetryAt:null,lastError:null,retryReason:null,previewUrl,cardUrls:Array.isArray(item.cardUrls)?item.cardUrls:[],publishMode:publishMode||item.publishMode||(item.carousel?'carousel':'single-image'),articleId:item.articleId,stableId:article.stableId||article.id||item.articleId,title:article.title||item.title||'Berita terbaru',category:article.category||'Berita',triggerSource:item.triggerSource||'unknown',sourceUrl:article.sourceUrl||article.url||item.sourceUrl||null,canonicalUrl:article.canonicalUrl||item.canonicalUrl||null,parentContainerId:item.carousel?item.containerId||null:item.parentContainerId||null};await setJson(key,record);await setJson(`ba:social:instagram:published:${item.articleId}`,record);await sortedAdd(SOCIAL_PUBLISHED_INDEX,Date.parse(publishedAt),key);await sortedRemove(SOCIAL_QUEUE_KEY,key);await setJson(SOCIAL_LAST_PUBLISHED,publishedAt);return record;}
