const clean=value=>{if(value==null)return'';if(typeof value==='string')return value.replace(/\s+/g,' ').trim();if(typeof value==='number'||typeof value==='boolean')return String(value);if(Array.isArray(value))return value.map(clean).filter(Boolean).join(' ').replace(/\s+/g,' ').trim();if(typeof value==='object')return clean(value.text||value.value||value.content||value.title||'');return''};
export function sanitizeCardText(value=''){return clean(value).normalize('NFKC').replace(/[\u0000-\u001f\u007f-\u009f]/g,' ').replace(/[\u200B-\u200D\u2060\uFEFF]/g,'').replace(/[“”„‟«»]/g,'"').replace(/[‘’‚‛]/g,"'").replace(/[–—―]/g,'-').replace(/…/g,'...').replace(/[\p{Extended_Pictographic}\p{Emoji_Presentation}\uFE0F]/gu,'').replace(/[^\p{L}\p{M}\p{N}\s.,!?;:'"()\-/%&@+#=]/gu,' ').replace(/\s+/g,' ').trim()};
const asArray=value=>Array.isArray(value)?value:Array.isArray(value?.items)?value.items:Array.isArray(value?.values)?value.values:[];
const matchesTerm=(text,term)=>term.length<=3?new RegExp(`(?:^|[^\\p{L}\\p{N}])${term.replace(/[.*+?^${}()|[\\]\\\\]/g,'\\\\$&')}(?:$|[^\\p{L}\\p{N}])`,'iu').test(text):text.includes(term);
const words=value=>sanitizeCardText(value).toLowerCase().replace(/[^\p{L}\p{N}\s-]/gu,' ').split(/\s+/).filter(w=>w.length>2);
const unique=items=>[...new Set(asArray(items).filter(Boolean).map(sanitizeCardText).filter(Boolean))];
const CATEGORY_RULES=[['Olahraga',['sepak bola','liga','gol','pemain','atlet','olahraga','pertandingan','tenis','basket','balap']],['Teknologi',['teknologi','ai','artificial intelligence','startup','chip','smartphone','aplikasi','digital','siber','internet']],['Ekonomi',['ekonomi','rupiah','saham','inflasi','bank','investasi','pasar','bisnis','pajak','ekspor','impor']],['Bencana',['gempa','banjir','longsor','erupsi','gunung api','tsunami','cuaca ekstrem','bencana','kebakaran']],['Kriminal',['polisi','kriminal','tersangka','penangkapan','korban','kejahatan','kasus','penembakan','pencurian']],['Politik',['presiden','pemilu','partai','dpr','politik','menteri','kebijakan','pemerintah','pilkada']],['Internasional',['amerika','china','tiongkok','jepang','rusia','ukraina','israel','palestina','dunia','internasional','negara']],['Kesehatan',['kesehatan','dokter','rumah sakit','penyakit','vaksin','obat','pasien','kesehatan masyarakat']],['Sains',['sains','ilmuwan','penelitian','riset','antariksa','nasa','astronomi','penemuan']]];
export function socialVisualProfile(article={}){const text=sanitizeCardText([article?.title,article?.summary,article?.excerpt,article?.content,article?.body,article?.category].map(sanitizeCardText).filter(Boolean));const lower=text.toLowerCase();const matched=CATEGORY_RULES.find(([,terms])=>asArray(terms).some(term=>matchesTerm(lower,term)));const category=matched?.[0]||sanitizeCardText(article?.category)||'Berita';const terms=matched?.[1]||[];const matchedTerms=unique(asArray(terms).filter(term=>matchesTerm(lower,term))).slice(0,3);const named=unique((text.match(/\b[A-ZÀ-Ý][\p{L}.-]{2,}(?:\s+[A-ZÀ-Ý][\p{L}.-]{2,}){0,2}/gu)||[])).filter(x=>!['Berita Auto','Berita Terkini','Sumber'].includes(x)).slice(0,3);const fallback=unique(words(text).filter(w=>w.length>4)).slice(0,4);const keywords=unique([...matchedTerms,...named,...fallback]).slice(0,4);const styles={Olahraga:{accent:'#ef4444',icon:'SPORT'},Teknologi:{accent:'#06b6d4',icon:'TECH'},Ekonomi:{accent:'#16a34a',icon:'ECONOMY'},Bencana:{accent:'#f97316',icon:'ALERT'},Kriminal:{accent:'#7c3aed',icon:'SAFETY'},Politik:{accent:'#2563eb',icon:'POLITIK'},Internasional:{accent:'#0ea5e9',icon:'WORLD'},Kesehatan:{accent:'#e11d48',icon:'HEALTH'},Sains:{accent:'#8b5cf6',icon:'SCIENCE'},Berita:{accent:'#1d4ed8',icon:'NEWS'}};return{category,keywords,style:styles[category]||styles.Berita};}
const trim=(value,max)=>sanitizeCardText(value).slice(0,max).trim();
const sentences=value=>sanitizeCardText(value).split(/(?<=[.!?])\s+/).map(clean).filter(s=>s.length>35);
const estimateLines=(value,charsPerLine)=>{const text=clean(value);if(!text)return 0;return text.split(/\s+/).reduce((lines,word)=>{const current=lines[lines.length-1]||'';if(!current)lines.push(word);else if(`${current} ${word}`.length<=charsPerLine)lines[lines.length-1]=`${current} ${word}`;else lines.push(word);return lines;},[]).length};
function buildFacts(article){const summary=clean(article?.excerpt||article?.summary);const body=clean(article?.content||article?.body||article?.text);const raw=[...sentences(summary),...sentences(body)].filter((item,index,array)=>array.indexOf(item)===index);return raw.filter(item=>!item.toLowerCase().startsWith(clean(article?.title).toLowerCase())).slice(0,10);}
function sourceParagraphs(article){const persisted=asArray(article?.paragraphs).map(clean).filter(Boolean);if(persisted.length)return persisted;const raw=[article?.content,article?.body,article?.text].map(value=>typeof value==='string'?value:'').find(Boolean)||'';const blocks=raw.split(/\n\s*\n|\r\n\s*\r\n/).map(sanitizeCardText).filter(Boolean);if(blocks.length>1)return blocks;return sentences(raw);}
function splitParagraph(paragraph,maxChars){const value=sanitizeCardText(paragraph);if(!value)return[];if(value.length<=maxChars)return[value];const sentenceParts=value.split(/(?<=[.!?])\s+/).filter(Boolean);const chunks=[];let current='';const push=part=>{const next=current?`${current} ${part}`:part;if(next.length<=maxChars){current=next;return;}if(current)chunks.push(current);current=part;};for(const sentence of sentenceParts.length?sentenceParts:[value]){if(sentence.length<=maxChars){push(sentence);continue;}for(const word of sentence.split(/\s+/)){const next=current?`${current} ${word}`:word;if(next.length<=maxChars)current=next;else{if(current)chunks.push(current);current=word;}}}if(current)chunks.push(current);return chunks;}
function paragraphSlides(article){const paragraphs=sourceParagraphs(article);const facts=buildFacts(article);const fallback=clean(article?.excerpt||article?.summary)||facts.join(' ')||'Informasi utama berita.';const maxBodyChars=520;const chunks=paragraphs.flatMap(p=>splitParagraph(p,maxBodyChars)).filter(Boolean);if(!chunks.length)return[trim(fallback,520)];if(chunks.length===1){const extra=facts.find(item=>item.toLowerCase()!==chunks[0].toLowerCase())||clean(article?.excerpt||article?.summary);if(extra&&extra.toLowerCase()!==chunks[0].toLowerCase())return[chunks[0],extra];return[chunks[0]];}return chunks.slice(0,10);}
export function buildInstagramSlides(article={}){const title=trim(article?.title||'Berita terbaru',220);const paragraphs=paragraphSlides(article);const contentLength=clean(article?.content||article?.body||article?.text).length;const totalText=paragraphs.join(' ');const isShort=paragraphs.length<=2&&totalText.length<=700&&title.length<=120&&contentLength<=900;const slides=paragraphs.length>10?paragraphs.slice(0,10):paragraphs;return slides.map((summary,index)=>({title:index===0?title:(index===1?'Poin penting':`Lanjutan ${index}`),summary:trim(summary,index===0?360:760),number:index+1,role:index===0?'cover':index===1?'detail':'context',paragraphIndex:index})).concat(isShort&&slides.length===1?[{title:'Poin penting',summary:trim(factsFallback(article,paragraphs[0]),760),number:2,role:'detail',paragraphIndex:1}]:[]);}
function factsFallback(article,first){const facts=buildFacts(article);const extra=facts.find(item=>item.toLowerCase()!==sanitizeCardText(first).toLowerCase());return extra||sanitizeCardText(article?.excerpt||article?.summary)||'Baca berita selengkapnya untuk konteks lengkap.';}
export const buildSocialSlides=buildInstagramSlides;
export function socialCardText(article,slide=1){const slides=buildInstagramSlides(article);return slides[Math.max(0,Math.min(slides.length-1,Number(slide)-1))];}
