const clean=value=>{if(value==null)return'';if(typeof value==='string')return value.replace(/\s+/g,' ').trim();if(typeof value==='number'||typeof value==='boolean')return String(value);if(Array.isArray(value))return value.map(clean).filter(Boolean).join(' ').replace(/\s+/g,' ').trim();if(typeof value==='object')return clean(value.text||value.value||value.content||value.title||'');return''};
export function sanitizeCardText(value=''){return clean(value).normalize('NFKC').replace(/[\u0000-\u001f\u007f-\u009f]/g,' ').replace(/[\u200B-\u200D\u2060\uFEFF]/g,'').replace(/[“”„‟«»]/g,'"').replace(/[‘’‚‛]/g,"'").replace(/[–—―]/g,'-').replace(/…/g,'...').replace(/[\p{Extended_Pictographic}\p{Emoji_Presentation}\uFE0F]/gu,'').replace(/[^\p{L}\p{M}\p{N}\s.,!?;:'"()\-/%&@+#=]/gu,' ').replace(/\s+/g,' ').trim()};
const asArray=value=>Array.isArray(value)?value:Array.isArray(value?.items)?value.items:Array.isArray(value?.values)?value.values:[];
const matchesTerm=(text,term)=>term.length<=3?new RegExp(`(?:^|[^\\p{L}\\p{N}])${term.replace(/[.*+?^${}()|[\\]\\\\]/g,'\\\\$&')}(?:$|[^\\p{L}\\p{N}])`,'iu').test(text):text.includes(term);
const words=value=>sanitizeCardText(value).toLowerCase().replace(/[^\p{L}\p{N}\s-]/gu,' ').split(/\s+/).filter(w=>w.length>2);
const unique=items=>[...new Set(asArray(items).filter(Boolean).map(sanitizeCardText).filter(Boolean))];
const CATEGORY_RULES=[['Olahraga',['sepak bola','liga','gol','pemain','atlet','olahraga','pertandingan','tenis','basket','balap']],['Teknologi',['teknologi','ai','artificial intelligence','startup','chip','smartphone','aplikasi','digital','siber','internet']],['Ekonomi',['ekonomi','rupiah','saham','inflasi','bank','investasi','pasar','bisnis','pajak','ekspor','impor']],['Bencana',['gempa','banjir','longsor','erupsi','gunung api','tsunami','cuaca ekstrem','bencana','kebakaran']],['Kriminal',['polisi','kriminal','tersangka','penangkapan','korban','kejahatan','kasus','penembakan','pencurian']],['Politik',['presiden','pemilu','partai','dpr','politik','menteri','kebijakan','pemerintah','pilkada']],['Internasional',['amerika','china','tiongkok','jepang','rusia','ukraina','israel','palestina','dunia','internasional','negara']],['Kesehatan',['kesehatan','dokter','rumah sakit','penyakit','vaksin','obat','pasien','kesehatan masyarakat']],['Sains',['sains','ilmuwan','penelitian','riset','antariksa','nasa','astronomi','penemuan']]];
export function socialVisualProfile(article={}){const text=sanitizeCardText([article?.title,article?.summary,article?.excerpt,article?.content,article?.body,article?.category].map(sanitizeCardText).filter(Boolean));const lower=text.toLowerCase();const matched=CATEGORY_RULES.find(([,terms])=>asArray(terms).some(term=>matchesTerm(lower,term)));const category=matched?.[0]||sanitizeCardText(article?.category)||'Berita';const terms=matched?.[1]||[];const matchedTerms=unique(asArray(terms).filter(term=>matchesTerm(lower,term))).slice(0,3);const named=unique((text.match(/\b[A-ZÀ-Ý][\p{L}.-]{2,}(?:\s+[A-ZÀ-Ý][\p{L}.-]{2,}){0,2}/gu)||[])).filter(x=>!['Berita Auto','Berita Terkini','Sumber'].includes(x)).slice(0,3);const fallback=unique(words(text).filter(w=>w.length>4)).slice(0,4);const keywords=unique([...matchedTerms,...named,...fallback]).slice(0,4);const styles={Olahraga:{accent:'#ef4444',icon:'SPORT'},Teknologi:{accent:'#06b6d4',icon:'TECH'},Ekonomi:{accent:'#16a34a',icon:'ECONOMY'},Bencana:{accent:'#f97316',icon:'ALERT'},Kriminal:{accent:'#7c3aed',icon:'SAFETY'},Politik:{accent:'#2563eb',icon:'POLITIK'},Internasional:{accent:'#0ea5e9',icon:'WORLD'},Kesehatan:{accent:'#e11d48',icon:'HEALTH'},Sains:{accent:'#8b5cf6',icon:'SCIENCE'},Berita:{accent:'#1d4ed8',icon:'NEWS'}};return{category,keywords,style:styles[category]||styles.Berita};}
const trim=(value,max)=>sanitizeCardText(value).slice(0,max).trim();
const sentences=value=>sanitizeCardText(value).split(/(?<=[.!?])\s+/).map(clean).filter(s=>s.length>35);
const estimateLines=(value,charsPerLine)=>{const text=clean(value);if(!text)return 0;return text.split(/\s+/).reduce((lines,word)=>{const current=lines[lines.length-1]||'';if(!current)lines.push(word);else if(`${current} ${word}`.length<=charsPerLine)lines[lines.length-1]=`${current} ${word}`;else lines.push(word);return lines;},[]).length};
function buildFacts(article){const summary=clean(article?.excerpt||article?.summary);const body=clean(article?.content||article?.body||article?.text);const raw=[...sentences(summary),...sentences(body)].filter((item,index,array)=>array.indexOf(item)===index);return raw.filter(item=>!item.toLowerCase().startsWith(clean(article?.title).toLowerCase())).slice(0,10);}
export function buildInstagramSlides(article={}){const title=trim(article?.title||'Berita terbaru',220);const summary=trim(article?.excerpt||article?.summary||'',520);const facts=buildFacts(article);const baseDetail=summary&&summary.toLowerCase()!==title.toLowerCase()?summary:'';const firstFacts=facts.slice(0,4);const remainingFacts=facts.slice(4);const detail=[baseDetail,...firstFacts].filter(Boolean).join(' ');const detailLines=estimateLines(detail,54);const longContent=title.length>120||detailLines>8||facts.length>5||clean(article?.content||article?.body||'').length>1100;const slide1={title,summary:trim(summary||firstFacts[0]||'',360),number:1,role:'cover'};if(!longContent){return[slide1,{title:'Poin penting',summary:trim(detail||summary||'Informasi utama berita.',760),number:2,role:'detail'}];}const slide2Facts=[baseDetail,...firstFacts.slice(0,3)].filter(Boolean).join(' ');const slide3Facts=[...firstFacts.slice(3),...remainingFacts].filter(Boolean).join(' ');return[slide1,{title:'Poin penting',summary:trim(slide2Facts||detail,680),number:2,role:'detail'},{title:'Konteks lanjutan',summary:trim(slide3Facts||'Informasi tambahan berita.',760),number:3,role:'context'}];}
export const buildSocialSlides=buildInstagramSlides;
export function socialCardText(article,slide=1){const slides=buildInstagramSlides(article);return slides[Math.max(0,Math.min(slides.length-1,Number(slide)-1))];}
