const clean=value=>String(value??'').trim();
const absolute=(value,base)=>{const raw=clean(value).replace(/&amp;/g,'&').replace(/\\/g,'/');if(!raw)return null;try{return new URL(raw,base||undefined).toString();}catch{return null;}};
const decodeUrl=value=>{try{return decodeURIComponent(value);}catch{return value;}};
const push=(list,url,provenance,priority)=>{const resolved=absolute(decodeUrl(url),list.baseUrl);if(!resolved||!(resolved.startsWith('http://')||resolved.startsWith('https://')))return;const key=resolved.replace(/#.*$/,'');if(list.seen.has(key))return;list.seen.add(key);list.items.push({url:key,provenance,priority});};
const imageFields=['imageUrl','image','primaryImage','featuredImage','leadImage','heroImage','imageSourceUrl','imageOriginUrl','ogImage','twitterImage','articleImage'];
function valueUrl(value){if(typeof value==='string')return value;if(Array.isArray(value))return value[0];if(value&&typeof value==='object')return value.url||value.src||value.href||value.contentUrl||value.image||value.imageUrl||null;return null;}
function addArticleFields(article,list){for(const field of imageFields){const value=valueUrl(article?.[field]);if(value)push(list,value,'ARTICLE_PRIMARY_IMAGE',0);}for(const field of ['media','mediaContent','mediaContents','enclosure','enclosures','attachments','images']){const values=Array.isArray(article?.[field])?article[field]:[article?.[field]];for(const value of values){const url=valueUrl(value);if(url)push(list,url,'RSS_IMAGE',7);}}}
function metaImages(html,list){const metaRe=/<meta\b[^>]*(?:property|name)\s*=\s*["']([^"']+)["'][^>]*content\s*=\s*["']([^"']+)["'][^>]*>/gi;let match;while((match=metaRe.exec(html||''))){const name=match[1].toLowerCase();if(name==='og:image')push(list,match[2],'OG_IMAGE',1);else if(name==='twitter:image'||name==='twitter:image:src')push(list,match[2],'TWITTER_IMAGE',2);else if(/image|thumbnail|featured/.test(name))push(list,match[2],'ARTICLE_METADATA_IMAGE',4);}}
function jsonLdImages(html,list){const scripts=[...(html||'').matchAll(/<script\b[^>]*type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)];const visit=value=>{if(!value)return;if(typeof value==='string'){const url=valueUrl(value);if(url)push(list,url,'SCHEMA_IMAGE',3);return;}if(Array.isArray(value)){for(const item of value)visit(item);return;}if(typeof value==='object'){for(const key of ['image','thumbnailUrl','contentUrl'])if(value[key]){const v=valueUrl(value[key]);if(v)push(list,v,'SCHEMA_IMAGE',3);}for(const key of ['@graph','mainEntity','mainEntityOfPage','itemListElement'])if(value[key]&&typeof value[key]==='object')visit(value[key]);}};for(const script of scripts){try{visit(JSON.parse(script[1]));}catch{}}}
function bodyImages(html,list){const imgRe=/<img\b[^>]*(?:src|data-src|data-original|data-lazy-src)\s*=\s*["']([^"']+)["'][^>]*>/gi;let match;let count=0;while((match=imgRe.exec(html||''))&&count<12){push(list,match[1],'BODY_IMAGE',5);count++;}const sourceRe=/<(?:source|video)\b[^>]*(?:src|poster)\s*=\s*["']([^"']+)["'][^>]*>/gi;while((match=sourceRe.exec(html||''))&&count<16){push(list,match[1],'BODY_IMAGE',5);count++;}}
function rssImages(html,list){const patterns=[/<(?:media:content|media:thumbnail|enclosure)\b[^>]*url\s*=\s*["']([^"']+)["'][^>]*>/gi,/<enclosure\b[^>]*href\s*=\s*["']([^"']+)["'][^>]*>/gi];for(const re of patterns){let match;while((match=re.exec(html||'')))push(list,match[1],'RSS_IMAGE',7);}}
export function discoverImageSources(article={},html='',baseUrl=''){const list={items:[],seen:new Set(),baseUrl:baseUrl||article?.sourceUrl||article?.canonicalUrl||''};addArticleFields(article,list);metaImages(html,list);jsonLdImages(html,list);bodyImages(html,list);rssImages(html,list);return list.items.sort((a,b)=>a.priority-b.priority);}
export async function fetchValidatedImage(url,{fetchImpl=fetch,timeoutMs=3000}={}){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeoutMs);const started=Date.now();try{const response=await fetchImpl(url,{method:'GET',headers:{Accept:'image/avif,image/webp,image/jpeg,image/png'},signal:controller.signal,cache:'force-cache',redirect:'follow'});const contentType=clean(response.headers.get('content-type')).toLowerCase().split(';')[0];if(response.status===403)throw Object.assign(new Error('ARTICLE_IMAGE_403'),{code:'ARTICLE_IMAGE_403'});if(response.status===404)throw Object.assign(new Error('ARTICLE_IMAGE_NOT_FOUND'),{code:'ARTICLE_IMAGE_NOT_FOUND'});if(response.status>=500)throw Object.assign(new Error(`ARTICLE_IMAGE_${response.status}`),{code:'ARTICLE_IMAGE_5XX'});if(!response.ok)throw Object.assign(new Error(`ARTICLE_IMAGE_HTTP_${response.status}`),{code:'ARTICLE_IMAGE_FETCH_FAILED'});if(!contentType.startsWith('image/'))throw Object.assign(new Error('ARTICLE_IMAGE_CONTENT_TYPE_INVALID'),{code:'ARTICLE_IMAGE_CONTENT_TYPE_INVALID'});const bytes=Buffer.from(await response.arrayBuffer());if(!bytes.length)throw Object.assign(new Error('ARTICLE_IMAGE_EMPTY'),{code:'ARTICLE_IMAGE_EMPTY'});const sharp=(await import('sharp')).default;const metadata=await sharp(bytes).metadata();if(!metadata.width||!metadata.height||!metadata.format)throw Object.assign(new Error('ARTICLE_IMAGE_DECODE_FAILED'),{code:'ARTICLE_IMAGE_DECODE_FAILED'});if(metadata.width<120||metadata.height<120)throw Object.assign(new Error('ARTICLE_IMAGE_DIMENSION_INVALID'),{code:'ARTICLE_IMAGE_DIMENSION_INVALID'});return{ok:true,url:response.url||url,contentType,width:metadata.width,height:metadata.height,format:String(metadata.format),bytes:bytes.length,fetchMs:Date.now()-started};}catch(error){const code=error?.name==='AbortError'?'ARTICLE_IMAGE_FETCH_TIMEOUT':String(error?.code||error?.message||'ARTICLE_IMAGE_FETCH_FAILED');return{ok:false,url,errorCode:code,fetchMs:Date.now()-started};}finally{clearTimeout(timer);}}
export async function findBestArticleImage(article,{html='',baseUrl='',fetchImpl=fetch,timeoutMs=3000}={}){const candidates=discoverImageSources(article,html,baseUrl);const failures=[];for(const candidate of candidates){const result=await fetchValidatedImage(candidate.url,{fetchImpl,timeoutMs});if(result.ok)return{status:'ORIGINAL',provenance:candidate.provenance,url:result.url,sourceUrl:candidate.url,...result,candidatesTried:failures.length+1,failures};failures.push({provenance:candidate.provenance,url:candidate.url,reason:result.errorCode});}return{status:'FALLBACK_USED',provenance:'FALLBACK',url:null,candidatesTried:candidates.length,failures};}
