import {readFile,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {slugify} from './article-url.js';
import {persistenceConfigured,getJson,setJson} from './persistence.js';
import {queueSocialArticle} from './social.js';
const articlesPath=join(process.cwd(),'data','articles.json');const historicalRecoveryPath=join(process.cwd(),'data','historical-published-recovery.json');const pendingPath=join(process.cwd(),'data','pending-articles.json');const apiBase='https://api.github.com/repos/projectdaaw-bot/berita-auto/contents/data/';const ARTICLES_KEY='ba:news:articles';const PENDING_KEY='ba:news:pending';const buildPhase=process.env.NEXT_PHASE==='phase-production-build';const CACHE_TTL_MS=Math.max(5000,Math.min(20000,Number(process.env.ARTICLES_READ_CACHE_TTL_MS||10000)));let articleCache=null;let articleCacheExpiresAt=0;let articleReadInFlight=null;
function normalizeParaphraseStatus(article){if(!article||typeof article!=='object')return article;if(article.paraphraseStatus)return article;const provider=String(article.generationProvider||'').trim().toLowerCase();if(!provider)return article;return {...article,paraphraseStatus:provider==='fallback'?'fallback':'success'}}
const hydrate=a=>Array.isArray(a)?a.map(x=>{const row=x?.slug?x:{...x,slug:slugify(x?.title||'artikel')};return normalizeParaphraseStatus(row)}):[];
async function readJson(path,fallback=[]){try{return hydrate(JSON.parse(await readFile(path,'utf8')))}catch{return fallback}}
async function readRemote(name){const response=await fetch(`${apiBase}${name}?ref=feature%2Fauto-news-mvp`,{cache:'no-store',redirect:'follow',headers:{accept:'application/vnd.github+json','cache-control':'no-cache'}});if(!response.ok)throw new Error(`remote_${name}_api_${response.status}`);const payload=await response.json();if(payload.encoding!=='base64'||!payload.content)throw new Error(`remote_${name}_invalid_api_payload`);return hydrate(JSON.parse(Buffer.from(payload.content,'base64').toString('utf8')))}
async function loadArticlesFallback(){try{return await readRemote('articles.json')}catch(error){console.warn('[storage]',JSON.stringify({operation:'remote_article_fallback',label:'articles',errorCode:'REMOTE_ARTICLES_READ_FAILED',message:String(error?.message||error).slice(0,240)}));return readJson(articlesPath,[])}}
async function ensurePersistent(key,loader,label){let current=null;try{current=await getJson(key)}catch(error){console.warn('[storage]',JSON.stringify({operation:'read_persistent',key,label,errorCode:error?.code||'PERSISTENCE_ERROR',message:String(error?.message||error).slice(0,240)}))}if(current!==null)return hydrate(current);const imported=hydrate(await loader());const quotaExhausted=Number(globalThis.__BA_UPSTASH_MAX_REQUESTS_UNTIL__||0)>Date.now();if(quotaExhausted){console.warn('[storage]',JSON.stringify({operation:'migrate_persistent',key,label,errorCode:'UPSTASH_QUOTA_EXCEEDED',message:'Skipped write-back while Upstash request quota is exhausted'}))}else{try{await setJson(key,imported);console.log(`[storage] migrated ${label} count=${imported.length}`)}catch(error){console.warn('[storage]',JSON.stringify({operation:'migrate_persistent',key,label,errorCode:error?.code||'PERSISTENCE_WRITE_FAILED',message:String(error?.message||error).slice(0,240)}))}}return imported}
export async function readArticles({fresh=false}={}){const now=Date.now();if(!fresh&&articleCache&&articleCacheExpiresAt>now)return articleCache;if(!fresh&&articleReadInFlight)return articleReadInFlight;articleReadInFlight=(async()=>{const value=persistenceConfigured()?await ensurePersistent(ARTICLES_KEY,loadArticlesFallback,'articles'):process.env.VERCEL&&!buildPhase?await Promise.reject(new Error('persistent_database_not_configured_for_production')):await readJson(articlesPath,[]);articleCache=hydrate(value);articleCacheExpiresAt=Date.now()+CACHE_TTL_MS;return articleCache})();try{return await articleReadInFlight}finally{articleReadInFlight=null}}
export function invalidateArticlesCache(){articleCache=null;articleCacheExpiresAt=0}
async function queueSocialNonBlocking(items){const candidates=items.filter(item=>item?.id&&item?.sitePublishedAt).slice(0,100);const results=await Promise.allSettled(candidates.map(queueSocialArticle));const failed=results.filter(x=>x.status==='rejected');if(failed.length)console.warn(`[social] queue_noncritical_failures=${failed.length}`)}
export function mergeDurableArticles(previous=[],incoming=[]){const existing=hydrate(previous),next=hydrate(incoming),byId=new Map(existing.filter(item=>item?.id).map(item=>[item.id,item]));for(const item of next){if(!item?.id)continue;const prior=byId.get(item.id);byId.set(item.id,prior?{...prior,...item}:item)}return [...byId.values()].map(normalizeParaphraseStatus)}
export async function readHistoricalRecovery(){return readJson(historicalRecoveryPath,[])}
export async function recoverHistoricalPublishedArticles(current=[]){const recovery=await readHistoricalRecovery();if(!recovery.length)return{articles:current,recovered:0};const currentIds=new Set(current.map(item=>item?.id).filter(Boolean));const merged=mergeDurableArticles(current,recovery);const recovered=merged.filter(item=>item?.id&&!currentIds.has(item.id)&&recovery.some(row=>row?.id===item.id));if(!recovered.length)return{articles:current,recovered:0};if(persistenceConfigured()){try{await setJson(ARTICLES_KEY,merged);invalidateArticlesCache()}catch(error){console.warn('[storage-recovery]',String(error?.message||error).slice(0,240))}}else await writeFile(articlesPath,JSON.stringify(merged,null,2)+'\n','utf8');console.log(`[storage-recovery] recovered=${recovered.length} ids=${recovered.map(item=>item.id).join(',')}`);return{articles:merged,recovered:recovered.length}}
export async function writeArticles(items){const normalized=hydrate(items);if(persistenceConfigured()){let previous=[];try{previous=hydrate((await getJson(ARTICLES_KEY))||[])}catch(error){console.error('[storage]',JSON.stringify({operation:'write_articles_read',errorCode:error?.code||'PERSISTENCE_READ_FAILED',message:String(error?.message||error).slice(0,240)}));throw error}const durable=mergeDurableArticles(previous,normalized);await setJson(ARTICLES_KEY,durable);invalidateArticlesCache();const previousIds=new Set(previous.map(item=>item?.id).filter(Boolean));await queueSocialNonBlocking(durable.filter(item=>item?.id&&!previousIds.has(item.id)));return durable}const previous=await readJson(articlesPath,[]);const durable=mergeDurableArticles(previous,normalized);await writeFile(articlesPath,JSON.stringify(durable,null,2)+'\n','utf8');invalidateArticlesCache();return durable}
export async function readPending(){if(persistenceConfigured())return ensurePersistent(PENDING_KEY,async()=>process.env.VERCEL?readRemote('pending-articles.json'):readJson(pendingPath),'pending');if(process.env.VERCEL&&!buildPhase)throw new Error('persistent_database_not_configured_for_production');return readJson(pendingPath)}
export async function writePending(items){const normalized=Array.isArray(items)?items:[];if(persistenceConfigured()){await setJson(PENDING_KEY,normalized);return normalized}await writeFile(pendingPath,JSON.stringify(normalized,null,2)+'\n','utf8');return normalized}
