import {acquireLock,releaseLock} from './persistence.js';
import {readArticles} from './storage.js';
import {listAllArticles} from './article-storage.js';
import {getAnalyticsSummary} from './analytics.js';
import {getPipelineSnapshot} from './pipeline.js';
import {instagramConfig} from './instagram.js';
import {readRecentPublished} from './social.js';
import {readSocialRuns} from './social-telemetry.js';

const TELEGRAM_API='https://api.telegram.org';
const HOURLY_TTL_SECONDS=2*60*60;
const PUBLICATION_TTL_SECONDS=7*24*60*60;

export function telegramConfigured(){return Boolean(process.env.TELEGRAM_BOT_TOKEN&&process.env.TELEGRAM_CHAT_ID);}
function escapeHtml(value){return String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;');}
function safeError(error){return String(error?.message||error||'telegram_error').replace(/bot\S+/gi,'bot[redacted]').slice(0,240);}
function wibParts(date=new Date()){const parts=new Intl.DateTimeFormat('id-ID',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(date);const get=k=>parts.find(x=>x.type===k)?.value||'';return{date:`${get('day')} ${new Intl.DateTimeFormat('id-ID',{timeZone:'Asia/Jakarta',month:'long'}).format(date)} ${get('year')}`,time:`${get('hour')}:${get('minute')}`,hourKey:`${get('year')}-${get('month')}-${get('day')}-${get('hour')}`};}
async function telegramRequest(method,payload={}){if(!telegramConfigured())throw new Error('telegram_not_configured');const token=process.env.TELEGRAM_BOT_TOKEN;const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),10000);try{const response=await fetch(`${TELEGRAM_API}/bot${token}/${method}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),signal:controller.signal,cache:'no-store'});let body=null;try{body=await response.json()}catch{}if(!response.ok||body?.ok!==true)throw new Error(`telegram_${method}_failed_http_${response.status}${body?.description?`_${String(body.description).slice(0,160)}`:''}`);return body.result;}catch(error){if(error?.name==='AbortError')throw new Error(`telegram_${method}_timeout`);throw error;}finally{clearTimeout(timer)}}
export async function sendTelegramMessage(text,{disableWebPagePreview=true}={}){return telegramRequest('sendMessage',{chat_id:process.env.TELEGRAM_CHAT_ID,text:String(text).slice(0,4096),parse_mode:'HTML',link_preview_options:disableWebPagePreview?{is_disabled:true}:undefined});}
async function acquireNotificationKey(key,ttl){const token=`telegram:${Date.now()}:${Math.random().toString(36).slice(2,8)}`;return (await acquireLock(key,token,ttl))?token:null;}
function articleUrl(article){const site=String(process.env.SITE_URL||'https://berita-auto.vercel.app').replace(/\/$/,'');return `${site}/berita/${encodeURIComponent(article?.slug||article?.id||'')}`;}
function formatNumber(value){return Number.isFinite(Number(value))?Number(value).toLocaleString('id-ID'):'NOT AVAILABLE';}
async function fetchInstagramJson(path){const c=instagramConfig();if(!c.enabled||!c.userId||!c.accessToken)return{available:false,reason:'Instagram integration is not configured'};const response=await fetch(`https://graph.instagram.com/${c.apiVersion}/${path.replace(/^\//,'')}`,{headers:{Authorization:`Bearer ${c.accessToken}`,Accept:'application/json'},cache:'no-store'});let body=null;try{body=await response.json()}catch{}if(!response.ok||body?.error)throw new Error(String(body?.error?.message||`http_${response.status}`).slice(0,240));return body;}
async function getInstagramMetrics(published){const c=instagramConfig();if(!c.enabled||!c.userId||!c.accessToken)return{posts:published.length,views:null,followers:null,viewsReason:'Instagram integration is not configured',followersReason:'Instagram integration is not configured'};let followers=null,followersReason=null;try{const account=await fetchInstagramJson(`${c.userId}?fields=followers_count`);followers=Number.isFinite(Number(account?.followers_count))?Number(account.followers_count):null;if(followers===null)followersReason='followers_count was not returned by the current Instagram API response';}catch(error){followersReason=safeError(error)}
 const mediaIds=published.map(x=>x?.externalPostId).filter(Boolean);if(!mediaIds.length)return{posts:published.length,views:0,followers,followersReason,viewsReason:null};const values=[];let viewsReason=null;for(const mediaId of mediaIds.slice(0,100)){try{const insight=await fetchInstagramJson(`${mediaId}/insights?metric=views`);const row=Array.isArray(insight?.data)?insight.data.find(x=>x?.name==='views')||insight.data[0]:null;const value=Number(row?.values?.at?.(-1)?.value??row?.value);if(Number.isFinite(value))values.push(value);else throw new Error('views metric missing');}catch(error){viewsReason=safeError(error);break;}}
 if(mediaIds.length>100&&!viewsReason)viewsReason='More than 100 published media records exist; no aggregate lifetime media-view source is available in the current integration';return{posts:published.length,views:viewsReason?null:values.reduce((sum,value)=>sum+value,0),followers,followersReason,viewsReason};}
function articleCreatedInWindow(article,start,end){const content=String(article?.content||'').trim();const status=String(article?.status||'').toUpperCase();if(!content||!['PUBLISHED','NEEDS_REVIEW','DRAFT'].includes(status))return false;const t=Date.parse(article?.createdAt||'');return Number.isFinite(t)&&t>=start&&t<end;}
function articlePublishedInWindow(article,start,end){const t=Date.parse(article?.publishedAt||'');return String(article?.status||'').toUpperCase()==='PUBLISHED'&&Number.isFinite(t)&&t>=start&&t<end;}
async function getArticleHourlyMetrics(start,end){const rows=await listAllArticles();const articlePublished=rows.filter(a=>String(a?.status||'').toUpperCase()==='PUBLISHED').length;const articleNeedsReview=rows.filter(a=>String(a?.status||'').toUpperCase()==='NEEDS_REVIEW').length;return{articleTotal:rows.length,articlePublished,articleNeedsReview,articleCreatedRecentHour:rows.filter(a=>articleCreatedInWindow(a,start,end)).length,articlePublishedRecentHour:rows.filter(a=>articlePublishedInWindow(a,start,end)).length};}
export async function getHourlyReportData(now=Date.now()){
 const date=new Date(now);const {date:dateLabel,time,hourKey}=wibParts(date);const articles=await readArticles();const published=articles.filter(a=>a?.publishStatus!=='rejected'&&a?.sitePublishedAt);const currentHourStart=Date.parse(new Date(date.getTime()-date.getMinutes()*60000-date.getSeconds()*1000-date.getMilliseconds()).toISOString());const previousHourStart=currentHourStart-60*60*1000;const recentCount=published.filter(a=>{const t=Date.parse(a.sitePublishedAt||'');return Number.isFinite(t)&&t>=previousHourStart&&t<currentHourStart}).length;const articleMetrics=await getArticleHourlyMetrics(previousHourStart,currentHourStart);const analytics=await getAnalyticsSummary(articles);const socialPublished=await readRecentPublished(1000);const instagram=await getInstagramMetrics(socialPublished);const pipeline=await getPipelineSnapshot();const socialRuns=await readSocialRuns(20);const latestPipeline=pipeline?.runs?.[0]||null;const latestSocial=socialRuns?.[0]||null;const publicationStatus=latestPipeline?.status==='COMPLETED'?'ACTIVE':latestPipeline?.status==='FAILED'?'FAILED':'UNKNOWN';const schedulerStatus=latestPipeline?.finishedAt&&Date.now()-Date.parse(latestPipeline.finishedAt)<45*60*1000?'ACTIVE':'UNKNOWN';return{hourKey,dateLabel,time,articlesTotal:published.length,articlesRecentHour:recentCount,...articleMetrics,websiteViews:analytics?.configured?analytics.totalViews:null,websiteViewsReason:analytics?.configured?null:'analytics is not configured',instagramPosts:instagram.posts,instagramViews:instagram.views,instagramViewsReason:instagram.viewsReason,instagramFollowers:instagram.followers,instagramFollowersReason:instagram.followersReason,publicationStatus,schedulerStatus,latestPipelineAt:latestPipeline?.finishedAt||latestPipeline?.startedAt||null,latestSocialAt:latestSocial?.finishedAt||latestSocial?.startedAt||null};}
export async function sendTelegramHourlyReport(now=Date.now()){
 const data=await getHourlyReportData(now);const key=`ba:telegram:hourly:${data.hourKey}`;const lockToken=await acquireNotificationKey(key,HOURLY_TTL_SECONDS);if(!lockToken)return{sent:false,duplicate:true,hourKey:data.hourKey};const text=`📊 <b>BERITA AUTO</b>\n<b>HOURLY REPORT</b>\n${escapeHtml(data.dateLabel)} • ${escapeHtml(data.time)} WIB\n\n📰 <b>BERITA</b>\n• Total berita: <b>${formatNumber(data.articlesTotal)}</b>\n• Berita 1 jam terakhir: <b>${formatNumber(data.articlesRecentHour)}</b>\n\n📚 <b>ARTIKEL</b>\n• Total artikel: <b>${formatNumber(data.articleTotal)}</b>\n• Published: <b>${formatNumber(data.articlePublished)}</b>\n• Needs Review: <b>${formatNumber(data.articleNeedsReview)}</b>\n• Artikel berhasil dibuat 1 jam terakhir: <b>${formatNumber(data.articleCreatedRecentHour)}</b>\n• Artikel published 1 jam terakhir: <b>${formatNumber(data.articlePublishedRecentHour)}</b>\n\n🌐 <b>WEBSITE</b>\n• Total views: <b>${formatNumber(data.websiteViews)}</b>${data.websiteViewsReason?`\n  ${escapeHtml(data.websiteViewsReason)}`:''}\n\n📸 <b>INSTAGRAM</b>\n• Total postingan: <b>${formatNumber(data.instagramPosts)}</b>\n• Total Instagram views: <b>${formatNumber(data.instagramViews)}</b>${data.instagramViewsReason?`\n  ${escapeHtml(data.instagramViewsReason)}`:''}\n• Instagram followers: <b>${formatNumber(data.instagramFollowers)}</b>${data.instagramFollowersReason?`\n  ${escapeHtml(data.instagramFollowersReason)}`:''}\n\n🤖 <b>SYSTEM</b>\n• Publication status: <b>${escapeHtml(data.publicationStatus)}</b>\n• Scheduler status: <b>${escapeHtml(data.schedulerStatus)}</b>\n\n🕐 ${escapeHtml(data.dateLabel)} ${escapeHtml(data.time)} WIB`;try{const result=await sendTelegramMessage(text);console.log(`[telegram] hourly_report_sent hourKey=${data.hourKey}`);return{sent:true,hourKey:data.hourKey,result,data};}catch(error){await releaseLock(key,lockToken).catch(()=>{});console.warn(`[telegram] hourly_report_failed hourKey=${data.hourKey} reason=${safeError(error)}`);return{sent:false,hourKey:data.hourKey,reason:safeError(error),data};}}
export async function sendTelegramPublicationReport({status,article,result,error}={}){const articleId=article?.id||result?.articleId||'unknown';const normalized=status==='success'?'success':status==='partial'?'partial':'failed';const key=`ba:telegram:publication:${normalized}:${articleId}`;const lockToken=await acquireNotificationKey(key,PUBLICATION_TTL_SECONDS);if(!lockToken)return{sent:false,duplicate:true,articleId};const when=result?.publishedAt||article?.sitePublishedAt||new Date().toISOString();const {date:dateLabel,time}=wibParts(new Date(when));const title=escapeHtml(article?.title||articleId);const url=articleUrl(article);let text;if(normalized==='success')text=`🚀 <b>BERITA AUTO</b>\n<b>PUBLICATION SUCCESS</b>\n\n📰 Artikel: <b>${title}</b>\n📸 Instagram: ✅ Published\n🔗 <a href="${escapeHtml(url)}">URL artikel</a>\n\n🕐 ${escapeHtml(dateLabel)} ${escapeHtml(time)} WIB\n\nStatus:\n✅ Article published\n✅ Instagram published`;else if(normalized==='partial')text=`⚠️ <b>BERITA AUTO</b>\n<b>PUBLICATION PARTIAL SUCCESS</b>\n\n📰 Artikel: <b>${title}</b>\n📸 Instagram: ⚠️ Partial / state tidak lengkap\n🔗 <a href="${escapeHtml(url)}">URL artikel</a>\n\n🕐 ${escapeHtml(dateLabel)} ${escapeHtml(time)} WIB`;else text=`🚨 <b>BERITA AUTO</b>\n<b>PUBLICATION FAILED</b>\n\n📰 Artikel: <b>${title}</b>\n📸 Instagram: ❌ Failed\n\nError:\n<code>${escapeHtml(String(error?.message||result?.reason||'publication_failed').slice(0,500))}</code>\n\n🕐 ${escapeHtml(dateLabel)} ${escapeHtml(time)} WIB`;try{const sent=await sendTelegramMessage(text);console.log(`[telegram] publication_report_sent status=${normalized} articleId=${articleId}`);return{sent:true,articleId,status:normalized,result:sent};}catch(sendError){await releaseLock(key,lockToken).catch(()=>{});console.warn(`[telegram] publication_report_failed status=${normalized} articleId=${articleId} reason=${safeError(sendError)}`);return{sent:false,articleId,status:normalized,reason:safeError(sendError)};}}
export async function telegramTest(){if(!telegramConfigured())return{ok:false,reason:'telegram_not_configured'};const bot=await telegramRequest('getMe');return{ok:true,bot:{id:bot?.id,username:bot?.username,firstName:bot?.first_name}};}
