import {NextResponse} from 'next/server';
import {prepareInstagramReviewQueue,REVIEW_MODE} from '../../../../lib/instagram-review.js';
import {runSocialCycle} from '../../../../worker/social-run.js';
import {recordSocialRun} from '../../../../lib/social-telemetry.js';
import {readArticles} from '../../../../lib/storage.js';
import {sendTelegramPublicationReport} from '../../../../lib/telegram.js';
export const dynamic='force-dynamic';
export const runtime='nodejs';
function authorized(request){const secret=process.env.CRON_SECRET||'';const auth=request.headers.get('authorization')||'';return Boolean(secret&&auth===`Bearer ${secret}`);}
async function execute(){const startedAt=new Date().toISOString();try{if(REVIEW_MODE==='review'){const result=await prepareInstagramReviewQueue({trigger:'legacy-social-publish',now:Date.now()});await recordSocialRun({triggerSource:'legacy-social-publish',startedAt,finishedAt:new Date().toISOString(),result}).catch(()=>{});return NextResponse.json({...result,mode:'review',metaCalls:0},{status:200,headers:{'Cache-Control':'no-store'}});}const result=await runSocialCycle({trigger:'vercel-cron',now:Date.now()});await recordSocialRun({triggerSource:'vercel-cron',startedAt,finishedAt:new Date().toISOString(),result}).catch(()=>{});if(['published','failed','persist_error'].includes(result?.status)&&result?.articleId){try{const articles=await readArticles();const article=articles.find(row=>row?.id===result.articleId)||null;const reportStatus=result.status==='published'?'success':result.status==='persist_error'?'partial':'failed';await sendTelegramPublicationReport({status:reportStatus,article,result,error:result?.reason?new Error(result.reason):null});}catch(error){console.warn(`[telegram] publication_notification_noncritical_failed articleId=${result?.articleId||'unknown'} reason=${String(error?.message||error).slice(0,180)}`);}}return NextResponse.json(result,{status:200,headers:{'Cache-Control':'no-store'}});}catch(error){await recordSocialRun({triggerSource:REVIEW_MODE==='review'?'legacy-social-publish':'vercel-cron',startedAt,finishedAt:new Date().toISOString(),result:{status:'failed',reason:'exception'},error}).catch(()=>{});return NextResponse.json({status:'failed',error:String(error?.message||error).replace(/Bearer\s+\S+/gi,'Bearer [redacted]').slice(0,240)},{status:503,headers:{'Cache-Control':'no-store'}})}}
export async function GET(request){if(!authorized(request))return NextResponse.json({error:'Unauthorized'},{status:401});return execute();}
export async function POST(request){return GET(request);}
