import {NextResponse} from 'next/server';
import {auth} from '../../../../../auth.js';
import {getAdminInstagramStatus} from '../../../../../lib/admin-instagram.js';
import {getInstagramReviewSnapshot} from '../../../../../lib/instagram-review.js';
import {getInstagramPublishQueueSnapshot} from '../../../../../lib/instagram-publish-queue.js';
import {getInstagramAutomationSettings} from '../../../../../lib/instagram-automation.js';
export const dynamic='force-dynamic';
export const runtime='nodejs';
async function authorized(){let session=null;try{session=await auth()}catch{return false}const allowed=(process.env.ADMIN_EMAILS||'').split(',').map(v=>v.trim().toLowerCase()).filter(Boolean);const email=session?.user?.email?.trim().toLowerCase();return Boolean(email&&allowed.includes(email));}
export async function GET(){if(!await authorized())return NextResponse.json({error:'Unauthorized'},{status:401,headers:{'Cache-Control':'no-store'}});try{const [status,review,publishQueue,automation]=await Promise.all([getAdminInstagramStatus(),getInstagramReviewSnapshot(),getInstagramPublishQueueSnapshot({now:Date.now()}),getInstagramAutomationSettings()]);console.log('[instagram-status]',JSON.stringify({autoUploadEnabled:automation.autoUploadEnabled,autoUploadSource:automation.source,autoUploadUpdatedAt:automation.updatedAt,ready:review?.counts?.ready||0,queue:{queued:publishQueue.counts?.queued||0,waitingMeta:publishQueue.counts?.waitingMeta||0},throttle:{active:Boolean(publishQueue.throttle?.active),reason:publishQueue.throttle?.reason||null,consecutiveThrottleCount:publishQueue.throttle?.consecutiveThrottleCount||0,nextProbeAt:publishQueue.throttle?.nextProbeAt||null,estimatedResumeAt:publishQueue.throttle?.estimatedResumeAt||null},publishingUsage:publishQueue.publishingUsage?{usage:publishQueue.publishingUsage.usage,total:publishQueue.publishingUsage.total,remaining:publishQueue.publishingUsage.remaining,checkedAt:publishQueue.publishingUsage.checkedAt}:null}));return NextResponse.json({...status,review,publishQueue,automation},{status:200,headers:{'Cache-Control':'no-store'}})}catch(error){return NextResponse.json({error:'Gagal memuat Instagram telemetry.',detail:String(error?.message||error).slice(0,160)},{status:503,headers:{'Cache-Control':'no-store'}})}}
