import {NextResponse} from 'next/server';
import {auth} from '../../../../../auth.js';
import {getAdminInstagramStatus} from '../../../../../lib/admin-instagram.js';
import {getInstagramReviewSnapshot} from '../../../../../lib/instagram-review.js';
import {getInstagramPublishQueueSnapshot} from '../../../../../lib/instagram-publish-queue.js';
import {getInstagramAutomationSettings} from '../../../../../lib/instagram-automation.js';
export const dynamic='force-dynamic';export const runtime='nodejs';
async function authorized(){let session=null;try{session=await auth()}catch{return false}const allowed=(process.env.ADMIN_EMAILS||'').split(',').map(v=>v.trim().toLowerCase()).filter(Boolean);const email=session?.user?.email?.trim().toLowerCase();return Boolean(email&&allowed.includes(email));}
function errorDetail(section,error){return{code:String(error?.code||'PERSISTENCE_ERROR'),operation:String(error?.operation||section),stage:String(error?.stage||'read'),status:error?.status??null,message:String(error?.message||error).slice(0,240)}}
async function section(name,loader,fallback){try{return{value:await loader(),error:null}}catch(error){const detail=errorDetail(name,error);console.error('[instagram-admin]',JSON.stringify({section:name,...detail}));return{value:fallback,error:detail}}}
export async function GET(){if(!await authorized())return NextResponse.json({error:'Unauthorized'},{status:401,headers:{'Cache-Control':'no-store'}});const [status,review,publishQueue,automation]=await Promise.all([section('status',getAdminInstagramStatus,{persistence:{configured:true},automation:{status:'UNKNOWN'},scheduler:{status:'UNKNOWN'},counts:{},runs:[],posts:[],queue:[]}),section('review',getInstagramReviewSnapshot,{items:[],ready:[],counts:{ready:0,preparing:0,failed:0,posted:0,removed:0},lastPreparation:null}),section('publishQueue',()=>getInstagramPublishQueueSnapshot({now:Date.now()}),{items:[],counts:{queued:0,waitingMeta:0},throttle:{active:false},publishingUsage:null}),section('automation',getInstagramAutomationSettings,{autoUploadEnabled:false,source:'unavailable',updatedAt:null,updatedBy:null})]);const errors={};for(const [name,result] of Object.entries({status,review,publishQueue,automation}))if(result.error)errors[name]=result.error;console.log('[instagram-status]',JSON.stringify({autoUploadEnabled:automation.value?.autoUploadEnabled===true,autoUploadSource:automation.value?.source||'unknown',ready:review.value?.counts?.ready||0,queue:{queued:publishQueue.value?.counts?.queued||0,waitingMeta:publishQueue.value?.counts?.waitingMeta||0},throttle:{active:Boolean(publishQueue.value?.throttle?.active),reason:publishQueue.value?.throttle?.reason||null,nextProbeAt:publishQueue.value?.throttle?.nextProbeAt||null},persistenceErrors:Object.keys(errors)}));return NextResponse.json({...status.value,review:review.value,publishQueue:publishQueue.value,automation:automation.value,persistenceErrors:errors,partial:Boolean(Object.keys(errors).length)},{status:200,headers:{'Cache-Control':'no-store'}})}
