import {NextResponse} from 'next/server';
import {randomUUID} from 'node:crypto';
import {requireAdmin} from '../../../../lib/admin-guard.js';
import {persistenceConfigured,upsertIndexed,listJson} from '../../../../lib/persistence.js';
const INDEX='ba:worklog:index';const key=id=>`ba:worklog:${id}`;
const TYPES=['Feature','Bug','Improvement','SEO','Scheduler','AI','UI','Deployment','Infrastructure','Security','Other'];
const STATUSES=['Belum Dikerjakan','Sedang Dikerjakan','Sudah Diperbaiki','Sudah Disesuaikan','Perlu Verifikasi','Blocked','Gagal','Selesai'];
const PRIORITIES=['Low','Normal','High','Critical'];
const clean=(v,max)=>String(v??'').trim().slice(0,max);
function deny(r){if(!r)return NextResponse.json({error:'Unauthorized'},{status:401});if(r.forbidden)return NextResponse.json({error:'Forbidden'},{status:403})}
const normalize=(body,email,existing={})=>{const now=new Date().toISOString();return {id:existing.id||body.id||randomUUID(),title:clean(body.title??existing.title,180),description:clean(body.description??existing.description,5000),type:TYPES.includes(body.type??existing.type)?(body.type??existing.type):'Other',status:STATUSES.includes(body.status??existing.status)?(body.status??existing.status):'Belum Dikerjakan',priority:PRIORITIES.includes(body.priority??existing.priority)?(body.priority??existing.priority):'Normal',createdBy:existing.createdBy||email,updatedBy:email,assignedTo:clean(body.assignedTo??existing.assignedTo,160)||null,problem:clean(body.problem??existing.problem,10000),fixDescription:clean(body.fixDescription??existing.fixDescription,10000),verificationResult:clean(body.verificationResult??existing.verificationResult,10000),blocker:clean(body.blocker??existing.blocker,5000),commitSha:clean(body.commitSha??existing.commitSha,64)||null,deploymentId:clean(body.deploymentId??existing.deploymentId,160)||null,createdAt:existing.createdAt||now,updatedAt:now,resolvedAt:(body.status==='Selesai'&&!existing.resolvedAt)?now:(body.resolvedAt??existing.resolvedAt??null)}};
const baseline=[
 {id:'public-search-404',title:'Public search route /cari',type:'Bug',priority:'High',description:'Public search previously returned 404 while header forms linked to /cari.',problem:'Production /cari returned 404.',status:'Perlu Verifikasi'},
 {id:'gemini-live-verification',title:'Gemini live generation verification',type:'AI',priority:'High',description:'Verify real Gemini publication after repository secret configuration.',problem:'GEMINI_API_KEY existence is not exposed by the available connector.',status:'Blocked',blocker:'GEMINI_API_KEY cannot be verified from available connector.'},
 {id:'publication-cadence',title:'Publication cadence verification',type:'Scheduler',priority:'High',description:'Measure actual schedule dispatch gaps separately from worker runtime.',problem:'GitHub scheduled runs show platform dispatch jitter.',status:'Perlu Verifikasi'},
 {id:'admin-authenticated-visual',title:'Authenticated admin visual/CRUD verification',type:'UI',priority:'Normal',description:'Verify authenticated admin experience end-to-end.',problem:'Only the public OAuth gate is directly reachable without an administrator session.',status:'Perlu Verifikasi'},
 {id:'seo-sitemap-format',title:'SEO sitemap audit',type:'SEO',priority:'High',description:'Normalize sitemap lastmod and add Google News sitemap.',problem:'Previous sitemap returned mixed date formats and had no news sitemap.',status:'Sedang Dikerjakan'}
];
async function ensureBaseline(email){const current=await listJson(INDEX);const byId=new Map(current.map(x=>[x.id,x]));for(const seed of baseline){if(!byId.has(seed.id))await upsertIndexed(INDEX,key(seed.id),{...seed,createdBy:email,updatedBy:email,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),assignedTo:null,fixDescription:'',verificationResult:'',blocker:seed.blocker||'',commitSha:null,deploymentId:null,resolvedAt:null})}return listJson(INDEX)}
export async function GET(request){const r=await requireAdmin();const d=deny(r);if(d)return d;if(!persistenceConfigured())return NextResponse.json({error:'Persistent admin database is not configured'},{status:503});try{let rows=await ensureBaseline(r.email);const {searchParams}=new URL(request.url);const q=clean(searchParams.get('q'),200).toLowerCase();const status=searchParams.get('status')||'';const type=searchParams.get('type')||'';const priority=searchParams.get('priority')||'';rows=rows.filter(x=>(!q||[x.title,x.description,x.problem,x.fixDescription,x.verificationResult,x.blocker].join(' ').toLowerCase().includes(q))&&(!status||x.status===status)&&(!type||x.type===type)&&(!priority||x.priority===priority));return NextResponse.json({items:rows,summary:Object.fromEntries(STATUSES.map(s=>[s,rows.filter(x=>x.status===s).length]))})}catch(error){return NextResponse.json({error:'Work log unavailable'},{status:503})}}
export async function POST(request){const r=await requireAdmin();const d=deny(r);if(d)return d;if(!persistenceConfigured())return NextResponse.json({error:'Persistent admin database is not configured'},{status:503});try{const body=await request.json();if(!clean(body.title,180))return NextResponse.json({error:'Title is required'},{status:400});const item=normalize(body,r.email);await upsertIndexed(INDEX,key(item.id),item);return NextResponse.json(item,{status:201})}catch(error){return NextResponse.json({error:'Unable to create work log item'},{status:400})}}
export const workLogKey=key;
export const workLogIndex=INDEX;
export const workLogNormalize=normalize;
export const workLogTypes=TYPES;
export const workLogStatuses=STATUSES;
export const workLogPriorities=PRIORITIES;
