import {NextResponse} from 'next/server';
import {getInstagramAutomationSettings,setInstagramAutoUploadEnabled} from '../../../../../lib/instagram-automation.js';
import {getInstagramAdminSnapshot,invalidateInstagramAdminSnapshot} from '../../../../../lib/instagram-admin-snapshot.js';
import {requireAdmin} from '../../../../../lib/admin-guard.js';
export const dynamic='force-dynamic';export const runtime='nodejs';
async function guard(){const admin=await requireAdmin();if(!admin)return NextResponse.json({error:'Unauthorized'},{status:401,headers:{'Cache-Control':'no-store'}});if(admin.forbidden)return NextResponse.json({error:'Forbidden'},{status:403,headers:{'Cache-Control':'no-store'}});return admin;}
function detail(error){return{code:String(error?.code||'PERSISTENCE_ERROR'),operation:String(error?.operation||'automation'),stage:String(error?.stage||'read'),status:error?.status??null,message:String(error?.message||error).slice(0,240)}}
export async function GET(){const denied=await guard();if(denied instanceof NextResponse)return denied;try{const snapshot=await getInstagramAdminSnapshot();const settings=snapshot.automation||{autoUploadEnabled:false,source:'unavailable',updatedAt:null};console.log('[instagram-automation]',JSON.stringify({autoUploadEnabled:settings.autoUploadEnabled,source:settings.source,updatedAt:settings.updatedAt}));return NextResponse.json(settings,{status:200,headers:{'Cache-Control':'private, max-age=10, stale-while-revalidate=10'}})}catch(error){const d=detail(error);console.error('[instagram-automation]',JSON.stringify(d));return NextResponse.json({autoUploadEnabled:false,source:'unavailable',updatedAt:null,persistenceError:d},{status:200,headers:{'Cache-Control':'private, max-age=5'}})}}
export async function PATCH(request){const admin=await guard();if(admin instanceof NextResponse)return admin;try{const body=await request.json();const enabled=body?.autoUploadEnabled===true;const before=await getInstagramAutomationSettings();const settings=await setInstagramAutoUploadEnabled(enabled,{updatedBy:admin?.email||admin?.user?.email||null});invalidateInstagramAdminSnapshot();console.log('[instagram-automation]',JSON.stringify({event:'toggle',oldValue:before.autoUploadEnabled,newValue:settings.autoUploadEnabled,updatedAt:settings.updatedAt}));return NextResponse.json(settings,{status:200,headers:{'Cache-Control':'no-store'}})}catch(error){const d=detail(error);console.error('[instagram-automation]',JSON.stringify({event:'toggle_failed',...d}));return NextResponse.json({error:'AUTO_UPLOAD_SETTING_WRITE_FAILED',detail:d},{status:503,headers:{'Cache-Control':'no-store'}})}}
