import Link from 'next/link';
import {auth} from '../../../auth.js';
import {getJson,setMembers,mgetJson} from '../../../lib/persistence.js';
import {INSTAGRAM_PUBLISH_QUEUE_INDEX} from '../../../lib/instagram-publish-queue.js';
import {REVIEW_QUEUE_INDEX} from '../../../lib/instagram-review.js';
import {readRecentPublished} from '../../../lib/social.js';
import InstagramQueueControls from '../InstagramQueueControls.jsx';

const REVIEW_ITEM=id=>`ba:social:instagram:review:item:${id}`;
function sort(a,b){return Number(b?.priority||0)-Number(a?.priority||0)||Date.parse(b?.priorityUpdatedAt||b?.queuedAt||b?.createdAt||'')-Date.parse(a?.priorityUpdatedAt||a?.queuedAt||a?.createdAt||'')||Date.parse(a?.queuedAt||a?.createdAt||'')-Date.parse(b?.queuedAt||b?.createdAt||'')}
async function readQueue(){const keys=await setMembers(INSTAGRAM_PUBLISH_QUEUE_INDEX);const rows=keys.length?await mgetJson(keys):[];const queued=rows.filter(row=>['QUEUED','WAITING_META'].includes(String(row?.status||'').toUpperCase())).sort(sort);const activeReviews=queued.length?await mgetJson(queued.map(row=>REVIEW_ITEM(row.queueId))):[];const active=queued.map((row,i)=>({...row,...(activeReviews[i]||{}),queueId:row.queueId,articleId:row.articleId||activeReviews[i]?.articleId,title:row.title||activeReviews[i]?.title||'Berita',position:i+1,caption:row.caption||activeReviews[i]?.caption||row.captionBody||activeReviews[i]?.captionBody||'',previewUrl:row.previewUrl||activeReviews[i]?.previewUrl||null,cardUrls:Array.isArray(row.cardUrls)?row.cardUrls:(Array.isArray(activeReviews[i]?.cardUrls)?activeReviews[i].cardUrls:[]),sourceImageUrl:row.sourceImageUrl||activeReviews[i]?.sourceImageUrl||null,imageOriginUrl:row.imageOriginUrl||activeReviews[i]?.imageOriginUrl||null,articleImageUrl:row.articleImageUrl||activeReviews[i]?.articleImageUrl||null}));const reviewKeys=await setMembers(REVIEW_QUEUE_INDEX);const reviewRows=reviewKeys.length?await mgetJson(reviewKeys):[];const terminal=reviewRows.filter(row=>['REMOVED','FAILED'].includes(String(row?.status||'').toUpperCase())).map(row=>({...row,queueId:row.queueId||row.id,title:row.title||'Berita',caption:row.caption||row.captionBody||'',previewUrl:row.previewUrl||null,cardUrls:Array.isArray(row.cardUrls)?row.cardUrls:[],sourceImageUrl:row.sourceImageUrl||null,imageOriginUrl:row.imageOriginUrl||null,articleImageUrl:row.articleImageUrl||null}));const activeIds=new Set(active.map(row=>row.queueId));return [...active,...terminal.filter(row=>row.queueId&&!activeIds.has(row.queueId))]}
export const dynamic='force-dynamic';
export default async function InstagramQueuePage(){let session=null;try{session=await auth()}catch{}const allowed=(process.env.ADMIN_EMAILS||'').split(',').map(v=>v.trim().toLowerCase()).filter(Boolean);if(!session?.user?.email||!allowed.includes(session.user.email.trim().toLowerCase()))return <main className="ig-shell"><section className="ig-panel"><h1>Akses ditolak</h1></section></main>;const all=await readQueue();const active=all.filter(x=>['QUEUED','WAITING_META'].includes(String(x.status||'').toUpperCase()));const recent=await readRecentPublished(1).catch(()=>[]);const lastSuccessAt=recent[0]?.publishedAt||null;const throttle=await getJson('ba:social:instagram:publish-throttle').catch(()=>null);const usage=await getJson('ba:social:instagram:publishing-usage').catch(()=>null);return <main className="ig-shell"><div className="ig-main-container"><section className="ig-page-header"><div className="ig-page-header-copy"><span className="ig-kicker">BERITA AUTO · INSTAGRAM</span><h1>Antrean Upload</h1><p>{active.length} item menunggu · urutan sama dengan publisher</p></div><div className="ig-page-header-actions"><Link href="/admin-instagram">← Instagram Automation</Link></div></section><section className="ig-panel"><div className="ig-queue-range"><strong>{active.length} item menunggu</strong><span>Queued {active.filter(x=>x.status==='QUEUED').length} · Waiting Meta {active.filter(x=>x.status==='WAITING_META').length} · Prioritas {active.filter(x=>Number(x.priority||0)>0).length}</span></div><InstagramQueueControls items={all} lastSuccessAt={lastSuccessAt} nowIso={new Date().toISOString()} limit={2200} throttle={throttle} publishingUsage={usage}/></section></div></main>}
