import Link from 'next/link';
import {auth} from '../../../auth.js';
import {getJson,setMembers,mgetJson} from '../../../lib/persistence.js';
import {INSTAGRAM_PUBLISH_QUEUE_INDEX} from '../../../lib/instagram-publish-queue.js';

const REVIEW_ITEM=id=>`ba:social:instagram:review:item:${id}`;
function sort(a,b){return Number(b?.priority||0)-Number(a?.priority||0)||Date.parse(b?.priorityUpdatedAt||b?.queuedAt||b?.createdAt||'')-Date.parse(a?.priorityUpdatedAt||a?.queuedAt||a?.createdAt||'')||Date.parse(a?.queuedAt||a?.createdAt||'')-Date.parse(b?.queuedAt||b?.createdAt||'')}
function fmt(value){return value?new Date(value).toLocaleString('id-ID',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Jakarta'}):'Belum tercatat'}
async function readQueue(){const keys=await setMembers(INSTAGRAM_PUBLISH_QUEUE_INDEX);const rows=keys.length?await mgetJson(keys):[];const queued=rows.filter(row=>['QUEUED','WAITING_META'].includes(String(row?.status||'').toUpperCase())).sort(sort);const reviews=queued.length?await mgetJson(queued.map(row=>REVIEW_ITEM(row.queueId))):[];return queued.map((row,i)=>({...row,...(reviews[i]||{}),queueId:row.queueId,articleId:row.articleId||reviews[i]?.articleId,title:row.title||reviews[i]?.title||'Berita'}))}
export const dynamic='force-dynamic';
export default async function InstagramQueuePage({searchParams}){let session=null;try{session=await auth()}catch{}const allowed=(process.env.ADMIN_EMAILS||'').split(',').map(v=>v.trim().toLowerCase()).filter(Boolean);if(!session?.user?.email||!allowed.includes(session.user.email.trim().toLowerCase()))return <main className="ig-shell"><section className="ig-panel"><h1>Akses ditolak</h1></section></main>;const params=await searchParams;const page=Math.max(1,Number(params?.page||1)||1);const all=await readQueue();const limit=20;const pages=Math.max(1,Math.ceil(all.length/limit));const current=Math.min(page,pages);const items=all.slice((current-1)*limit,current*limit);return <main className="ig-shell"><div className="ig-main-container"><section className="ig-page-header"><div className="ig-page-header-copy"><span className="ig-kicker">BERITA AUTO · INSTAGRAM</span><h1>Antrean Upload</h1><p>{all.length} item dalam antrean · urutan sama dengan publisher</p></div><div className="ig-page-header-actions"><Link href="/admin-instagram">← Instagram Automation</Link></div></section><section className="ig-panel"><div className="ig-queue-range"><strong>{all.length} item dalam antrean</strong><span>Menampilkan {all.length?`${(current-1)*limit+1}–${Math.min(current*limit,all.length)} dari ${all.length}`:'0 dari 0'}</span></div><div className="ig-queue-full-grid">{items.map((item,index)=><article className="ig-queue-full-card" key={item.queueId}><span className="ig-kicker">#{(current-1)*limit+index+1} · PRIORITAS {Number(item.priority||0)}</span><h2>{String(item.title).slice(0,180)}</h2><p>Status: {String(item.status||'UNKNOWN')}</p><p>Percobaan: {Number(item.publishAttemptCount||item.attempts||0)}</p><p>Percobaan terakhir: {fmt(item.lastPublishAttemptAt)}</p><p>Hasil terakhir: {item.lastAttemptResult||item.lastFailureMessage||'Belum pernah diproses publisher'}</p><Link href={`/admin-instagram/queue/${encodeURIComponent(item.queueId)}`}>Lihat Detail →</Link></article>)}</div><nav className="ig-pagination" aria-label="Pagination">{current>1?<Link href={`/admin-instagram/queue?page=${current-1}`}>← Sebelumnya</Link>:<span/>}<strong>Page {current} / {pages}</strong>{current<pages?<Link href={`/admin-instagram/queue?page=${current+1}`}>Berikutnya →</Link>:<span/>}</nav></section></div></main>}
