import {NextResponse} from 'next/server';
import {requireAdmin} from '../../../../../lib/admin-guard.js';
import {prepareInstagramAdminLive} from '../../../../../lib/instagram-preparation-admin-live.js';
import {getInstagramAdminSnapshot,invalidateInstagramAdminSnapshot} from '../../../../../lib/instagram-admin-snapshot.js';
import {getInstagramPreparationProgress} from '../../../../../lib/instagram-preparation-progress.js';
export const dynamic='force-dynamic';export const runtime='nodejs';
async function guard(){const admin=await requireAdmin();if(!admin)return NextResponse.json({error:'Unauthorized'},{status:401,headers:{'Cache-Control':'no-store'}});if(admin.forbidden)return NextResponse.json({error:'Forbidden'},{status:403,headers:{'Cache-Control':'no-store'}});return admin;}
function isPreparationRun(row){return ['admin-manual','social-prepare','qstash','scheduled'].includes(String(row?.triggerSource||''))}
async function state(){const progress=await getInstagramPreparationProgress({recoverStale:true});const snapshot=await getInstagramAdminSnapshot();const runs=Array.isArray(snapshot.runs)?snapshot.runs:[];const active=progress?.status==='PREPARING'&&progress?.runId?{runId:progress.runId,trigger:progress.trigger,startedAt:progress.startedAt,expiresAt:Date.parse(progress.startedAt||'')+120000,requestedTarget:progress.requestedTarget||null,resumeRequired:Boolean(progress.resumeRequired)}:null;const previous=snapshot.preparation?.lastRun||snapshot.review?.lastPreparation||null;const lastRun=previous||(!active&&progress?.completedAt?{runId:progress.runId,status:progress.status,attempted:progress.attempted||0,ready:progress.ready||0,failed:progress.failed||0,requestedTarget:progress.requestedTarget||null,primaryBlocker:progress.primaryBlocker||null,failureBreakdown:progress.failureBreakdown||{},completedAt:progress.completedAt,resumeRequired:Boolean(progress.resumeRequired)}:null);const logs=runs.filter(isPreparationRun).slice(0,10).map(run=>({runId:run.runId,trigger:run.triggerSource,status:run.status,stage:run.stage,reason:run.reason||null,durationMs:Number(run.durationMs||0),diagnostics:run.preparationDiagnostics||null,finishedAt:run.finishedAt}));return{active,lastRun,progress:progress||null,logs}}
export async function GET(){const denied=await guard();if(denied instanceof NextResponse)return denied;try{return NextResponse.json(await state(),{status:200,headers:{'Cache-Control':'no-store'}})}catch(error){return NextResponse.json({active:false,progress:null,lastRun:null,logs:[],persistenceError:{code:String(error?.code||'PERSISTENCE_ERROR'),operation:String(error?.operation||'prepare_status'),stage:String(error?.stage||'read'),status:error?.status??null,message:String(error?.message||error).slice(0,240)}},{status:200,headers:{'Cache-Control':'no-store'}})}}
export async function POST(request){const denied=await guard();if(denied instanceof NextResponse)return denied;try{const body=await request.json().catch(()=>({}));const raw=Number(body?.targetReady);if(!Number.isFinite(raw)||raw<1||raw>15)return NextResponse.json({error:'targetReady harus antara 1 dan 15.'},{status:400,headers:{'Cache-Control':'no-store'}});invalidateInstagramAdminSnapshot();const result=await prepareInstagramAdminLive({now:Date.now(),targetReady:Math.trunc(raw)});invalidateInstagramAdminSnapshot();return NextResponse.json(result,{status:200,headers:{'Cache-Control':'no-store'}})}catch(error){invalidateInstagramAdminSnapshot();return NextResponse.json({status:'FAILED',error:String(error?.message||error).slice(0,240)},{status:503,headers:{'Cache-Control':'no-store'}})}}
