import {NextResponse} from 'next/server';
import {requireAdmin} from '../../../../../lib/admin-guard.js';
import {prepareInstagramAdminLive} from '../../../../../lib/instagram-preparation-admin-live.js';
import {invalidateInstagramAdminSnapshot} from '../../../../../lib/instagram-admin-snapshot.js';
import {getInstagramPreparationProgress} from '../../../../../lib/instagram-preparation-progress.js';
export const dynamic='force-dynamic';export const runtime='nodejs';
async function guard(){const admin=await requireAdmin();if(!admin)return NextResponse.json({error:'Unauthorized'},{status:401,headers:{'Cache-Control':'no-store'}});if(admin.forbidden)return NextResponse.json({error:'Forbidden'},{status:403,headers:{'Cache-Control':'no-store'}});return admin;}
async function state(){const progress=await getInstagramPreparationProgress({recoverStale:true});const active=progress?.status==='PREPARING'&&progress?.runId?{runId:progress.runId,trigger:progress.trigger,startedAt:progress.startedAt,expiresAt:Number(progress.expiresAt||0),requestedTarget:progress.requestedTarget||null,resumeRequired:Boolean(progress.resumeRequired)}:null;const lastRun=progress?.completedAt||progress?.status==='COMPLETED'||progress?.status==='BLOCKED'?{runId:progress.runId,status:progress.status,attempted:progress.attempted||0,ready:progress.ready||0,failed:progress.failed||0,requestedTarget:progress.requestedTarget||null,primaryBlocker:progress.primaryBlocker||null,failureBreakdown:progress.failureBreakdown||{},completedAt:progress.completedAt||null,resumeRequired:Boolean(progress.resumeRequired)}:null;return{active,lastRun,progress:progress||null,logs:[]};}
export async function GET(){const denied=await guard();if(denied instanceof NextResponse)return denied;try{return NextResponse.json(await state(),{status:200,headers:{'Cache-Control':'no-store'}})}catch(error){return NextResponse.json({active:false,progress:null,lastRun:null,logs:[],persistenceError:{code:String(error?.code||'PERSISTENCE_ERROR'),operation:String(error?.operation||'prepare_status'),stage:String(error?.stage||'read'),status:error?.status??null,message:String(error?.message||error).slice(0,240)}},{status:200,headers:{'Cache-Control':'no-store'}})}}
export async function POST(request){const denied=await guard();if(denied instanceof NextResponse)return denied;try{const body=await request.json().catch(()=>({}));const raw=Number(body?.targetReady);if(!Number.isFinite(raw)||raw<1||raw>15)return NextResponse.json({error:'targetReady harus antara 1 dan 15.'},{status:400,headers:{'Cache-Control':'no-store'}});invalidateInstagramAdminSnapshot();const result=await prepareInstagramAdminLive({now:Date.now(),targetReady:Math.trunc(raw)});invalidateInstagramAdminSnapshot();return NextResponse.json(result,{status:200,headers:{'Cache-Control':'no-store'}})}catch(error){invalidateInstagramAdminSnapshot();return NextResponse.json({status:'FAILED',error:String(error?.message||error).slice(0,240)},{status:503,headers:{'Cache-Control':'no-store'}})}}
