import {NextResponse} from 'next/server';
import {requireAdmin} from '../../../../../lib/admin-guard.js';
import {prepareInstagramProductionQueue} from '../../../../../lib/instagram-preparation-runtime.js';
import {getInstagramAdminSnapshot,invalidateInstagramAdminSnapshot} from '../../../../../lib/instagram-admin-snapshot.js';
export const dynamic='force-dynamic';
export const runtime='nodejs';
async function guard(){const admin=await requireAdmin();if(!admin)return NextResponse.json({error:'Unauthorized'},{status:401,headers:{'Cache-Control':'no-store'}});if(admin.forbidden)return NextResponse.json({error:'Forbidden'},{status:403,headers:{'Cache-Control':'no-store'}});return admin;}
function isPreparationRun(row){return ['admin-manual','social-prepare','qstash','scheduled'].includes(String(row?.triggerSource||''))}
async function state(){const snapshot=await getInstagramAdminSnapshot();const runs=Array.isArray(snapshot.runs)?snapshot.runs:[];const logs=runs.filter(isPreparationRun).slice(0,10).map(run=>({runId:run.runId,trigger:run.triggerSource,status:run.status,stage:run.stage,reason:run.reason||null,durationMs:Number(run.durationMs||0),diagnostics:run.preparationDiagnostics||null,finishedAt:run.finishedAt}));return{active:snapshot.preparation?.active||null,lastRun:snapshot.preparation?.lastRun||snapshot.review?.lastPreparation||null,logs}}
export async function GET(){const denied=await guard();if(denied instanceof NextResponse)return denied;try{return NextResponse.json(await state(),{status:200,headers:{'Cache-Control':'private, max-age=10, stale-while-revalidate=10'}})}catch(error){return NextResponse.json({active:null,lastRun:null,logs:[],persistenceError:{code:String(error?.code||'PERSISTENCE_ERROR'),operation:String(error?.operation||'prepare_status'),stage:String(error?.stage||'read'),status:error?.status??null,message:String(error?.message||error).slice(0,240)}},{status:200,headers:{'Cache-Control':'private, max-age=5'}})}}
export async function POST(request){const denied=await guard();if(denied instanceof NextResponse)return denied;try{invalidateInstagramAdminSnapshot();const result=await prepareInstagramProductionQueue({trigger:'admin-manual',now:Date.now()});invalidateInstagramAdminSnapshot();return NextResponse.json(result,{status:200,headers:{'Cache-Control':'no-store'}})}catch(error){invalidateInstagramAdminSnapshot();return NextResponse.json({status:'failed',error:String(error?.message||error).slice(0,240),metaCalls:0},{status:503,headers:{'Cache-Control':'no-store'}})}}
