import {notFound,permanentRedirect} from 'next/navigation';
import ArticleDetailView from '../../../components/article/ArticleDetailView.jsx';
import {readPublicArticles,readPublicListArticles} from '../../../lib/public-data.js';
import {articlePath,articleSlug,stableIdFromArticlePath,matchesArticleStableId} from '../../../lib/article-url.js';
import {isLegacyArticlePath,legacyIdFromPath,resolveLegacyArticle} from '../../../lib/legacy-route.js';
import {cleanExcerpt} from '../../../lib/text.js';
import {getPopularArticles} from '../../../lib/analytics.js';
import {FOREIGN_SOURCE_IDS} from '../../../lib/sources.js';
import {categories} from '../../../lib/categories.js';
import {hasRealSourceImage} from '../../../lib/homepage-display.js';
import '../../artikel/artikel.css';
const base='https://berita-auto.vercel.app';export const dynamic='force-dynamic';
function isForeign(a){return String(a?.language||'id').toLowerCase()!=='id'||FOREIGN_SOURCE_IDS.has(String(a?.sourceId||''))}function isPending(a){return String(a?.translationStatus||'').toLowerCase()==='pending'||(isForeign(a)&&String(a?.translationStatus||'').toLowerCase()!=='translated')}function counts(items){const out=Object.fromEntries(categories.map(c=>[c,0]));for(const a of items){const c=categories.find(x=>x.toLowerCase()===String(a.category||'').trim().toLowerCase());if(c)out[c]++}return out}function similarity(a,b){let s=0;if(a.topicCluster&&b.topicCluster&&a.topicCluster===b.topicCluster)s+=50;if(a.category&&b.category&&String(a.category).toLowerCase()===String(b.category).toLowerCase())s+=20;const e=new Set((a.entities||a.entityNames||[]).map(x=>String(x).toLowerCase()));for(const x of(b.entities||b.entityNames||[]))if(e.has(String(x).toLowerCase()))s+=12;return s}
export async function generateMetadata({params}){const {slug}=await params;const items=await readPublicArticles();const article=items.find(x=>x.id===slug)||items.find(x=>matchesArticleStableId(x,slug));if(!article)return{title:'Artikel tidak ditemukan',robots:{index:false,follow:true}};const canonical=`${base}${articlePath(article)}`;const description=cleanExcerpt(article.excerpt||article.summary||article.title||'').slice(0,160);const image=hasRealSourceImage(article)?String(article.imageUrl):null;return{title:article.title,description,robots:isPending(article)?{index:false,follow:true,noarchive:true}:{index:true,follow:true},alternates:{canonical},openGraph:{type:'article',url:canonical,title:article.title,description,siteName:'Berita Auto',locale:'id_ID',publishedTime:article.sitePublishedAt||article.publishedAt||article.createdAt,modifiedTime:article.updatedAt||article.publishedAt,images:image?[{url:image,width:1200,height:675,alt:article.title}]:[]},twitter:{card:'summary_large_image',title:article.title,description,images:image?[image]:[]}}}
export default async function ArticlePage({params}){const {slug}=await params;const items=await readPublicArticles();const direct=items.find(x=>x.id===slug);if(direct)permanentRedirect(articlePath(direct));if(isLegacyArticlePath(`/berita/${slug}`)){const resolved=await resolveLegacyArticle(items,legacyIdFromPath(`/berita/${slug}`));if(resolved.article)permanentRedirect(articlePath(resolved.article));notFound()}const short=stableIdFromArticlePath(slug);if(!short)notFound();const article=items.find(x=>matchesArticleStableId(x,slug));if(!article)notFound();if(slug!==articleSlug(article))permanentRedirect(articlePath(article));if(!String(article.content||'').trim())notFound();const [news,popular]=await Promise.all([readPublicListArticles(),getPopularArticles(items,7,5)]);const published=items.filter(x=>!isForeign(x)&&!isPending(x));const relatedArticles=published.filter(x=>x.id!==article.id).sort((a,b)=>similarity(article,b)-similarity(article,a)).slice(0,5);const relatedNews=news.filter(x=>x.contentType!=='article'&&x.id!==article.id).sort((a,b)=>{const rank=x=>/otomotif|automotive|transportasi|kendaraan/i.test(String(x.category||''))?1:0;return rank(b)-rank(a)}).slice(0,5);return <ArticleDetailView article={article} latestArticles={published} popularArticles={popular} latestNews={news} relatedArticles={relatedArticles} relatedNews={relatedNews} categoryCounts={counts([...items,...news])}/>}
