'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
const STATUS=[['open','Open'],['monitoring','Monitoring'],['resolved','Resolved']];
const PRIORITIES=['P1','P2','P3'];
const AREAS=['Performance','SEO','Google','Admin','Automation','Berita','Iklan','Analytics','Navbar','Social','Infrastructure'];
const statusLabel=Object.fromEntries(STATUS);
const fmt=value=>{if(!value)return '-';const d=new Date(value);return Number.isNaN(d.getTime())?'-':new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Jakarta'}).format(d)+' WIB'};
const tab=()=>new URLSearchParams(window.location.search).get('tab')||'automation';
export default function AdminNotesPanel(){
 const [active,setActive]=useState(false),[notes,setNotes]=useState([]),[filter,setFilter]=useState(''),[area,setArea]=useState(''),[priority,setPriority]=useState(''),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [title,setTitle]=useState(''),[content,setContent]=useState(''),[status,setStatus]=useState('open'),[newPriority,setNewPriority]=useState('P2'),[newArea,setNewArea]=useState('Admin');
 const [editing,setEditing]=useState(null),[edit,setEdit]=useState(null);
 const refresh=useCallback(async()=>{setLoading(true);setError('');try{const r=await fetch('/api/admin/notes',{cache:'no-store'});const data=await r.json().catch(()=>null);if(!r.ok)throw new Error(data?.error||'Gagal memuat Catatan & Perbaikan.');setNotes(Array.isArray(data)?data:[])}catch(e){setError(e.message||'Gagal memuat Catatan & Perbaikan.')}finally{setLoading(false)}},[]);
 useEffect(()=>{const sync=()=>setActive(tab()==='notes');sync();const original=history.pushState;const onPop=sync;history.pushState=function(...args){const r=original.apply(this,args);window.dispatchEvent(new Event('admin:navigation'));return r};window.addEventListener('admin:navigation',sync);window.addEventListener('popstate',onPop);return()=>{history.pushState=original;window.removeEventListener('admin:navigation',sync);window.removeEventListener('popstate',onPop)}},[]);
 useEffect(()=>{if(active)refresh()},[active,refresh]);
 useEffect(()=>{const shell=document.querySelector('.admin-workspace-shell');if(!shell)return;const placeholder=[...shell.querySelectorAll('.admin-shell .admin-content > section.admin-panel')].find(x=>x.textContent?.includes('CATATAN & PERBAIKAN'));if(placeholder)placeholder.style.display=active?'none':'';return()=>{if(placeholder)placeholder.style.display=''}},[active,loading,error,notes.length]);
 const counts=useMemo(()=>Object.fromEntries(STATUS.map(([s])=>[s,notes.filter(n=>n.status===s).length])),[notes]);
 const filtered=useMemo(()=>notes.filter(n=>(!filter||n.status===filter)&&(!area||n.area===area)&&(!priority||n.priority===priority)),[notes,filter,area,priority]);
 const save=async()=>{if(!content.trim())return;setSaving(true);setError('');try{const r=await fetch('/api/admin/notes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,content,status,priority:newPriority,area:newArea})});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.error||'Gagal menyimpan catatan.');setNotes(v=>[d,...v.filter(x=>x.id!==d.id)]);setTitle('');setContent('');setNotice('Catatan tersimpan.')}catch(e){setError(e.message||'Gagal menyimpan catatan.')}finally{setSaving(false)}};
 const beginEdit=n=>{setEditing(n.id);setEdit({title:n.title,content:n.content,status:n.status||'open',priority:n.priority||'P2',area:n.area||'Admin'})};
 const update=async()=>{if(!editing||!edit?.content?.trim())return;setSaving(true);setError('');try{const r=await fetch(`/api/admin/notes/${encodeURIComponent(editing)}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(edit)});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.error||'Gagal memperbarui catatan.');setNotes(v=>v.map(n=>n.id===d.id?d:n));setEditing(null);setEdit(null);setNotice('Catatan diperbarui.')}catch(e){setError(e.message||'Gagal memperbarui catatan.')}finally{setSaving(false)}};
 const remove=async id=>{if(!window.confirm('Hapus catatan ini?'))return;try{const r=await fetch(`/api/admin/notes/${encodeURIComponent(id)}`,{method:'DELETE'});if(!r.ok)throw new Error('Gagal menghapus catatan.');setNotes(v=>v.filter(n=>n.id!==id));setNotice('Catatan dihapus.')}catch(e){setError(e.message||'Gagal menghapus catatan.')}};
 if(!active)return null;
 return <section className="admin-notes-route-panel admin-notes" aria-label="Catatan & Perbaikan"><header className="admin-notes-header"><div><p className="admin-label">CATATAN &amp; PERBAIKAN</p><h2 className="admin-notes-title">Maintenance tracker</h2><p className="admin-notes-subtitle">Catatan internal ringan untuk pekerjaan, known issues, dan hasil perbaikan.</p></div><span className="admin-notes-count">{notes.length} catatan</span></header>
 <div className="worklog-summary"><div><strong>{counts.open||0}</strong><span>Open</span></div><div><strong>{counts.monitoring||0}</strong><span>Monitoring</span></div><div><strong>{counts.resolved||0}</strong><span>Resolved</span></div><div><strong>{notes.length}</strong><span>Total</span></div></div>
 <div className="admin-note-compose"><input className="admin-note-title-input" value={title} onChange={e=>setTitle(e.target.value)} placeholder="Judul catatan"/><textarea className="admin-note-textarea" value={content} onChange={e=>setContent(e.target.value)} placeholder="Tulis catatan, diagnosis, atau resolution note…"/><div className="admin-note-compose-meta"><select value={status} onChange={e=>setStatus(e.target.value)}>{STATUS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select value={newPriority} onChange={e=>setNewPriority(e.target.value)}>{PRIORITIES.map(v=><option key={v}>{v}</option>)}</select><select value={newArea} onChange={e=>setNewArea(e.target.value)}>{AREAS.map(v=><option key={v}>{v}</option>)}</select></div><div className="admin-note-compose-actions"><span className="admin-note-draft">Server-side persistent storage</span><button className="admin-note-save" disabled={saving||!content.trim()} onClick={save}>{saving?'Menyimpan…':'Tambah Catatan'}</button></div></div>
 <div className="admin-note-filters"><div className="admin-note-filter-group"><button className={!filter?'active':''} onClick={()=>setFilter('')}>Semua ({notes.length})</button>{STATUS.map(([v,l])=><button key={v} className={filter===v?'active':''} onClick={()=>setFilter(v)}>{l} ({counts[v]||0})</button>)}</div><select value={area} onChange={e=>setArea(e.target.value)}><option value="">Semua area</option>{AREAS.map(v=><option key={v}>{v}</option>)}</select><select value={priority} onChange={e=>setPriority(e.target.value)}><option value="">Semua prioritas</option>{PRIORITIES.map(v=><option key={v}>{v}</option>)}</select></div>
 {error&&<div className="admin-note-error" role="alert">{error} <button onClick={refresh}>Coba lagi</button></div>}{notice&&<div className="admin-note-toast">{notice}</div>}
 {loading?<div className="admin-notes-empty">Memuat catatan…</div>:!filtered.length?<div className="admin-notes-empty"><strong>Belum ada catatan pada filter ini.</strong><span>Tambahkan catatan pertama di atas.</span></div>:<div className="admin-notes-list">{filtered.map(n=>editing===n.id?<article className="admin-note-card" key={n.id}><input className="admin-note-title-input" value={edit.title} onChange={e=>setEdit({...edit,title:e.target.value})}/><textarea className="admin-note-textarea" value={edit.content} onChange={e=>setEdit({...edit,content:e.target.value})}/><div className="admin-note-compose-meta">{[['status',STATUS],['priority',PRIORITIES.map(v=>[v,v])],['area',AREAS.map(v=>[v,v])]].map(([field,opts])=><select key={field} value={edit[field]} onChange={e=>setEdit({...edit,[field]:e.target.value})}>{opts.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>)}</div><div className="admin-note-edit-actions"><button className="admin-note-save compact" disabled={saving||!edit.content.trim()} onClick={update}>Simpan</button><button className="admin-note-action" onClick={()=>{setEditing(null);setEdit(null)}}>Batal</button></div></article>:<article className="admin-note-card" key={n.id}><div className="admin-note-card-head"><div><span className={`status-badge ${n.status==='resolved'?'status-good':n.status==='monitoring'?'status-warn':'status-bad'}`}>{statusLabel[n.status]||'Open'}</span> <span className="source-scope">{n.priority||'P2'}</span> <span className="source-scope">{n.area||'Admin'}</span><h3>{n.title}</h3></div></div><p className="admin-note-content">{n.content}</p><footer className="admin-note-footer"><div className="admin-note-date"><span>{fmt(n.createdAt)}</span><span>updated {fmt(n.updatedAt)}</span></div><div className="admin-note-actions"><button className="admin-note-action" onClick={()=>beginEdit(n)}>Edit</button><button className="admin-note-action danger" onClick={()=>remove(n.id)}>Hapus</button></div></footer></article>)}</div>}</section>;
}
