'use client';
import {useEffect,useMemo,useState} from 'react';

const statuses=['Belum Dikerjakan','Sedang Dikerjakan','Sudah Diperbaiki','Sudah Disesuaikan','Perlu Verifikasi','Blocked','Gagal','Selesai'];
const types=['Feature','Bug','Improvement','SEO','Scheduler','AI','UI','Deployment','Infrastructure','Security','Other'];
const priorities=['Low','Normal','High','Critical'];
const fmt=v=>{if(!v)return '-';const d=new Date(v);return Number.isNaN(d.getTime())?'-':new Intl.DateTimeFormat('id-ID',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'Asia/Jakarta'}).format(d)+' WIB'};
const errorText=async r=>{try{const j=await r.json();return j.error||'Request gagal'}catch{return 'Request gagal'}};

export default function AdminNotes({email}){
 const [tab,setTab]=useState('notes');const [notes,setNotes]=useState([]);const [work,setWork]=useState([]);const [pipeline,setPipeline]=useState({configured:false,runs:[],latest:null});const [title,setTitle]=useState('');const [content,setContent]=useState('');const [editing,setEditing]=useState(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [filters,setFilters]=useState({status:'',type:'',priority:'',q:''});
 const loadNotes=async()=>{const r=await fetch('/api/admin/notes',{cache:'no-store'});if(!r.ok)throw new Error(await errorText(r));setNotes(await r.json())};
 const migrateLegacy=async()=>{if(typeof window==='undefined')return;const flag=`berita-auto-admin-notes-migrated:v1`;if(localStorage.getItem(flag))return;const raw=localStorage.getItem(`berita-auto-admin-notes:${email}`);if(!raw){localStorage.setItem(flag,'1');return}try{const legacy=JSON.parse(raw);if(Array.isArray(legacy)&&legacy.length){const r=await fetch('/api/admin/notes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({legacyNotes:legacy})});if(!r.ok)throw new Error(await errorText(r))}localStorage.setItem(flag,'1')}catch(e){setMessage(`Migrasi catatan lama belum berhasil: ${e.message}`)}};
 const loadWork=async()=>{const qs=new URLSearchParams(Object.entries(filters).filter(([,v])=>v));const r=await fetch(`/api/admin/work-log?${qs}`,{cache:'no-store'});if(!r.ok)throw new Error(await errorText(r));const j=await r.json();setWork(j.items||[])};
 const loadPipeline=async()=>{const r=await fetch('/api/admin/pipeline',{cache:'no-store'});if(r.ok)setPipeline(await r.json())};
 useEffect(()=>{(async()=>{try{await loadNotes();await migrateLegacy();await loadNotes()}catch(e){setMessage(e.message)} })()},[]);
 useEffect(()=>{if(tab==='work'){loadWork().catch(e=>setMessage(e.message))}if(tab==='pipeline'){loadPipeline()}},[tab,filters.status,filters.type,filters.priority,filters.q]);
 useEffect(()=>{if(tab!=='pipeline')return;const t=setInterval(loadPipeline,15000);return()=>clearInterval(t)},[tab]);
 const reset=()=>{setTitle('');setContent('');setEditing(null)};
 const saveNote=async e=>{e.preventDefault();if(!content.trim())return;setBusy(true);try{const url=editing?`/api/admin/notes/${editing.id}`:'/api/admin/notes';const r=await fetch(url,{method:editing?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,content})});if(!r.ok)throw new Error(await errorText(r));const item=await r.json();setNotes(prev=>editing?prev.map(x=>x.id===item.id?item:x):[item,...prev]);reset();setMessage('Catatan tersimpan di database bersama.')}catch(e){setMessage(e.message)}finally{setBusy(false)}};
 const togglePin=async n=>{const r=await fetch(`/api/admin/notes/${n.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({isPinned:!n.isPinned})});if(r.ok){const item=await r.json();setNotes(prev=>prev.map(x=>x.id===item.id?item:x))}};
 const deleteNote=async n=>{if(!confirm('Hapus catatan ini untuk semua admin?'))return;const r=await fetch(`/api/admin/notes/${n.id}`,{method:'DELETE'});if(r.ok)setNotes(prev=>prev.filter(x=>x.id!==n.id))};
 const saveWork=async item=>{const r=await fetch(`/api/admin/work-log/${item.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(item)});if(r.ok)loadWork()};
 const summary=useMemo(()=>Object.fromEntries(statuses.map(s=>[s,work.filter(x=>x.status===s).length])),[work]);
 return <section className="admin-workspace"><div className="admin-workspace-head"><div><span className="admin-kicker">ADMIN WORKSPACE</span><h2>Catatan &amp; Pekerjaan</h2><p>Catatan tersimpan bersama di database persistent, sedangkan status pekerjaan memakai telemetry dan verifikasi nyata.</p></div>{message&&<div className="admin-inline-message">{message}</div>}</div><div className="admin-tabs"><button className={tab==='notes'?'active':''} onClick={()=>setTab('notes')}>Catatan</button><button className={tab==='work'?'active':''} onClick={()=>setTab('work')}>Pekerjaan &amp; Perbaikan</button><button className={tab==='pipeline'?'active':''} onClick={()=>setTab('pipeline')}>Automation / News Pipeline</button></div>
 {tab==='notes'&&<div className="admin-notes-panel"><form onSubmit={saveNote} className="admin-note-form"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Judul catatan"/><textarea value={content} onChange={e=>setContent(e.target.value)} placeholder="Tulis catatan untuk tim admin…" rows={5}/><div><button type="submit" disabled={busy}>{busy?'Menyimpan…':editing?'Simpan perubahan':'Tambah catatan'}</button>{editing&&<button type="button" className="ghost" onClick={reset}>Batal</button>}</div></form><div className="admin-note-list">{notes.length===0?<p className="muted">Belum ada catatan.</p>:notes.sort((a,b)=>Number(b.isPinned)-Number(a.isPinned)||String(b.updatedAt).localeCompare(String(a.updatedAt))).map(n=><article className={`admin-note-card${n.isPinned?' pinned':''}`} key={n.id}><div><span className="note-pin">{n.isPinned?'PIN':'CATATAN'}</span><h3>{n.title}</h3><p>{n.content}</p><small>Diperbarui {fmt(n.updatedAt)} · {n.updatedByEmail||n.createdByEmail}</small></div><div className="note-actions"><button onClick={()=>{setEditing(n);setTitle(n.title);setContent(n.content)}}>Edit</button><button onClick={()=>togglePin(n)}>{n.isPinned?'Lepas Pin':'Pin'}</button><button onClick={()=>deleteNote(n)} className="danger">Hapus</button></div></article>)}</div></div>}
 {tab==='work'&&<div className="admin-worklog"><div className="worklog-summary">{statuses.map(s=><div key={s}><strong>{summary[s]||0}</strong><span>{s}</span></div>)}</div><div className="worklog-filters"><input value={filters.q} onChange={e=>setFilters({...filters,q:e.target.value})} placeholder="Cari pekerjaan…"/><select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">Semua status</option>{statuses.map(s=><option key={s}>{s}</option>)}</select><select value={filters.type} onChange={e=>setFilters({...filters,type:e.target.value})}><option value="">Semua tipe</option>{types.map(s=><option key={s}>{s}</option>)}</select><select value={filters.priority} onChange={e=>setFilters({...filters,priority:e.target.value})}><option value="">Semua prioritas</option>{priorities.map(s=><option key={s}>{s}</option>)}</select></div><div className="worklog-list">{work.map(item=><article key={item.id} className="worklog-card"><div className="worklog-card-head"><div><span>{item.type} · {item.priority}</span><h3>{item.title}</h3></div><select value={item.status} onChange={e=>saveWork({...item,status:e.target.value})}>{statuses.map(s=><option key={s}>{s}</option>)}</select></div><p>{item.description}</p><dl><div><dt>Problem</dt><dd>{item.problem||'-'}</dd></div><div><dt>Fix</dt><dd>{item.fixDescription||'-'}</dd></div><div><dt>Verification</dt><dd>{item.verificationResult||'-'}</dd></div></dl><small>Updated {fmt(item.updatedAt)} · {item.updatedBy||item.createdBy}</small></article>)}</div></div>}
 {tab==='pipeline'&&<div className="admin-pipeline"><div className="pipeline-top"><div><span className={`pipeline-state ${pipeline.latest?.status==='RUNNING'?'running':''}`}>{pipeline.configured?(pipeline.latest?.status||'IDLE'):'DATABASE NOT CONFIGURED'}</span><h3>Automation / News Pipeline</h3><p>{pipeline.latest?.stage?`Stage terakhir: ${pipeline.latest.stage}`:'Belum ada telemetry worker tersimpan.'}</p></div>{pipeline.latest&&<div className="pipeline-metrics"><span>Provider <b>{pipeline.latest.summary?.provider||'-'}</b></span><span>AI <b>{pipeline.latest.summary?.aiDurationMs?`${pipeline.latest.summary.aiDurationMs} ms`:'-'}</b></span><span>Worker <b>{pipeline.latest.finishedAt&&pipeline.latest.startedAt?`${new Date(pipeline.latest.finishedAt)-new Date(pipeline.latest.startedAt)} ms`:'-'}</b></span></div>}</div><div className="pipeline-history">{(pipeline.runs||[]).map(r=><article key={r.id}><div><strong>{r.status}</strong><span>{r.stage}</span></div><div><b>{r.summary?.provider||'-'}</b><small>{r.published?'1 artikel dipublikasikan':'Tidak publish'}</small></div><time>{fmt(r.startedAt)}</time></article>)}</div></div>}
 </section>
}
