'use client';
import {useEffect,useState} from 'react';

export default function ArticleImageMigrationPanel(){
  const [data,setData]=useState(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(null);
  const load=()=>fetch('/api/admin-berita/article-image-migration',{cache:'no-store'}).then(r=>r.ok?r.json():null).then(setData).catch(()=>{});
  useEffect(()=>{load()},[]);
  const run=async()=>{setBusy(true);setMessage(null);try{const dry=await fetch('/api/admin-berita/article-image-migration',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({dryRun:true})});const preview=await dry.json().catch(()=>({}));if(!dry.ok)throw new Error(preview.error||'dry_run_failed');const count=Number(preview.wouldRepair||0);if(!count){setData(preview);setMessage('Tidak ada URL gambar legacy yang perlu diperbaiki.');return}if(!window.confirm(`Akan memperbaiki ${count} record URL gambar legacy. Data artikel dan Blob tidak dihapus. Lanjutkan?`))return;const exec=await fetch('/api/admin-berita/article-image-migration',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({dryRun:false})});const result=await exec.json().catch(()=>({}));if(!exec.ok)throw new Error(result.error||'migration_failed');setData(result);setMessage(`Selesai: ${result.repaired||0} record diperbaiki.`)}catch(error){setMessage(String(error?.message||'migration_failed'))}finally{setBusy(false)}};
  const health=data?.storageHealth;const totals=data?.totals||{};
  return <section className="admin-panel" style={{marginTop:16}}><div style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',flexWrap:'wrap'}}><div><p className="admin-label">IMAGE STORAGE &amp; MIGRATION</p><strong>IMAGE STORAGE: {health?.healthy?'Healthy':health?.code||'Unavailable'}</strong><div className="muted" style={{marginTop:6}}>Blob storage diperiksa read-only; URL Blob yang valid tetap dipertahankan.</div></div><button className="admin-secondary-button" onClick={run} disabled={busy}>{busy?'Memeriksa…':'Perbaiki URL Gambar Lama'}</button></div><div className="article-admin-summary" style={{marginTop:14}}>{[['IMAGE READY',Math.max(0,(data?.scanned||0)-(data?.missing||0))],['IMAGE MISSING',data?.missing||0],['IMAGE FAILED',data?.broken||0],['LEGACY IMAGE URL',data?.legacyUrls||0]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>{data?.wouldRepair!==undefined&&<small className="muted" style={{display:'block',marginTop:10}}>Dry-run: {data.wouldRepair} record akan diperbaiki · {data.legacyUrls||0} URL legacy terdeteksi · {totals.validBlob||0} Blob valid dipertahankan.</small>}{message&&<div className="article-action-notice" style={{marginTop:12}}><span>{message}</span></div>}</section>
}
