import {NextResponse} from 'next/server';
import {randomUUID} from 'node:crypto';
import {requireAdmin} from '../../../../lib/admin-guard.js';
import {persistenceConfigured,upsertIndexed,listJson,getJson,setJson} from '../../../../lib/persistence.js';
const INDEX='ba:notes:index',SEED_KEY='ba:notes:seed:v2';const key=id=>`ba:notes:${id}`;const clean=(v,max)=>String(v??'').trim().slice(0,max);const normalizeStatus=v=>['open','in_progress','monitoring','resolved','blocked'].includes(v)?v:'open';const normalizePriority=v=>['P0','P1','P2','P3'].includes(v)?v:'P2';const normalizeArea=v=>['Performance','SEO','Google','Admin','Automation','Berita','Iklan','Analytics','Navbar','Social','Infrastructure','System','Distribution','AI','Frontend','Backend'].includes(v)?v:'Admin';const progressFor=s=>s==='resolved'?100:s==='open'?0:s==='monitoring'?90:s==='in_progress'?50:null;
const note=(raw,email)=>{const status=normalizeStatus(raw.status),history=Array.isArray(raw.statusHistory)&&raw.statusHistory.length?raw.statusHistory:[{status,at:raw.createdAt||new Date().toISOString(),by:raw.createdBy||email}];return{id:raw.id||randomUUID(),title:clean(raw.title,160)||'Catatan tanpa judul',description:clean(raw.description||raw.content,10000),content:clean(raw.content||raw.description,10000),area:normalizeArea(raw.area),priority:normalizePriority(raw.priority),status,progress:Number.isFinite(Number(raw.progress))?Math.max(0,Math.min(100,Number(raw.progress))):progressFor(status),diagnosis:clean(raw.diagnosis,5000),actionsTaken:clean(raw.actionsTaken,8000),verification:clean(raw.verification,5000),resolution:clean(raw.resolution,5000),blocker:clean(raw.blocker,3000),remaining:clean(raw.remaining,3000),relatedCommit:clean(raw.relatedCommit,120),relatedDeployment:clean(raw.relatedDeployment,500),createdBy:raw.createdBy||email,createdByEmail:raw.createdByEmail||email,updatedBy:email,updatedByEmail:email,isPinned:Boolean(raw.isPinned??raw.pinned),createdAt:raw.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString(),statusHistory:history,deletedAt:null,resolutionNote:clean(raw.resolutionNote,5000),relatedUrl:clean(raw.relatedUrl,1000)} };
function deny(r){if(!r)return NextResponse.json({error:'Unauthorized'},{status:401});if(r.forbidden)return NextResponse.json({error:'Forbidden'},{status:403})}
const seeds=[
{title:'Production Core Web Vitals belum diukur',content:'TTFB, LCP, INP, dan CLS belum tersedia dari tooling lab/browser yang sah pada audit terakhir. Jangan mengarang angka.',description:'Audit measurement capability dan lakukan lab measurement saat tooling tersedia.',area:'Performance',priority:'P1',status:'open',progress:0,diagnosis:'Belum ada measurement tool yang dapat dipakai untuk angka production yang dapat dipertanggungjawabkan.',actionsTaken:'Audit capability dilakukan; tidak membuat angka sintetis.',verification:'Belum ada measurement evidence.',remaining:'Jalankan lab measurement TTFB/LCP/INP/CLS dengan browser tooling yang sah.',blocker:'Browser/lab measurement capability belum tersedia pada agent.'},
{title:'Google site name dan favicon menunggu recrawl',content:'Technical readiness tersedia di Production; perubahan hasil Google masih menunggu recrawl eksternal.',area:'Google',priority:'P2',status:'monitoring',progress:90,diagnosis:'Code/metadata dapat benar sebelum Google memperbarui hasil pencarian.',actionsTaken:'Favicon, WebSite metadata, canonical, robots dan sitemap diaudit.',verification:'Production technical checks tersedia; Google recrawl belum dapat dipaksa.',remaining:'Monitor Search Console/hasil Google sampai recrawl.',blocker:'External Google recrawl.'},
{title:'Admin CSS asset audit',content:'Production stylesheet Admin telah diaudit secara HTTP; authenticated visual verification perlu dilakukan di browser admin.',area:'Admin',priority:'P1',status:'monitoring',progress:90,diagnosis:'Asset response production dapat benar tetapi visual authenticated membutuhkan browser session.',actionsTaken:'admin.css dan admin-overrides.css dipertahankan dan HTTP asset behavior diaudit.',verification:'HTTP 200 + CSS content type; visual authenticated follow-up belum tersedia.',remaining:'Visual desktop/mobile/dark-light verification dengan authenticated browser.',blocker:'Authenticated browser visual session tidak tersedia pada agent.'},
{title:'Ads / Blob production',content:'Banner iklan dan Vercel Blob production sudah bekerja pada state yang terverifikasi.',area:'Iklan',priority:'P2',status:'resolved',progress:100,verification:'Production asset path dan Blob behavior telah diverifikasi.',actionsTaken:'Production Blob/ad asset regression dipertahankan.',resolution:'Resolved; monitor bila ada perubahan deployment.'},
{title:'SEO technical audit dan Search Intent',content:'Technical SEO diarahkan ke title, meta description, H1, canonical, NewsArticle, Breadcrumb, sitemap, robots, internal links, Search Intent dan duplicate safety.',area:'SEO',priority:'P1',status:'monitoring',progress:90,diagnosis:'Search Intent engine dan technical SEO safeguards tersedia; ranking Google tetap merupakan outcome eksternal.',actionsTaken:'Search Intent/query validation, canonical/schema checks, duplicate safeguards dan search-data abstraction diterapkan.',verification:'Production article routes dan metadata checks tersedia; ranking/recrawl belum merupakan bukti resolved.',remaining:'Monitor Search Console impressions/clicks/position dan kualitas query baru.',blocker:'Tidak ada blocker code; Google ranking/recrawl eksternal.'},
{title:'Ruang iklan dan kesiapan monetisasi',content:'Audit ads diarahkan pada slot yang tidak mengganggu UX, mobile/desktop, ads.txt, policy pages dan content quality. Jangan mengejar jumlah slot sebelum traffic/SEO sehat.',area:'Iklan',priority:'P2',status:'monitoring',progress:90,diagnosis:'Infrastructure ads dapat siap tanpa berarti network approval sudah tersedia.',actionsTaken:'Ads/Blob regression dipertahankan; production ad surface tidak diperbanyak secara agresif.',verification:'Existing ad asset works; network approval tidak diasumsikan.',remaining:'Monitor approval/readiness dan layout shift.',blocker:'Network approval bersifat eksternal jika belum tersedia.'},
{title:'Tampilan homepage',content:'Homepage perlu hero image yang proporsional, responsive image behavior, spacing dan animasi ringan hanya bila membantu UX.',area:'Frontend',priority:'P2',status:'in_progress',progress:50,diagnosis:'Visual homepage membutuhkan audit terarah agar tidak menambah payload/CLS.',actionsTaken:'Scope ditetapkan untuk hero sizing, responsive behavior dan lightweight motion.',verification:'Belum ada authenticated visual comparison final.',remaining:'Audit desktop/mobile production dan implement perubahan yang terbukti perlu.',blocker:'Tidak ada code blocker.'},
{title:'Notifikasi berita dan subscriber',content:'MVP specification untuk subscriber kategori/query perlu diselesaikan sebelum menambah service mahal.',area:'Backend',priority:'P3',status:'in_progress',progress:30,diagnosis:'Feature membutuhkan preference model dan notification delivery contract.',actionsTaken:'Scope MVP: subscription, category, optional query dan notification preference.',verification:'Belum production implemented.',remaining:'Implement persistence + delivery provider hanya setelah contract tervalidasi.',blocker:'Delivery infrastructure belum dipilih/diaktifkan.'}
];
async function ensureSeeds(email){if(await getJson(SEED_KEY))return;const existing=await listJson(INDEX),signatures=new Set(existing.map(n=>`${n.title}\n${n.content}`));for(const raw of seeds){const item=note(raw,email),sig=`${item.title}\n${item.content}`;if(signatures.has(sig))continue;await upsertIndexed(INDEX,key(item.id),item)}await setJson(SEED_KEY,{version:2,seededAt:new Date().toISOString()})}
export async function GET(){const r=await requireAdmin(),d=deny(r);if(d)return d;if(!persistenceConfigured())return NextResponse.json({error:'Persistent admin database is not configured'},{status:503});try{await ensureSeeds(r.email);const rows=await listJson(INDEX);return NextResponse.json(rows.sort((a,b)=>Date.parse(b.updatedAt||b.createdAt||0)-Date.parse(a.updatedAt||a.createdAt||0)))}catch(error){return NextResponse.json({error:'Gagal memuat Catatan & Perbaikan.',detail:error.message},{status:503})}}
export async function POST(request){const r=await requireAdmin(),d=deny(r);if(d)return d;if(!persistenceConfigured())return NextResponse.json({error:'Persistent admin database is not configured'},{status:503});try{const body=await request.json();if(Array.isArray(body?.legacyNotes)){const existing=await listJson(INDEX),signatures=new Set(existing.map(n=>`${n.title}\n${n.content}`)),imported=[];for(const raw of body.legacyNotes){const item=note(raw,r.email),sig=`${item.title}\n${item.content}`;if(!item.content||signatures.has(sig))continue;signatures.add(sig);item.createdByEmail=r.email;item.updatedByEmail=r.email;await upsertIndexed(INDEX,key(item.id),item);imported.push(item)}return NextResponse.json({imported})}const item=note(body,r.email);if(!item.content)return NextResponse.json({error:'Content is required'},{status:400});await upsertIndexed(INDEX,key(item.id),item);return NextResponse.json(item,{status:201})}catch(error){return NextResponse.json({error:'Unable to save note'},{status:400})}}
