import {NextResponse} from 'next/server';
import {randomUUID} from 'node:crypto';
import {requireAdmin} from '../../../../lib/admin-guard.js';
import {persistenceConfigured,upsertIndexed,listJson,getJson,setJson} from '../../../../lib/persistence.js';
const INDEX='ba:notes:index',SEED_KEY='ba:notes:seed:v1';const key=id=>`ba:notes:${id}`;const clean=(v,max)=>String(v??'').trim().slice(0,max);const normalizeStatus=v=>['open','monitoring','resolved'].includes(v)?v:'open';const normalizePriority=v=>['P1','P2','P3'].includes(v)?v:'P2';const normalizeArea=v=>['Performance','SEO','Google','Admin','Automation','Berita','Iklan','Analytics','Navbar','Social','Infrastructure'].includes(v)?v:'Admin';
const note=(raw,email)=>({id:raw.id||randomUUID(),title:clean(raw.title,160)||'Catatan tanpa judul',content:clean(raw.content,10000),area:normalizeArea(raw.area),priority:normalizePriority(raw.priority),status:normalizeStatus(raw.status),createdBy:raw.createdBy||email,createdByEmail:raw.createdByEmail||email,updatedBy:email,updatedByEmail:email,isPinned:Boolean(raw.isPinned??raw.pinned),createdAt:raw.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString(),deletedAt:null,resolutionNote:clean(raw.resolutionNote,5000),relatedUrl:clean(raw.relatedUrl,1000)});
function deny(r){if(!r)return NextResponse.json({error:'Unauthorized'},{status:401});if(r.forbidden)return NextResponse.json({error:'Forbidden'},{status:403})}
const seeds=[{title:'Production Core Web Vitals belum diukur',content:'TTFB, LCP, INP, dan CLS field/lab belum tersedia dari tooling yang sah pada audit terakhir. Jangan mengarang angka; ukur saat browser/lab tooling tersedia.',area:'Performance',priority:'P1',status:'open'},{title:'Google site name dan favicon menunggu recrawl',content:'Konfigurasi teknis Berita Auto dan favicon sudah tersedia di Production. Tampilan Google dapat tetap memakai nilai lama sampai Google melakukan recrawl.',area:'Google',priority:'P2',status:'monitoring'},{title:'Admin CSS asset audit',content:'Production mengirim stylesheet Admin dengan HTTP 200 dan Content-Type text/css. Import admin.css dan admin-overrides.css tetap ada; authenticated visual verification masih menjadi follow-up.',area:'Admin',priority:'P1',status:'monitoring'},{title:'Ads / Blob production',content:'Banner iklan dan Vercel Blob sudah bekerja pada state production yang terverifikasi.',area:'Iklan',priority:'P2',status:'resolved'}];
async function ensureSeeds(email){if(await getJson(SEED_KEY))return;const existing=await listJson(INDEX),signatures=new Set(existing.map(n=>`${n.title}\n${n.content}`));for(const raw of seeds){const item=note(raw,email),sig=`${item.title}\n${item.content}`;if(signatures.has(sig))continue;await upsertIndexed(INDEX,key(item.id),item)}await setJson(SEED_KEY,{version:1,seededAt:new Date().toISOString()})}
export async function GET(){const r=await requireAdmin(),d=deny(r);if(d)return d;if(!persistenceConfigured())return NextResponse.json({error:'Persistent admin database is not configured'},{status:503});try{await ensureSeeds(r.email);const rows=await listJson(INDEX);return NextResponse.json(rows.sort((a,b)=>Date.parse(b.updatedAt||b.createdAt||0)-Date.parse(a.updatedAt||a.createdAt||0)))}catch(error){return NextResponse.json({error:'Gagal memuat Catatan & Perbaikan.',detail:error.message},{status:503})}}
export async function POST(request){const r=await requireAdmin(),d=deny(r);if(d)return d;if(!persistenceConfigured())return NextResponse.json({error:'Persistent admin database is not configured'},{status:503});try{const body=await request.json();if(Array.isArray(body?.legacyNotes)){const existing=await listJson(INDEX),signatures=new Set(existing.map(n=>`${n.title}\n${n.content}`)),imported=[];for(const raw of body.legacyNotes){const item=note(raw,r.email),sig=`${item.title}\n${item.content}`;if(!item.content||signatures.has(sig))continue;signatures.add(sig);item.createdByEmail=r.email;item.updatedByEmail=r.email;await upsertIndexed(INDEX,key(item.id),item);imported.push(item)}return NextResponse.json({imported})}const item=note(body,r.email);if(!item.content)return NextResponse.json({error:'Content is required'},{status:400});await upsertIndexed(INDEX,key(item.id),item);return NextResponse.json(item,{status:201})}catch(error){return NextResponse.json({error:'Unable to save note'},{status:400})}}
