import path from 'node:path';
import fs from 'node:fs';
import {readArticles} from '../../../../lib/storage.js';
import {socialVisualProfile,socialCardText,buildSocialSlides,sanitizeCardText} from '../../../../lib/social-visual.js';
import {discoverImageSources,fetchValidatedImage} from '../../../../lib/social-image.js';
export const dynamic='force-dynamic';
export const runtime='nodejs';
const fontDir=path.join(process.cwd(),'assets','fonts');
const regularFont=path.join(fontDir,'NotoSans-Regular.ttf');
const boldFont=path.join(fontDir,'NotoSans-Bold.ttf');
const regularExists=fs.existsSync(regularFont);const boldExists=fs.existsSync(boldFont);
if(!regularExists||!boldExists)throw new Error(`social_card_bundled_font_missing:regular=${regularExists}:bold=${boldExists}`);
const fontconfigDir=path.join('/tmp','berita-auto-fontconfig');const runtimeFontconfig=path.join(fontconfigDir,'fonts.conf');fs.mkdirSync(fontconfigDir,{recursive:true});
const xml=`<?xml version="1.0"?><!DOCTYPE fontconfig SYSTEM "fonts.dtd"><fontconfig><dir>${fontDir}</dir><dir>/usr/share/fonts</dir><dir>/usr/local/share/fonts</dir><dir>/opt/fonts</dir><cachedir>/tmp/fontconfig</cachedir></fontconfig>`;fs.writeFileSync(runtimeFontconfig,xml,'utf8');process.env.FONTCONFIG_FILE=runtimeFontconfig;process.env.FONTCONFIG_PATH=fontconfigDir;
const {default:sharp}=await import('sharp');
const text=value=>sanitizeCardText(value);const arr=value=>Array.isArray(value)?value:Array.isArray(value?.items)?value.items:Array.isArray(value?.values)?value.values:[];
const clip=(value,max)=>text(value).slice(0,max).trim();
const esc=value=>clip(value,1800).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');
const wrap=(value,maxChars,maxLines)=>{const words=esc(value).split(/\s+/).filter(Boolean);const lines=[];let line='';for(const word of words){if(word.length>maxChars){if(line){lines.push(line);line='';}let rest=word;while(rest.length>maxChars&&lines.length<maxLines-1){lines.push(rest.slice(0,maxChars-1)+'-');rest=rest.slice(maxChars-1);}line=rest;continue;}const next=line?`${line} ${word}`:word;if(next.length<=maxChars)line=next;else{if(line)lines.push(line);line=word;if(lines.length>=maxLines)break;}}if(line&&lines.length<maxLines)lines.push(line);return lines.slice(0,maxLines);};
const tspans=(lines,x,dy)=>lines.map((line,index)=>`<tspan x="${x}" dy="${index?dy:0}">${line}</tspan>`).join('');
const fitHeadline=(value,maxWidth,maxLines=5)=>{const sizes=[68,64,60,56,52];for(const fontSize of sizes){const maxChars=Math.max(16,Math.floor(maxWidth/(fontSize*0.58)));const lines=wrap(value,maxChars,maxLines);const longest=Math.max(0,...lines.map(line=>line.length));const estimatedWidth=longest*fontSize*0.58;if(lines.length<=maxLines&&estimatedWidth<=maxWidth)return{lines,fontSize,lineHeight:Math.round(fontSize*1.08)};}const fontSize=52;const maxChars=Math.max(16,Math.floor(maxWidth/(fontSize*0.58)));return{lines:wrap(value,maxChars,maxLines),fontSize,lineHeight:56};};
async function fetchArticleHtml(article){const url=article?.sourceUrl||article?.source||article?.originalUrl||article?.sourceArticleUrl;try{if(!/^https:\/\//i.test(String(url||'')))return'';const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),2800);const response=await fetch(url,{headers:{Accept:'text/html'},signal:controller.signal,redirect:'follow',cache:'no-store'});const body=response.ok?await response.text():'';clearTimeout(timer);return body.slice(0,500000);}catch{return'';}}
async function resolveImages(article,html){const base=article?.sourceUrl||article?.originalUrl||article?.canonicalUrl||'';const candidates=discoverImageSources(article,html,base);const resolved=[];for(const candidate of candidates.slice(0,12)){const result=await fetchValidatedImage(candidate.url,{timeoutMs:2200});if(result.ok){resolved.push({provenance:candidate.provenance,url:result.url,...result});if(resolved.length>=2)break;}}return resolved;}
async function imageData(url){try{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),2500);const response=await fetch(url,{headers:{Accept:'image/avif,image/webp,image/jpeg,image/png'},signal:controller.signal,redirect:'follow',cache:'force-cache'});if(!response.ok){clearTimeout(timer);return null;}const bytes=Buffer.from(await response.arrayBuffer());clearTimeout(timer);if(!bytes.length)return null;const jpeg=await sharp(bytes).resize(1080,780,{fit:'cover',position:'attention',withoutEnlargement:false}).jpeg({quality:84,mozjpeg:true}).toBuffer();return`data:image/jpeg;base64,${jpeg.toString('base64')}`;}catch{return null;}}
function renderSvg(article,slide,slides,images){
 const profile=socialVisualProfile(article);const style=profile?.style||{accent:'#1d4ed8',icon:'NEWS'};const content=socialCardText(article,slide)||{title:'Berita terbaru',summary:''};const isCover=slide===1;const slideCount=Math.max(1,slides.length);
 const SAFE_HORIZONTAL=88;const SAFE_TOP=34;const SAFE_BOTTOM=56;const CONTENT_INSET=32;const canvasWidth=1080;const canvasHeight=1350;const right=canvasWidth-SAFE_HORIZONTAL;const contentWidth=right-SAFE_HORIZONTAL;const accent=esc(style.accent||'#1d4ed8');
 const title=clip(content.title||article.title,260);const summary=clip(content.summary||article.summary||article.excerpt,1200);const source=clip(article.publisher||article.sourceName||'Sumber publik',72);
 const bg=isCover?'#07111f':'#f6f8fb';const titleColor=isCover?'#ffffff':'#0b1728';const bodyColor='#172b40';const image=images[Math.min(slide-1,images.length-1)]||images[0]||null;
 const imageHeight=isCover?780:450;const titleWidth=contentWidth;const headline=fitHeadline(title,titleWidth,isCover?5:3);const titleHeight=headline.lines.length*headline.lineHeight;
 const titleY=isCover?382:510;const panelY=isCover?Math.max(760,titleY+titleHeight+34):Math.max(535,titleY+titleHeight+30);const summaryFont=28;const summaryMaxChars=Math.max(40,Math.floor((contentWidth-CONTENT_INSET*2)/(summaryFont*0.52)));const summaryLines=wrap(summary,summaryMaxChars,isCover?5:9);const summaryLineHeight=40;const panelPaddingTop=54;const ctaHeight=46;const panelBottomGap=24;const panelHeight=Math.max(isCover?300:340,panelPaddingTop+summaryLines.length*summaryLineHeight+28+ctaHeight+panelBottomGap);const boxY=panelY;const boxH=Math.min(panelHeight,canvasHeight-SAFE_BOTTOM-120-boxY);
 const ctaText='Baca Selengkapnya di berita-auto.vercel.app';const ctaX=SAFE_HORIZONTAL+CONTENT_INSET;const ctaWidth=520;const ctaY=boxY+boxH-28;const ctaBg=isCover?'#07111f':accent;const ctaFg='#ffffff';
 const category=clip(profile.category,34);const categoryFont=20;const categoryPadX=18;const categoryPadY=7;const categoryTextWidth=Math.max(1,category.length*categoryFont*0.56);const categoryWidth=Math.max(112,Math.min(contentWidth,Math.ceil(categoryTextWidth+categoryPadX*2)));const categoryHeight=categoryFont+categoryPadY*2+2;const categoryX=right-categoryWidth;const categoryY=SAFE_TOP;const categoryCenterX=categoryX+categoryWidth/2;const categoryCenterY=categoryY+categoryHeight/2;
 const imageTag=image?`<image href="${image}" x="0" y="0" width="${canvasWidth}" height="${imageHeight}" preserveAspectRatio="xMidYMid slice"/>`:'';const fallbackVisual=`<rect x="0" y="0" width="${canvasWidth}" height="${imageHeight}" fill="${accent}" fill-opacity=".16"/><circle cx="850" cy="230" r="260" fill="${accent}" fill-opacity=".12"/><circle cx="180" cy="620" r="360" fill="#ffffff" fill-opacity=".035"/>`;
 const overlay=isCover?`<rect x="0" y="0" width="${canvasWidth}" height="${imageHeight}" fill="url(#heroGradient)"/>`:`<rect x="0" y="0" width="${canvasWidth}" height="${imageHeight}" fill="url(#detailGradient)"/>`;
 const titleSvg=`<text x="${SAFE_HORIZONTAL}" y="${titleY}" fill="${titleColor}" font-family="Noto Sans" font-size="${headline.fontSize}" font-weight="700" letter-spacing="-0.7">${tspans(headline.lines,SAFE_HORIZONTAL,headline.lineHeight)}</text>`;
 const summaryY=boxY+panelPaddingTop;const summarySvg=`<text x="${SAFE_HORIZONTAL+CONTENT_INSET}" y="${summaryY}" fill="${bodyColor}" font-family="Noto Sans" font-size="${summaryFont}" font-weight="400">${tspans(summaryLines,SAFE_HORIZONTAL+CONTENT_INSET,summaryLineHeight)}</text>`;
 const summaryBox=`<rect x="${SAFE_HORIZONTAL}" y="${boxY}" width="${contentWidth}" height="${boxH}" rx="28" fill="#ffffff" fill-opacity=".98" stroke="#dbe5ee" stroke-width="1.5"/>`;
 const header=`<g><text x="${SAFE_HORIZONTAL}" y="76" fill="${isCover?'#ffffff':'#0b1728'}" font-family="Noto Sans" font-size="29" font-weight="900" letter-spacing=".4">BERITA AUTO</text><text x="${SAFE_HORIZONTAL}" y="112" fill="${isCover?'#d8e6f2':'#66788b'}" font-family="Noto Sans" font-size="18" font-weight="800">${isCover?'BERITA TERKINI':'POIN PENTING'} · ${slide}/${slideCount}</text><rect x="${categoryX}" y="${categoryY}" width="${categoryWidth}" height="${categoryHeight}" rx="${categoryHeight/2}" fill="${accent}" fill-opacity=".98" stroke="#ffffff" stroke-opacity=".28" stroke-width="1"/><text x="${categoryCenterX}" y="${categoryCenterY}" text-anchor="middle" dominant-baseline="middle" fill="#ffffff" font-family="Noto Sans" font-size="${categoryFont}" font-weight="800">${esc(category)}</text></g>`;
 const cta=`<rect x="${ctaX}" y="${ctaY-ctaHeight+4}" width="${ctaWidth}" height="${ctaHeight}" rx="${ctaHeight/2}" fill="${ctaBg}" fill-opacity=".98"/><text x="${ctaX+22}" y="${ctaY-11}" fill="${ctaFg}" font-family="Noto Sans" font-size="20" font-weight="800">${esc(ctaText)}</text>`;
 const footer=`<text x="${SAFE_HORIZONTAL}" y="1292" fill="${isCover?'#dce8f2':'#71849a'}" font-family="Noto Sans" font-size="20" font-weight="700">${esc(source)}</text><text x="${right}" y="1292" text-anchor="end" fill="${isCover?'#ffffff':accent}" font-family="Noto Sans" font-size="36" font-weight="900">BA</text>`;
 return`<svg xmlns="http://www.w3.org/2000/svg" width="${canvasWidth}" height="${canvasHeight}" viewBox="0 0 ${canvasWidth} ${canvasHeight}"><defs><linearGradient id="heroGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#000" stop-opacity=".08"/><stop offset=".46" stop-color="#000" stop-opacity=".12"/><stop offset="1" stop-color="#000" stop-opacity=".86"/></linearGradient><linearGradient id="detailGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${accent}" stop-opacity=".05"/><stop offset="1" stop-color="${accent}" stop-opacity=".16"/></linearGradient></defs><rect width="${canvasWidth}" height="${canvasHeight}" fill="${bg}"/>${image?imageTag:fallbackVisual}${overlay}${header}${titleSvg}${summaryBox}${summarySvg}${cta}${footer}</svg>`;}
export function normalizeSocialArticle(article={}){const source=article&&typeof article==='object'?article:{};return{...source,id:text(source.id),title:text(source.title)||'Berita terbaru',summary:text(source.summary||source.excerpt),excerpt:text(source.excerpt||source.summary),content:text(source.content||source.body||source.text),body:text(source.body),category:text(source.category)||'Berita',publisher:text(source.publisher||source.sourceName)||'Sumber publik',sourceName:text(source.sourceName||source.publisher)||'Sumber publik',sourceUrl:text(source.sourceUrl||source.source||source.originalUrl),canonicalUrl:text(source.canonicalUrl),imageUrl:text(source.imageUrl),topics:arr(source.topics),keywords:arr(source.keywords),entities:arr(source.entities),paragraphs:arr(source.paragraphs),slides:arr(source.slides)};}
export async function GET(request,{params}){const started=Date.now();const {articleId}=await params;const raw=(await readArticles()).find(item=>item.id===articleId);if(!raw)return new Response('Not found',{status:404});const article=normalizeSocialArticle(raw);const url=new URL(request.url);const slide=Math.max(1,Number(url.searchParams.get('slide')||1));const slides=buildSocialSlides(article);if(slide>slides.length)return new Response('Slide not found',{status:404});const html=await fetchArticleHtml(article);const resolved=await resolveImages(article,html);const imageDataUrls=[];for(const item of resolved){const data=await imageData(item.url);if(data)imageDataUrls.push(data);if(imageDataUrls.length>=2)break;}const renderStarted=Date.now();const svg=renderSvg(article,slide,slides,imageDataUrls);const jpeg=await sharp(Buffer.from(svg)).jpeg({quality:86,mozjpeg:true}).toBuffer();console.log(`[social-card] articleId=${articleId} slide=${slide} image=${resolved[0]?.provenance||'FALLBACK'} image2=${resolved[1]?.provenance||'NONE'} slides=${slides.length} renderMs=${Date.now()-renderStarted} totalMs=${Date.now()-started}`);return new Response(jpeg,{status:200,headers:{'Content-Type':'image/jpeg','Cache-Control':'public, max-age=300, s-maxage=300, stale-while-revalidate=600','Content-Length':String(jpeg.length),'X-Social-Card-Render':'valid','X-Social-Card-Slide-Count':String(slides.length),'X-Social-Card-Image-Provenance':String(resolved[0]?.provenance||'FALLBACK'),'X-Social-Card-Image-2-Provenance':String(resolved[1]?.provenance||'NONE'),'X-Social-Card-Font-Source':'bundled-ttf'}});}
