import { classifyCategory } from './category.js';

const NORMAL_MAX = 2;
const DELAYED_MAX = 2;
const STALE_MAX = 2;
const LONG_OUTAGE_MAX = 2;
const HARD_MAX = 2;
const LOW_WATERMARK = 30;
const QUEUE_TARGET = 60;
const QUEUE_MAX = 120;
const MAX_AGE_MS = 12 * 60 * 60 * 1000;
const DIVERSITY_WINDOW = 10;
const DIVERSITY_SHARE_LIMIT = 0.35;

function ageMs(value, now) { const t = Date.parse(value || ''); return Number.isFinite(t) ? Math.max(0, now - t) : Infinity; }
function freshness(value, now) { const age = ageMs(value, now); if (age <= 2 * 60 * 60 * 1000) return 100; if (age <= 6 * 60 * 60 * 1000) return 70; if (age <= 12 * 60 * 60 * 1000) return 35; return 0; }
function publisher(item) { const raw = String(item?.publisher || item?.sourceName || '').trim(); if (!raw) return 'unknown'; const known = [['ANTARA','antara'],['Liputan6','liputan6'],['CNN Indonesia','cnn indonesia'],['CNBC Indonesia','cnbc indonesia'],['Media Indonesia','media indonesia'],['Tribunnews','tribunnews']]; const hit = known.find(([,needle]) => raw.toLowerCase().includes(needle)); return hit ? hit[0] : raw; }
function sourcePenalty(item, history = []) { const name = publisher(item); const recent = history.slice(0,DIVERSITY_WINDOW); const counts = new Map(); for (const row of recent) counts.set(publisher(row),(counts.get(publisher(row))||0)+1); const sameCount=counts.get(name)||0; let consecutive=0; for(const row of recent){if(publisher(row)!==name)break;consecutive++;} const share=recent.length?sameCount/recent.length:0; let penalty=0; if(consecutive>=2)penalty+=140; if(share>=DIVERSITY_SHARE_LIMIT)penalty+=100+(share-DIVERSITY_SHARE_LIMIT)*200; else penalty+=sameCount*8; return penalty; }
function sourceBonus(item, history = []) { return history.some(row=>publisher(row)===publisher(item))?0:24; }
function priority(item, now, recentHistory = []) { const category=item.category||classifyCategory(item); const breaking=/breaking|darurat|terkini|meninggal|gempa|kebakaran|banjir|evakuasi/i.test(`${item.title} ${item.summary||''}`)?25:0; const international=category==='Internasional'?10:0; const weight=Number.isFinite(Number(item.sourceWeight))?Number(item.sourceWeight):1; return freshness(item.publishedAt,now)+breaking+international+weight*5+sourceBonus(item,recentHistory)-sourcePenalty(item,recentHistory); }
function categoryWeight(category, counts) { const count=counts.get(category)||0; return Math.max(0,20-count*8); }
export function recentPublicationRate(published=[]) { const stamps=published.slice(0,6).map(x=>Date.parse(x.sitePublishedAt||x.createdAt||'')).filter(Number.isFinite); if(stamps.length<2)return 0; let totalGap=0; for(let i=0;i<stamps.length-1;i++)totalGap+=Math.abs(stamps[i]-stamps[i+1]); const avgGapMinutes=(totalGap/(stamps.length-1))/60000; return avgGapMinutes>0?60/avgGapMinutes:0; }
export function publicationPlan(published=[],pending=[],now=Date.now()) { const pendingCount=pending.length; if(!pendingCount)return{mode:'idle',maxPublish:0,gapMinutes:0,pendingCount,recentRatePerHour:recentPublicationRate(published)}; const lastStamp=Date.parse(published[0]?.sitePublishedAt||published[0]?.createdAt||''); if(!Number.isFinite(lastStamp))return{mode:'live',maxPublish:NORMAL_MAX,gapMinutes:Infinity,pendingCount,recentRatePerHour:recentPublicationRate(published)}; const gapMinutes=Math.max(0,(now-lastStamp)/60000); const recentRatePerHour=recentPublicationRate(published); if(gapMinutes<10)return{mode:'normal',maxPublish:NORMAL_MAX,gapMinutes,pendingCount,recentRatePerHour}; if(gapMinutes<20)return{mode:'delayed',maxPublish:DELAYED_MAX,gapMinutes,pendingCount,recentRatePerHour}; if(gapMinutes<45)return{mode:'stale',maxPublish:STALE_MAX,gapMinutes,pendingCount,recentRatePerHour}; return{mode:'long-outage',maxPublish:LONG_OUTAGE_MAX,gapMinutes,pendingCount,recentRatePerHour}; }
export function selectIngestionCandidates(items,seen,pending=[],existing=[],now=Date.now()) { const pendingFingerprints=new Set(pending.map(x=>x.fingerprint).filter(Boolean)); const pendingTitles=new Set(pending.map(x=>x.titleFingerprint).filter(Boolean)); const publishedFingerprints=seen instanceof Set?seen:new Set(existing.map(x=>x.fingerprint).filter(Boolean)); const publishedTitles=new Set(existing.map(x=>x.titleFingerprint).filter(Boolean)); const unique=new Map(); for(const raw of items){const fingerprint=raw.fingerprint;const titleFingerprint=raw.titleFingerprint;if(!fingerprint||publishedFingerprints.has(fingerprint)||pendingFingerprints.has(fingerprint)||unique.has(fingerprint))continue;if(titleFingerprint&&(publishedTitles.has(titleFingerprint)||pendingTitles.has(titleFingerprint)))continue;if(ageMs(raw.publishedAt,now)>MAX_AGE_MS)continue;const category=classifyCategory(raw);unique.set(fingerprint,{...raw,category,queuedAt:new Date(now).toISOString(),priority:0});} const candidates=[...unique.values()]; const counts=new Map(pending.map(x=>[x.category,pending.filter(y=>y.category===x.category).length])); const recentHistory=existing.slice(0,DIVERSITY_WINDOW); for(const item of candidates)item.priority=priority(item,now,recentHistory)+categoryWeight(item.category,counts); candidates.sort((a,b)=>b.priority-a.priority||Date.parse(b.publishedAt||0)-Date.parse(a.publishedAt||0)||publisher(a).localeCompare(publisher(b))||String(a.fingerprint).localeCompare(String(b.fingerprint))); const target=Math.min(12,Math.max(0,QUEUE_MAX-pending.length)); const buckets=new Map(); for(const item of candidates){if(!buckets.has(item.category))buckets.set(item.category,[]);buckets.get(item.category).push(item);} const categoryKeys=[...buckets.keys()].sort((a,b)=>Math.max(...buckets.get(b).map(x=>x.priority))-Math.max(...buckets.get(a).map(x=>x.priority))||a.localeCompare(b)); const selected=[]; let round=0; while(selected.length<target){let progressed=false;for(const category of categoryKeys){const bucket=buckets.get(category);if(round<bucket.length&&selected.length<target){selected.push(bucket[round]);progressed=true;}}if(!progressed)break;round++;} return{items:selected,queueTarget:QUEUE_TARGET,queueMax:QUEUE_MAX}; }
export function selectPublication(pending,history=[],now=Date.now()) { if(!pending.length)return null; const recentCategories=history.slice(0,6).map(x=>x.category).filter(Boolean); const recentHistory=history.slice(0,DIVERSITY_WINDOW); const scored=pending.map((item,index)=>{const freshnessScore=freshness(item.publishedAt,now);const breaking=/breaking|darurat|gempa|kebakaran|banjir|evakuasi/i.test(`${item.title} ${item.summary||''}`)?35:0;const categoryRotation=recentCategories.includes(item.category)?-20:15;const diversityPenalty=sourcePenalty(item,recentHistory);const diversityBonus=sourceBonus(item,recentHistory);const international=item.category==='Internasional'?12:0;const sourceWeight=Number.isFinite(Number(item.sourceWeight))?Number(item.sourceWeight):1;return{...item,_score:freshnessScore+breaking+categoryRotation+diversityBonus+sourceWeight*4+international-diversityPenalty-index*0.01};}); scored.sort((a,b)=>b._score-a._score||Date.parse(b.publishedAt||0)-Date.parse(a.publishedAt||0)||publisher(a).localeCompare(publisher(b))||String(a.fingerprint).localeCompare(String(b.fingerprint))); const chosen={...scored[0]}; delete chosen._score; return chosen; }
export const queueConfig={NORMAL_MAX,DELAYED_MAX,STALE_MAX,LONG_OUTAGE_MAX,HARD_MAX,LOW_WATERMARK,QUEUE_TARGET,QUEUE_MAX,MAX_AGE_MS,DIVERSITY_WINDOW,DIVERSITY_SHARE_LIMIT};
