import {NextResponse} from 'next/server';
import {auth} from '../../../../../auth.js';
import {withPersistenceSource,setMembers,mgetJson,getJson} from '../../../../../lib/persistence.js';
import {INSTAGRAM_PUBLISH_QUEUE_INDEX,INSTAGRAM_PUBLISH_THROTTLE_KEY,INSTAGRAM_PUBLISHING_USAGE_KEY} from '../../../../../lib/instagram-publish-queue.js';
const REVIEW_ITEM=id=>`ba:social:instagram:review:item:${id}`;const FALLBACK='/branding/instagram-profile-ba.svg';
function queued(row){return ['QUEUED','WAITING_META'].includes(String(row?.status||'').toUpperCase())}function sort(a,b){return Number(b?.priority||0)-Number(a?.priority||0)||Date.parse(a?.queuedAt||a?.createdAt||'')-Date.parse(b?.queuedAt||b?.createdAt||'')}function thumb(row){return String(row?.cardUrls?.[0]||row?.previewUrl||row?.sourceImageUrl||row?.imageOriginUrl||FALLBACK)}
async function authorized(){let session=null;try{session=await auth()}catch{return false}const allowed=(process.env.ADMIN_EMAILS||'').split(',').map(v=>v.trim().toLowerCase()).filter(Boolean);const email=session?.user?.email?.trim().toLowerCase();return Boolean(email&&allowed.includes(email))}
export const dynamic='force-dynamic';export const runtime='nodejs';
export async function GET(request){if(!await authorized())return NextResponse.json({error:'Unauthorized'},{status:401,headers:{'Cache-Control':'no-store'}});const url=new URL(request.url);const page=Math.max(1,Number(url.searchParams.get('page')||1)||1);const limit=Math.max(1,Math.min(20,Number(url.searchParams.get('limit')||10)||10));const started=Date.now();try{const result=await withPersistenceSource('admin-instagram-queue',async()=>{const keys=await setMembers(INSTAGRAM_PUBLISH_QUEUE_INDEX);const values=keys.length?await mgetJson(keys):[];const rows=values.filter(queued).sort(sort);const total=rows.length;const start=(page-1)*limit;const selected=rows.slice(start,start+limit);const reviewValues=selected.length?await mgetJson(selected.map(row=>REVIEW_ITEM(row.queueId))):[];const throttle=await getJson(INSTAGRAM_PUBLISH_THROTTLE_KEY);const usage=await getJson(INSTAGRAM_PUBLISHING_USAGE_KEY);const nextProbeAt=throttle?.nextProbeAt||throttle?.estimatedResumeAt||null;const items=selected.map((row,i)=>{const review=reviewValues[i]||{};const status=String(row.status||'').toUpperCase();return{id:row.queueId,queueId:row.queueId,title:row.title||review.title||'Berita',position:start+i+1,attemptCount:Number(row.publishAttemptCount||review.publishAttemptCount||0),publishAttemptCount:Number(row.publishAttemptCount||review.publishAttemptCount||0),status,reason:row.blockedReason||review.blockedReason||null,blockedReason:row.blockedReason||review.blockedReason||null,priority:Number(row.priority||0),thumbnailUrl:thumb(review),articleUrl:row.canonicalUrl||review.canonicalUrl||null,canonicalUrl:row.canonicalUrl||review.canonicalUrl||null,effectiveEstimatedResumeAt:status==='WAITING_META'&&throttle?.active&&nextProbeAt?nextProbeAt:(row.estimatedResumeAt||null)}});return{page,limit,items,total,pageCount:Math.max(1,Math.ceil(total/limit)),counts:{queued:rows.filter(r=>String(r.status||'').toUpperCase()==='QUEUED').length,waitingMeta:rows.filter(r=>String(r.status||'').toUpperCase()==='WAITING_META').length},throttle:throttle||{active:false},publishingUsage:usage||null,refreshedAt:new Date().toISOString()}});const payload=JSON.stringify(result);console.log('[instagram-admin-queue]',JSON.stringify({page,limit,items:result.items.length,redisCommands:result.items.length?5:4,payloadBytes:Buffer.byteLength(payload),durationMs:Date.now()-started}));return new NextResponse(payload,{status:200,headers:{'Content-Type':'application/json','Cache-Control':'private, max-age=10, stale-while-revalidate=30'}})}catch(error){console.error('[instagram-admin-queue]',JSON.stringify({stage:'read',code:error?.code||'PERSISTENCE_ERROR',message:String(error?.message||error).slice(0,240),durationMs:Date.now()-started}));return NextResponse.json({error:'Instagram queue temporarily unavailable.'},{status:200,headers:{'Cache-Control':'private, max-age=5'}})}}
