import {NextResponse} from 'next/server';
import {requireAdmin} from '../../../../../lib/admin-guard.js';
import {editInstagramReviewCaption,getInstagramReviewSnapshot,removeInstagramReviewItem} from '../../../../../lib/instagram-review.js';
import {repairInstagramReviewItem} from '../../../../../lib/instagram-review-repair.js';
import {getJson,setJson,acquireLock,releaseLock} from '../../../../../lib/persistence.js';
export const dynamic='force-dynamic';
export const runtime='nodejs';
const itemKey=id=>`ba:social:instagram:review:item:${id}`;
async function guard(){const admin=await requireAdmin();if(!admin)return NextResponse.json({error:'Unauthorized'},{status:401,headers:{'Cache-Control':'no-store'}});if(admin.forbidden)return NextResponse.json({error:'Forbidden'},{status:403,headers:{'Cache-Control':'no-store'}});return admin;}
async function safeRemove(queueId,admin){const token=`admin-remove:${queueId}:${Date.now()}`;const lockKey=`ba:social:instagram:publish:${queueId}`;if(!(await acquireLock(lockKey,token,180)))throw new Error('Posting sedang diproses. Tunggu proses selesai.');try{const current=await getJson(itemKey(queueId));if(!current)throw new Error('review_item_not_found');if(current.status==='PUBLISHING')throw new Error('Posting sedang diproses. Tunggu proses selesai.');if(current.status==='POSTED')throw new Error('Posting yang sudah berhasil tidak dapat dihapus dari history.');if(!['READY','FAILED','ATTENTION','PERLU_PERHATIAN'].includes(String(current.status||'').toUpperCase()))throw new Error('review_item_not_removable');const row=await removeInstagramReviewItem(queueId);await setJson(`ba:social:instagram:review:removed:${current.articleId}`,{articleId:current.articleId,queueId,removedAt:row.removedAt,removedBy:admin?.email||admin?.user?.email||null,removeReason:'admin_queue_delete'});return row;}finally{await releaseLock(lockKey,token).catch(()=>{});}}
export async function GET(){const denied=await guard();if(denied instanceof NextResponse)return denied;return NextResponse.json(await getInstagramReviewSnapshot(),{status:200,headers:{'Cache-Control':'no-store'}});}
export async function POST(request){const admin=await guard();if(admin instanceof NextResponse)return admin;try{const body=await request.json();if(body?.action!=='retry')return NextResponse.json({error:'unsupported_action'},{status:400});const queueId=String(body?.queueId||'');const row=await getJson(itemKey(queueId));if(!row)throw new Error('review_item_not_found');if(['REMOVED','POSTED','PUBLISHING'].includes(row.status))throw new Error('review_item_not_retryable');const result=await repairInstagramReviewItem(queueId,{now:Date.now()});if(result.status==='recovered'||result.status==='failed')return NextResponse.json({status:result.recovered?'recovered':'retry_failed',item:result.item},{status:200,headers:{'Cache-Control':'no-store'}});if(result.status==='skipped')return NextResponse.json({status:'retry_skipped',reason:result.reason,item:result.item},{status:409,headers:{'Cache-Control':'no-store'}});throw new Error('review_item_retry_failed');}catch(error){return NextResponse.json({error:String(error?.message||error).slice(0,240)},{status:409,headers:{'Cache-Control':'no-store'}})}}
export async function PATCH(request){const denied=await guard();if(denied instanceof NextResponse)return denied;try{const body=await request.json();const row=await editInstagramReviewCaption(String(body?.queueId||''),body?.caption);return NextResponse.json({status:'updated',item:row},{status:200,headers:{'Cache-Control':'no-store'}})}catch(error){return NextResponse.json({error:String(error?.message||error).slice(0,240)},{status:400,headers:{'Cache-Control':'no-store'}})}}
export async function DELETE(request){const admin=await guard();if(admin instanceof NextResponse)return admin;try{const body=await request.json();if(Array.isArray(body?.queueIds)){const ids=[...new Set(body.queueIds.map(String).filter(Boolean))];const removed=[];for(const queueId of ids){try{removed.push(await safeRemove(queueId,admin))}catch(error){if(String(error?.message||error).includes('Posting sedang diproses'))throw error;}}return NextResponse.json({status:'removed',count:removed.length,items:removed},{status:200,headers:{'Cache-Control':'no-store'}});}const row=await safeRemove(String(body?.queueId||''),admin);return NextResponse.json({status:'removed',item:row},{status:200,headers:{'Cache-Control':'no-store'}})}catch(error){return NextResponse.json({error:String(error?.message||error).slice(0,240)},{status:409,headers:{'Cache-Control':'no-store'}})}}
